### ISSUE TITLE
Brickman adds multiple '.err.log' files to the File Browser

### ISSUE THREAD

**Issue by cavenel** [ev3dev/ev3dev#1004]
### What are you trying to do?
I am trying to launch a program `myprogram.py` from Brickman.

### What did you expect to happen?
A single `myprogram.py.err.log` to be displayed after the program is killed.

### What actually happened?
A new `myprogram.py.err.log` is added in the File Browser after the program is killed, even though the file already exists. Which means if you launch your program ten times it will show ten `myprogram.py.err.log` lines.
As an addition, this can sometimes move the vertical scroll of Brickman, making your actual file selection (in the File Browser) out of the screen.

### What hardware and software are you using (including version numbers)?

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-10-24
Kernel version:     4.9.49-ev3dev-1.5.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165343581F
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
At long last... fixed in `brickman 0.10.2`
