### ISSUE TITLE
Auto connect wifi 

### ISSUE THREAD

**Issue by YuHanChen04** [ev3dev/ev3dev#1005]
**System information:**

BrickPi with a Raspberry Pi3 model B
I installed ev3dev using this image file:rpi-ev3dev-jessie-2017-09-14.img
Version : unknown 
Computer: Mac OS Sierra
Network: WiFi & Wired network (the same domain)

**About the  issue:**

I want to auto connect wifi when the brickpi of brickPi booting

## And I try to command sudo nano /etc/wpa_supplicant/wpa_supplicant.conf 
This file didn't exist, 
I wnat to ask what could I  set up it?

thanks  yhc!

**Comment by dlech** [comment]
We use  ConnMan for network management. From the command line, run `connmanctl`.

Resources:
* https://manpages.debian.org/stretch/connman/connmanctl.1.en.html
* https://wiki.archlinux.org/index.php/ConnMan
