### ISSUE TITLE
Go into single user mode to reset forgotten password?

### ISSUE THREAD

**Issue by stormingrobots** [ev3dev/ev3dev#1009]
### What are you trying to do?
lost password

### What did you expect to happen?
cannot login 

### What actually happened?
cannot login

### What hardware and software are you using (including version numbers)?
revision 006 4.4.87-22-ev3dev-ev3

**Comment by dlech** [comment]
I don't know of a way to boot to single user mode.

You could try putting the SD card in another Linux computer and edit `/etc/passwd` and `/etc/shadow` manually to clear the password like [this](https://askubuntu.com/a/84697/376284).

Or, if you don't care about losing files, you can just re-flash the SD card.

**Comment by ghost** [comment]
If you happen to have a similar ARM device (like Beaglebone) you can put the SD card in it and chroot, then change the password from there.

This is the method I use when I'm too lazy to figure out what password it's supposed to be.
