### ISSUE TITLE
Question about powersafe

### ISSUE THREAD

**Issue by zhenyolka** [ev3dev/ev3dev#1012]
Hello! Sorry for my English. I use ev3dev-strech on EV3 platform.
Can you say me: Which firmware(stock or ev3dev) is more energy economy?
I write it issue, because i think that stock firmware more economy.
I say true?

**Comment by dlech** [comment]
Have you done a test to measure the difference?

My experience has been that what you plug into the EV3 makes more of a difference in power consumption than any software. I have measured this with an amp meter. When you plug in motors, sensors or USB devices, there is a measurable difference in the current. But I could not measure any difference between using 100% CPU or not running any programs at all. It has been so long that I can't remember if I measured a difference between the official firmware and ev3dev.
