### ISSUE TITLE
Project won't build due to javadoc error in Sysfs.java (line 67)

### ISSUE THREAD

**Issue by phowson** [ev3dev/ev3dev#1019]
### What are you trying to do?
Run mvn install for this project, from the default branch.

### What did you expect to happen?
The project to correctly build

### What actually happened?
The project does not build due to a minor javadoc error on Sysfs.java, line 67, requires a one-line change. I've removed the `@param` from my local copy and then I can build your project without issue.

`
[ERROR] D:\devel\lego\ev3dev-lang-java\src\main\java\org\ev3dev\io\Sysfs.java:67: error: @param name not found
[ERROR] * @param enabled Enabled
[ERROR] ^
`

**Comment by dlech** [comment]
Which ev3dev-lang-java are you using?

**Comment by jabrena** [comment]
I think that he is using this library:
https://github.com/mob41/ev3dev-lang-java
https://github.com/mob41/ev3dev-lang-java/tree/develop/src/main/java/org/ev3dev/io

**Comment by a1aw** [comment]
Noted. I will look through the JavaDoc problems these days. Thanks!
