### ISSUE TITLE
MBIM support in kernel

### ISSUE THREAD

**Issue by akosladanyi** [ev3dev/ev3dev#1028]
Tried to use a Vodafone/Huawei K5150 4G USB dongle with an EV3. To get it working I had to compile a custom kernel with CONFIG_USB_NET_CDC_MBIM enabled. Would it be possible to enable this in the default kernel config?

**Comment by dlech** [comment]
Yes, we can do that. Which kernel are you using?

**Comment by akosladanyi** [comment]
4.9.58-ev3dev-1.6.0-ev3

**Comment by dlech** [comment]
Fix released in `4.14.35-ev3dev-2.0.0-ev3` kernel.
