### ISSUE TITLE
How do I detect events from sensors?

### ISSUE THREAD

**Issue by eahutchins** [ev3dev/ev3dev#104]
I just tried `tail -f /sys/class/msensor/sensor0/value0` and didn't see the value change as I tried toggling a touch sensor... is there a way to select/poll on /sys fs mounts, or more broadly how do I get asynchronous notifications of sensor changes?

**Comment by dlech** [comment]
This is something that has come up again more recently. My current line of thought is that the best way to do this is using a character device similar to the Linux input/event subsystem.

**Comment by dlech** [comment]
I'm closing this issue in favor of #498 since this issue is quite old and no longer has much relevant information. Any further comments should be made on #498.

**Comment by WasabiFan** [comment]
> I'm closing this issue...

Uhhhh... the issue is still open half an hour later :wink: Any chance that you forgot about the "closing" bit?

**Comment by dlech** [comment]
must have hit the wrong button.
