### ISSUE TITLE
nxt-python ev3 controlling nxt

### ISSUE THREAD

**Issue by Vienhackar** [ev3dev/ev3dev#1046]
I am trying to allow the ev3 to master over the nxt, I found this [post](https://bricks.stackexchange.com/questions/4512/is-it-possible-to-connect-ev3-and-nxt-bricks-like-master-slave-configuration-via) that says to install nxt-python on ev3dev, but I have no idea how to do this, I have no coding expirience, I am just a simple man looking for an easy solution.

**Comment by dlech** [comment]
Make sure you EV3 is connected to the internet, then run the following commands in an SSH terminal

    sudo apt update
    sudo apt install python-nxt

**Comment by bonmotwang** [comment]
Thanks. I just had my son started on EV3 using Python. Found a great deal on a used full set of NXT. This is a great news that he can talk to NXT and expand the inputs and outputs. 
I have another question. Does EV3DEV works on NXT? I am thinking about using NXT as a co-processor to share some workload from EV3. 
Thanks.

**Comment by dlech** [comment]
No, ev3dev cannot run on NXT.

**Comment by bonmotwang** [comment]
Thanks for being son prompt!!! Are you aware of anything could be used for using Python on NXT?

**Comment by dlech** [comment]
You can't run python *on* the NXT, but you can remote control the NXT using python.

**Comment by bonmotwang** [comment]
Does “remote control” reads sensors connected to the NXT? Thanks

**Comment by dlech** [comment]
https://github.com/Eelviny/nxt-python/wiki

**Comment by bonmotwang** [comment]
Wow. Amazing. Reading sensors! Running motors! Even display message on NXT!
You guys are awesome!
