### ISSUE TITLE
Using Motors docs

### ISSUE THREAD

**Issue by ensonic** [ev3dev/ev3dev#105]
- [x] I noticed a few typos on the new motors wiki pages (is there an easier way to help)?
    https://github.com/mindboards/ev3dev/wiki/Using-Motors-Run-Forever
    s/brake_mode/stop_mode/
    s/regulaton_mode/regulation_mode/

- [ ] Also when talking to one motor/sensor, what about not repeating the whole path for each command, so instead of

        user@ev3dev:~$ cat         /sys/class/tacho-motor/tacho-motor2/stop_mode
        brake
        user@ev3dev:~$ echo hold > /sys/class/tacho-motor/tacho-motor2/stop_mode
        user@ev3dev:~$ cat         /sys/class/tacho-motor/tacho-motor2/stop_mode
        hold

    do

        user@ev3dev:~$ cd          /sys/class/tacho-motor/tacho-motor2
        user@ev3dev:~$ cat         stop_mode
        brake
        user@ev3dev:~$ echo hold > stop_mode
        user@ev3dev:~$ cat         stop_mode
        hold

    or use a variable

        user@ev3dev:~$ export dev=/sys/class/tacho-motor/tacho-motor2
        user@ev3dev:~$ cat         $dev/stop_mode

- [ ] Oh and finally this one-liner is useful to show the current status:

    ```sh
    for file in $(find . -type f | grep -v reset | sort); do printf "%+25s: %s\n" "$file" "$(cat $file)"; done
    ```

    Or have a continuously updated status in one terminal:

    ```sh
    files=$(find . -type f | grep -v reset | sort); while /bin/true; out=""; do for file in $files; do out=$(printf "%s\n%+25s: %s" "$out" "$file" "$(cat $file)"); done; clear; echo "$out"; done
    ```

- [ ] Finally can you tell how to use <code>reset</code> on
    https://github.com/mindboards/ev3dev/wiki/Using-Motors
    It seems to be just a matter of

    ```sh
    echo "1" >reset
    ```

    and that imho easier that recommending to "just unplug the motor for a few seconds and plug it in again to reset it" as recommended on
    https://github.com/mindboards/ev3dev/wiki/Using-Motors-Run-Forever

**Comment by dlech** [comment]
We just totally revamped the motor drivers, so closing this issue. See #282.
