### ISSUE TITLE
lms2012 no video driver

### ISSUE THREAD

**Issue by Vienhackar** [ev3dev/ev3dev#1050]
So I was trying to get lms2012 to run, I downloaded stretch and installed lms2012 and ran sudo lms2012
_______________________________________________________________________________________________________________
robot@ev3dev:~$ sudo lms2012
[sudo] password for robot:

** (process:925): WARNING **: Could not start graphics: No supported video driver plugins found

** (process:925): WARNING **: Falling back to memory driver

** (process:925): ERROR **: Could not load memory driver
Trace/breakpoint trap
**robot@ev3dev:~$**
_______________________________________________________________________________________________________________

**Comment by dlech** [comment]
I believe this has been fixed already. Upgrade the `lms2012-compat` package.

* make sure EV3 is connected to the internet
* in an SSH terminal, run `sudo apt update && sudo apt install lms2012-compat`

**Comment by Vienhackar** [comment]
sorry about that, forgot I posted that, new to github, I tried that and got this:
** (process:3292): WARNING **: Failed to open /dev/hidg0: No such file or directory

** (process:3292): WARNING **: Error setting property 'Discoverable' on interface org.bluez.Adapter1: GDBus.Error:org.bluez.Error.Failed: Not Powered (g-io-error-quark, 36)

Edit: I did it again and it turned on the normal ev3 firmware, which I assume means I can't use the
nxt-python? let me explain what I am doing with my robots, I am using my ev3 with gyro sensor controls as the master and nxt as the slave, I just want to be able to have the ev3 to master of the nxt, but everything I try doesn't work

**Comment by dlech** [comment]
Closing since original issue is solved. I'm also looking at packaging a python3 version of nxt-python.
