### ISSUE TITLE
run_mode=position issues with ramping

### ISSUE THREAD

**Issue by ensonic** [ev3dev/ev3dev#106]
https://github.com/mindboards/ev3dev/wiki/Using-Motors-Run-Limited
has a note to check if position mode works when regulation is off. It does \o/

```sh
cd /sys/bus/legoev3/devices/outA:motor/tacho-motor/tacho-motor0
echo "1" >reset
echo "0" >position
echo "position" >run_mode
echo "brake" >stop_mode
echo "relative" >position_mode
echo "500" >position_sp
echo "50" >duty_cycle_sp
```

now the trouble seems to be ramp_up/down_sp. If I also set ramp_up/down time, in regulation_mode=off, nothing happens and in regulation_mode=on, the motor will stutter back and forth (flipping the polarity), although the position increments monotonically.
```sh
cd /sys/bus/legoev3/devices/outA:motor/tacho-motor/tacho-motor0
echo "1" >reset
echo "0" >position
echo "position" >run_mode
echo "brake" >stop_mode
echo "on" >regulation_mode
echo "relative" >position_mode
echo "500" >position_sp
echo "100" >pulses_per_second_sp
echo "200" >ramp_up_sp 
echo "200" >ramp_down_sp
```

**Comment by dlech** [comment]
I fixed something like this in kernel v3.16.7-ckt9-ev3dev1. If there are still problems like this, please open a new issue since we have made major changes to the motor driver since this issue was opened.
