### ISSUE TITLE
How do I control the text console in ev3dev?

### ISSUE THREAD

**Issue by tcwan** [ev3dev/ev3dev#1065]
Currently when a command line application is launched, it will automatically take over the framebuffer and use it as a text console.

However, I would like to control the text console from C-based applications beyond using `printf()`. e.g., 

* Clear Screen
* Position text cursor at (col,row)
* Move text cursor
* Get keypresses from EV3 front panel buttons (prefer a generic/Linux-based approach if possible)

Optional:
* Change font size

What approaches are available? I am aware of ncurses though I've not programmed with it before. Are there easier solutions?

I'm planning on targeting both jessie and stretch ev3dev distros.

**Comment by tcwan** [comment]
Ok, I found a ncurses [example](https://cheukyin699.github.io/tutorial/c++/2015/02/01/ncurses-editor-tutorial-01.html) and managed to compile and run it on the EV3. It even works with a USB keyboard attached.

The question I have now is how do I change the font size (in ncurses terms, it should be referred to as the character set) for the framebuffer console on EV3:

Can it be changed dynamically? Or Is it only configurable as a [boot argument](https://www.kernel.org/doc/Documentation/fb/fbcon.txt)? I don't know where the boot args is configured for Debian.

**Comment by dlech** [comment]
Strange, my previous reply seems to have disappeared.

To recap...

Ncurses is pretty much __the__ library for this kind of stuff. Or if you don't wan't to use it, you can research escape codes and use them directly. I have found old Linux articles from the 1990s to be useful in this regard.

As for changing the font, you can just call `setfont` or research said 1990s literature on how to use ioctls to do the same. Fonts are found in `/usr/share/consolefonts`. However, I don't think setting the font works on ev3dev-jessie because of permission issues. It has been fixed on ev3dev-stretch though.

Example in Go lang: https://github.com/ev3dev/vscode-hello-go/blob/master/hello.go

**Comment by tcwan** [comment]
@dlech:
Thanks!

I'm leaving some URLs here for future reference:
* https://wiki.archlinux.org/index.php/Fonts#Console_fonts
* https://unix.stackexchange.com/questions/49779/can-i-change-the-font-of-terminal

**Comment by tcwan** [comment]
@dlech:

I tested this on `stretch` since you mention that it might not work on `jessie`.

A few questions: 

1. Do I need to `sudo setfont` or is `setfont` sufficient?
2. I tried changing the font from a SSH session using `setfont` and then run the binary from Brickman, but it doesn't appear to make any difference to the size of the fonts on the display?  

> I tried `Lat15-TerminusBold32x16.psf.gz` and `Lat38-VGA32x16.psf.gz` for example, and they still look the same to me.

3. Changing /etc/defaults/console-setup and rebooting does have an effect, but I can't seem to find a suitable setting other than *Huge fontsize*. How does FONTSIZE interact with FONT? Both sets of settings seem to override each other.

Here's my example configuration: 

```
CODESET="guess"
#FONTFACE="Fixed"
FONTFACE="Terminus"
FONTSIZE="6x12"

VIDEOMODE=

# The following is an example how to use a braille font
# FONT='lat9w-08.psf.gz brl-8x8.psf'

#FONT='Lat15-TomThumb4x6.psf.gz'
FONT="Lat15-Terminus12x6.psf.gz"
```

**Comment by tcwan** [comment]
From my testing, changing the font using `setfont` only works if it is executed from the binary launched via brickman, `setfont` does not affect the framebuffer console on the EV3 if I run it via a SSH remote login console.

**Comment by dlech** [comment]
> From my testing, changing the font using setfont only works if it is executed from the binary launched via brickman, setfont does not affect the framebuffer console on the EV3 if I run it via a remote login SSH console.

100% expected. `setfont` changes the font of the terminal you run it on.

**Comment by dlech** [comment]
To run programs from a remote terminal, use `brickrun`.

**Comment by tcwan** [comment]
I just tested it on `jessie`, `setfont` does work to change the console font.

Edit: One difference may be that in `jessie`, changes made by `setfont` is only valid during the process lifetime, the console will reset to the bootup font settings after the program exits, whereas in `stretch` it seems to persist.

In addition, brickrun is not installed by default on `jessie`. Not sure about `stretch`.

**Comment by dlech** [comment]
`brickrun` is new in stretch. There is a background service that goes with it that takes over one of the virtual consoles, which is why the font persists on stretch but not on jessie.
