### ISSUE TITLE
Create a site to explore and collect projects which use ev3dev??

### ISSUE THREAD

**Issue by paulsoper** [ev3dev/ev3dev#107]
I suspect that a number of us are working on projects that are using ev3dev.  I'm wondering how we could create a way of collecting those, so that we could see what each other is doing?

At a very minimum, we could put a page on the wiki which would allow comments, and then each leave a link to a site where are project is featured.

A more complete way would be to set up a site which allows multiple bloggers (I think that can be done through WordPress), and invite folks to post directly to that site - code, pictures, videos, etc.

I'd be happy to set up such a site, if there appears to be some interest.

Maybe there is a much better way which I'm just not thinking of ... for instance, I don't know if github itself allows such a system ...

**Comment by dpiquee** [comment]
Hi there
I have experimented with great pleasure the fabulous  laurens walk  balancing robot
http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/
I would like work in python and ev3dev,
I was inspired to http://www.ev3dev.org/projects/2014/05/16/Balancing-Robot/
but without success
Has anyone succeeded?
a java solution also interest me
Thanks for your attention

**Comment by dlech** [comment]
Hi, @dpiquee. This seems to be unrelated to the original issue here. Please open a new issue.
