### ISSUE TITLE
Does exist in Debian Stretch some utility to check batteryMonitor?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#1071]
Hi @dlech,

Maybe it is a old question but I am not sure if anyone has developed something in last months.

Does exist some utility to check the battery and if the level reach some threshold in that case, shutdown the brick?

Many thanks in advance

Juan Antonio

**Comment by jabrena** [comment]
I found this old issue about the topic:
https://github.com/ev3dev/ev3dev/issues/861

What is the threshold level to shutdown?
https://github.com/ev3dev/brickd

How to configure?

Juan Antonio

**Comment by dlech** [comment]
> What is the threshold level to shutdown?

See https://github.com/ev3dev/brickd/blob/ev3dev-stretch/src/power_monitor.vala#L115



> How to configure?

It is not configurable.

**Comment by jabrena** [comment]
I am going to test this week.

Thanks @dlech

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/issues/1035

**Comment by dlech** [comment]
https://github.com/ev3dev/brickd/blob/ev3dev-stretch/docs/PROTOCOL.md#properties
