### ISSUE TITLE
how do you use a mobile ssh connection

### ISSUE THREAD

**Issue by Vortetty** [ev3dev/ev3dev#1073]
### What are you trying to do?
connect on mobile

### What did you expect to happen?
it to connect over bluetooth

### What actually happened?
i could bluetooth, would not open ssh

### What hardware and software are you using (including version numbers)?
newest, mobile ssh by gao feng

**Comment by dlech** [comment]
Did you follow this tutorial (the Android one)? http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-bluetooth/
