### ISSUE TITLE
Connecting 046d:08ae Logitech QuickCam: Module zc0301 not found in ev3dev stretch

### ISSUE THREAD

**Issue by obo** [ev3dev/ev3dev#1076]
### What are you trying to do?

Get my old Logitech camera connected to my EV3.

### What did you expect to happen?

Plug the camera to the brick's USB and get /dev/video0 to use the camera through video4linux.

### What actually happened?

Having tried snapshot-ev3dev-stretch-ev3-generic-2018-04-22.img.xz, I see the camera as a USB device but the /dev/video0 is not created, apparently the correct driver module is not available in the stretch release.

The messages are:

dmegs:
[ 2498.040488] usb 1-1: new full-speed USB device number 2 using ohci-da8xx
[ 2498.310741] usb 1-1: New USB device found, idVendor=046d, idProduct=08ae
[ 2498.310804] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 2498.310840] usb 1-1: Product: Camera
[ 2499.162313] usbcore: registered new interface driver snd-usb-audio

lsusb
Bus 001 Device 002: ID 046d:08ae Logitech, Inc. QuickCam for Notebooks

hwinfo --usb
03: USB 00.1: 11200 TV Card                                     
  [Created at usb.122]
  Unique ID: dOTr.elweGVRLXdD
  Parent ID: k4bc.t+d_q03AOjF
  SysFS ID: /devices/platform/soc@1c00000/ohci-da8xx/usb1/1-1/1-1:1.1
  SysFS BusID: 1-1:1.1
  Hardware Class: tv card
  Model: "Logitech QuickCam for Notebooks"
  Hotplug: USB
  Vendor: usb 0x046d "Logitech, Inc."
  Device: usb 0x08ae "QuickCam for Notebooks"
  Revision: "1.00"
  Driver: "snd-usb-audio"
  Driver Modules: "snd_usb_audio"
  Speed: 12 Mbps
  Module Alias: "usb:v046Dp08AEd0100dc00dsc00dp00ic01isc01ip00in01"
  Driver Info #0:
    Driver Status: zc0301 is not active
    Driver Activation Cmd: "modprobe zc0301"
  Driver Info #1:
    Driver Status: snd_usb_audio is active
    Driver Activation Cmd: "modprobe snd_usb_audio"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #4 (Hub)

uname -r
4.14.34-ev3dev-1.6.1-ev3

sudo modprobe zc0301
modprobe: FATAL: Module zc0301 not found in directory /lib/modules/4.14.34-ev3dev-1.6.1-ev3

### What hardware and software are you using (including version numbers)?

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2018-04-22
Kernel version:     4.14.34-ev3dev-1.6.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=8
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016535F74D2
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
According to [this](https://github.com/ev3dev/ev3dev/issues/1030#issuecomment-383408961), the kernel module you need is in kernel version `4.14.35-ev3dev-2.0.0-ev3`, but you have `4.14.34-ev3dev-1.6.1-ev3`.

Once you get the correct kernel installed, you should not have to manually run `modprobe`.

**Comment by dlech** [comment]
It looks like that kernel didn't get uploaded for some reason... working on it.

**Comment by dlech** [comment]
OK, kernel upgrade should work now

    sudo apt update
    sudo apt upgrade

**Comment by obo** [comment]
Doesn't seem that it installed any new kernel, so not worth rebooting yet. Or am I wrong?

robot@ev3dev:~$ sudo apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Get:3 http://archive.ev3dev.org/debian stretch InRelease [8,428 B]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease        
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release          
Get:5 http://archive.ev3dev.org/debian stretch/main armel Packages [61.6 kB]   
Fetched 70.1 kB in 25s (2,791 B/s)                                             
Reading package lists... Done
robot@ev3dev:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-image-ev3dev-ev3
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by dlech** [comment]
You didn't use the commands that I suggested. If you want to use `apt-get` instead of `apt` then you need to run `sudo apt-get dist-upgrade`. The "kept back" package is the one that upgrades the kernel.

**Comment by obo** [comment]
Oops, sorry, too much automation in my fingers.

It works!!! Fabulous!!

After rebooting with the new kernel, /dev/video0 was there and worked just great. My first robot-selfie attached.
![image](https://user-images.githubusercontent.com/192828/39216777-514e7604-481d-11e8-8d4b-8e505b933251.jpeg)

(Now just the bluetooth, opencv, pocketsphinx and a big portion of operator's patience ;-)
