### ISSUE TITLE
Upgrading from Jessie to Stretch

### ISSUE THREAD

**Issue by Uldiniad** [ev3dev/ev3dev#1080]
How should I proceed with the upgrade (if it is even possible without re-flashing once the stretch stable images are made available on the ev3dev website)?
Can I follow tutorials available elsewhere as if I was upgrading my PC (I'm guessing not since it ev3dev is specialized)?

**Comment by dlech** [comment]
Just grab one of the ev3dev-stretch SD card images and re-flash your microSD card.
