### ISSUE TITLE
PiStorms - Error Displaying

### ISSUE THREAD

**Issue by KWSmit** [ev3dev/ev3dev#1086]
### What are you trying to do?
I tried to use the development snapshots of 2018-04-14 and 2018-04-22 on my PiStorms v2.

### What did you expect to happen?
Normal operation of ev3dev.

### What actually happened?
After booting the display is a mess: Brickman is not showed correctly, see attached image. I believe it's also rotaded 90 degrees counterclockwise.
Development snapshot of 2017-12-13 works fine. I believe the display driver has changed since then, could it be this is the source of this problem? Or do I have to set a proper value to dtparam=rotate=270 in config.txt (e.g 90)?

### What hardware and software are you using (including version numbers)?

Development snapshots of 2018-04-14 and 2018-04-22.
PiStorms v2 on RPi 3B.

![img_2926](https://user-images.githubusercontent.com/19389629/39565632-ffc558f0-4eb8-11e8-9e27-c273443dce2f.JPG)

**Comment by dlech** [comment]
Fix is released in kernel `4.14.39-ev3dev-2.0.1-rpi2`.
