### ISSUE TITLE
kernel info for ev3 not updated?

### ISSUE THREAD

**Issue by jingan0904** [ev3dev/ev3dev#1088]
Picture on site
<img width="408" alt="screen shot 2018-05-04 at 8 26 13 pm" src="https://user-images.githubusercontent.com/24708918/39627775-8a499bb4-4fd9-11e8-9bf2-4c9c1c172363.png">
My kernel is 4.4.87-22-ev3dev-ev3

**Comment by dlech** [comment]
Thanks for noticing. We don't update screenshots every time we do a kernel release. That would be too much work. :wink:.
