### ISSUE TITLE
www.ev3dev.org

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#109]
I have figured out how point http://www.ev3dev.org to our github pages site. ev3dev.org redirects to www.ev3dev.org and our packages and irclogs are still in their original places.

Also, I deleted to `gh-pages` branch here. The correct repository to submit pull requests to is http://github.com/ev3dev/ev3dev.github.io

Have a look and send us some pull requests.

**Comment by rhempel** [comment]
Doh! I was in a rush - it's public now...

**Comment by WasabiFan** [comment]
It looks good! And it has the perfect shape to work as a favicon.

**Comment by BertLindeman** [comment]
@rhempel 
> It's sloped because the camera view (in Blender) is below and slightly off center - If you like this, you will like the animation :-)

Well, :smile:  you are right: I like it.

**Comment by fringd** [comment]
Here's the text for my last version, btw. I moved the period up to the second line to match the other version.

```
            _____
  _____   _|___ /
 / _ \ \ / / |_ \
|  __/\ ` / ___) |
 \___) \_/ |____/
  _| | _____   __
 /   |/ _ \ \ / /
| (| |  __/\ ` /
 \__,|\___| \_/ o
  __   _ ___ ____
 /  \ | '__// _ (
| () || |   ) __/
 \__/ |_|   ) _ \
            \___/
```

**Comment by fringd** [comment]
![square logo](https://cloud.githubusercontent.com/assets/272709/5631450/ad61a900-9594-11e4-9961-1b8185c4dd76.png)
