### ISSUE TITLE
Fswebcam newbie issues

### ISSUE THREAD

**Issue by jingan0904** [ev3dev/ev3dev#1090]
### What are you trying to do?
fswebcam test.jpg

### What did you expect to happen?
no error and picture taken

### What actually happened?
--- Opening /dev/video0...
stat: No such file or directory

### What hardware and software are you using (including version numbers)?

Image file:         ev3dev-jessie-ev3-generic-2017-09-14
Kernel version:     4.4.87-22-ev3dev-ev3
Board:              LEGO MINDSTORMS EV3 Programmable Brick
Revision:           0006
Brickman:           0.8.1
ev3devKit:          0.4.3

**Comment by jingan0904** [comment]
The webcam can be found through `lsusb`
Output: 
Bus 001 Device 002: ID 046d:08a0 Logitech, Inc. QuickCam IM
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

**Comment by dwalton76** [comment]
Try ‘sudo fswebcam’

**Comment by jingan0904** [comment]
Thanks but it doesn't work

**Comment by dlech** [comment]
Duplicate of #1030.
