### ISSUE TITLE
Ev3- stretch no bluetooth?

### ISSUE THREAD

**Issue by jingan0904** [ev3dev/ev3dev#1091]
### What are you trying to do?
Access Bluetooth on ev3dev-stretch

### What did you expect to happen?
Options to enable Bluetooth

### What actually happened?
Bluetooth says not available

### What hardware and software are you using (including version numbers)?

Kernel: 4.14.34-ev3dev-1.6.1-ev3
Revision:0000

**Comment by dlech** [comment]
Fixed in kernel `4.14.38-ev3dev-2.0.1-ev3`. Please upgrade you packages or use the most recent snapshot image.

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3-kernel/commit/44c8496628f526e80a8439551fc1577e711f09b8
