### ISSUE TITLE
Open Roberta Lab Hangs

### ISSUE THREAD

**Issue by jingan0904** [ev3dev/ev3dev#1096]
### What are you trying to do?
Open Roberta Lab display values

### What did you expect to happen?
Able to quit program normally

### What actually happened?
Ev3 is stuck in the program and can't quit, if program ends, blank screen

### What hardware and software are you using (including version numbers)?

```
Image file:         ev3dev-stretch-ev3-generic-2018-04-22
Kernel version:     4.14.38-ev3dev-2.0.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016533DD4F5
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
cc: @ensonic

**Comment by dlech** [comment]
I would suggest opening an issue at https://github.com/OpenRoberta/robertalab-ev3dev

**Comment by jingan0904** [comment]
Ok @dlech

**Comment by dlech** [comment]
https://github.com/OpenRoberta/robertalab-ev3dev/issues/64
