### ISSUE TITLE
dGPS

### ISSUE THREAD

**Issue by EmilSchaetzle** [ev3dev/ev3dev#1100]
### What are you trying to do?

I want to use my dexter industries GPS Sensor with ev3dev

### What did you expect to happen?
A driver to be there
### What actually happened?

There was no driver

### What hardware and software are you using (including version numbers)?

ev3dev
dGPS sensor https://www.dexterindustries.com/manual/dgps-2/

### Own text:

If you tell me how i can write the driver on my own i would be happy to. If you want i could give them to you too.

**Comment by dlech** [comment]
See #465
