### ISSUE TITLE
ev3dev password change

### ISSUE THREAD

**Issue by Vortetty** [ev3dev/ev3dev#1104]
i would like to change the password of my ev3dev brick.

how can i accomplish this?

**Comment by dlech** [comment]
Open an SSH terminal to the EV3 then run the command `passwd`.

**Comment by Vortetty** [comment]
ok thank you

**Comment by Vortetty** [comment]
how could i make a new user

**Comment by dlech** [comment]
With the `adduser` command. But I don't recommend it unless you really know what you are doing. The Brickman user interface, for example, will only show files for the `robot` user account.

**Comment by Vortetty** [comment]
how could i make it show just my new user

or is there a way to change the name of a user

**Comment by Vortetty** [comment]
also, it is not clear how to make scripts that are separate files, how do i do that
