### ISSUE TITLE
Drawing text and rectangle on screen, wrong driver is being used.

### ISSUE THREAD

**Issue by KWSmit** [ev3dev/ev3dev#1111]
### What are you trying to do?
Displaying text and drawing rectangles on the screen of my PiStorms v2 by using `draw.text` and 'draw.rectangle`. Purpose is to write a graphical userinterface for my application (including touch interface).

### What did you expect to happen?
That it works.

### What actually happened?
In fact it seems to work, but often I get the following error-message:
`fb_ili9341 spi0.0: fbtft_update_display: start_line=239 is larger than end_line=0. Shouldn't happen, will do full display update.`

It seems it's using driver `fb_ili9341` which it's supposed not to use anymore.

### What hardware and software are you using (including version numbers)?
```
Image file:         ev3dev-stretch-rpi2-generic-2017-12-13
Kernel version:     4.14.39-ev3dev-2.0.1-rpi2
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=A02082
BOARD_INFO_MODEL=Raspberry Pi 3 Model B Rev 1.2
BOARD_INFO_SERIAL_NUM=00000000bc6aa21f
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_FW_VER=V2.08
BOARD_INFO_MODEL=PiStorms
BOARD_INFO_TYPE=aux
```

**Comment by dlech** [comment]
I think I just realized what is going on here. `flash-kernel` doesn't have support for device tree overlays. You should be able to work around by copying the new overlay.

    sudo cp /usr/lib/linux-image-$(uname -r)/overlays/pistorms.dtbo /boot/flash/overlays/

Also, if you install the latest SD card snapshot image, it will have the correct file in the correct place.

**Comment by KWSmit** [comment]
Tested it with the latest shapshot image, works fine now 👍
