### ISSUE TITLE
Debian Stretch // New Display driver // Question

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#1114]
Hi @dlech,

Does the new display driver 4 colors (or brightness levels)?

Juan Antonio

**Comment by dlech** [comment]
The driver reports itself as XRGB (32-bits per pixel). However, this is converted to 8-bit per pixel grayscale using ITU BT.601 and then downsampled to 2-bits per pixel in the driver.

See https://github.com/ev3go/ev3/pull/3

**Comment by jabrena** [comment]
Oki, 

Next week, I will try to review the technical details to begin with the change.

Thanks David

**Comment by JakubVanek** [comment]
This issue can be closed, as we implemented the display support [<sub>RGB specific bits</sub>](https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/src/main/java/ev3dev/hardware/display/RGBFramebuffer.java) and I remember seeing multiple shades of grey.
