### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by mardukeyo** [ev3dev/ev3dev#1128]
Is there an IDE for ev3dev? Text editor, visual code navigator, compile, link, target download, debugger..etc

**Comment by WasabiFan** [comment]
There isn't one for ev3dev-jessie (the ev3dev version which is currently used by most people) but there is one for the upcoming version, ev3dev-stretch. If you'd like to work with that version, which doesn't have quite as complete support and documentation yet, you can check out the VSCode extension here: https://github.com/ev3dev/vscode-ev3dev-browser

**Comment by mardukeyo** [comment]
Thank you!
