### ISSUE TITLE
Incorrect analog values in kernel ev3dev-2.2.0

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#1131]
### What are you trying to do?

Make a public service announcement.

### What did you expect to happen?

Someone else to report this bug before me. :laughing: 

### What actually happened?

In kernel release `ev3dev-2.2.0`, the analog values on LEGO MINDSTORMS EV3 (and probably also FatcatLab EVB) are off by as much as 0.1V.

This was an unintended side effect of some performance improvement changes.

### What hardware and software are you using (including version numbers)?

Mentioned above.

**Comment by dlech** [comment]
Here is a patch I don't intend to use, but putting it here just in case I change my mind in the future.

[0001-hack-read-TI-ADS79xx-analog-values-multiple-times-to.zip](https://github.com/ev3dev/ev3dev/files/2203689/0001-hack-read-TI-ADS79xx-analog-values-multiple-times-to.zip)

**Comment by dlech** [comment]
Should be fixed by https://github.com/ev3dev/ev3-kernel/commit/74e60bba98503776dae51162097e33e49b3474cb

**Comment by tcwan** [comment]
I was wondering why the battery voltage readings differ from those read on jessie 😅

**Comment by dlech** [comment]
Actually, this should not affect the battery voltage, so if there is a problem there, please open a new issue.

**Comment by dlech** [comment]
Fixed released in `ev3dev-2.2.1` kernel.
