### ISSUE TITLE
root password maker does not work

### ISSUE THREAD

**Issue by BothellRobotics** [ev3dev/ev3dev#1141]
### What are you trying to do?
I am trying to SSH EV3 after booting with EV3DEV.  Once I enter ssh root@<IP address of EV3 brick>, I have been prompted password. When I enter "maker", I get  permission denied.

**Comment by BertLindeman** [comment]
Think you are missing the letter b in the userid. `maker` is the password set for user `robot`
See [ev3dev doc connecting-to-ev3dev-with-ssh](https://www.ev3dev.org/docs/tutorials/connecting-to-ev3dev-with-ssh/)

**Comment by BothellRobotics** [comment]
Thank you. You saved my day. For user name robot the password works.
