### ISSUE TITLE
FLL (for a small number of participating regions only in 2018/2019)

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#1142]
### What are you trying to do?

Let people know that ev3dev can be used for FIRST LEGO League **IN REGIONS PARTICIPATING IN THE PILOT PROGRAM ONLY**

This is an experimental pilot program and does not mean that FLL has made any commitment to further expansion of the program.

Update: here is a list of participating regions:

Adventist Robotics League, New Mexico, Uruguay, Alabama, Ohio, Washington, California, Southern Oklahoma, Wisconsin, Chile, Oregon, Illinois, Romania, Israel, South Dakota, Japan, Taiwan										

### What did you expect to happen?

Some people will be very excited to hear this.

### What actually happened?

It is yet to be seen...

**Comment by dlech** [comment]
So, FLL season is already in full swing (at least here in the USA). The challenge was released on 1 August. It will be interesting to see how many teams actually use ev3dev. Also it opens up the question: what is needed to make ev3dev "FLL ready"?

**Comment by moriarty** [comment]
That sounds cool!
Can you provide a link to the rules?

http://www.firstlegoleague.org/challenge

* Throughout the season, teams need access to the following materials:
    * LEGO® MINDSTORMS Robot Set
    * Computer or tablet with software to program the robot. (Laptop is recommended.)

> with software to program the robot

So that doesn’t specifically say Lego Mindstorms Software like in former rules so ev3dev is allowed?

**Comment by dlech** [comment]
This year, using other programming languages is being done on a per-region opt-in basis, so the general rules are the same as in past years. FLL coordinators in regions that have opted in will receive special rules. For example Ohio FLL posted [this on facebook](https://www.facebook.com/ohfll/photos/a.1413669698846922.1073741832.1385524211661471/2125504434330108/?type=3&theater).

![image](https://scontent-dfw5-1.xx.fbcdn.net/v/t1.0-9/38392279_2125504440996774_2934430065896718336_n.jpg?_nc_cat=0&oh=a9e4a9ae2c20a644ae31d3c9a0158635&oe=5BCE0086)

**Comment by WasabiFan** [comment]
Woah! I didn't know they were opening up the software restrictions. That's quite exciting!

**Comment by jabrena** [comment]
Very good news!!!

**Comment by sanjayseshan** [comment]
Yes. @arvindseshan and I are very exited for the opportunities this brings to teams. We are working with @dlech to create a chart comparing different programming languages to help teams make intelligent choices. Let's see how many teams pick ev3dev!

**Comment by dwalton76** [comment]
That is very cool :)

**Comment by sanjayseshan** [comment]
To make it easier for teams to install/setup ev3dev, we wrote a new lesson on ev3lessons.com: <a href="http://ev3lessons.com/en/ProgrammingLessons/beyond-ev3g/EV3Dev-intro.pdf">Lesson PDF</a>.

Thank you to @dlech for the feedback he gave on the lesson.
