### ISSUE TITLE
Minimum Polling Time for EV3 Color Sensors

### ISSUE THREAD

**Issue by tcwan** [ev3dev/ev3dev#1146]
### What are you trying to do?

Determine the minimum polling time that can be used for the EV3 Color Sensor (and other sensors)

### What did you expect to happen?

Understand the limits of the stock kernel configuration in terms of minimum polling time vs. hardware capabilities of the sensor.

### What actually happened?

Some [historical posts](https://github.com/ev3dev/ev3dev/issues/443#issuecomment-161624762) mentioned 10 ms as the minimum polling time, but that seemed like it is a kernel configuration issue rather than a hardware limitation.

### What hardware and software are you using (including version numbers)?

EV3 with stock ev3-jessie, ev3-stretch releases.

### More details

I'm in the process of developing a control loop for a line following robot in C which would require sampling the EV3 Color Sensor  input continuously. I have a 100 ms control loop which would collect multiple sequential light intensity samples, determine the range of values, and then execute the line following algorithm.

Previously I had this configuration working on the NXT using the NXT Light Sensor, where I would collect multiple samples from the sensor every 3 ms (minimum sampling time for the A/D input on the NXT) until I have enough samples. The program was running bare-metal on the NXT.

I understand that the default polling rate on ev3dev is 10 ms, and it is controlled via the poll_ms parameter for the sensor (**EDIT: I can't change `poll_ms` for the LEGO sensors in jessie, haven't tried in stretch**). However, when using the default sampling rate, the sensor readings will take up to 50 ms (for 5 samples), which leaves only 50 ms for the rest of the control logic. Consequently I have to reevaluate the way I'm implementing the control loop.

My questions:
1. Can the poll_ms value be reduced below 10 ms on the stock kernel? (Some [previous posts](https://github.com/ev3dev/ev3dev/issues/324#issuecomment-106872602) suggests that I need to redefine `HZ` and recompile the kernel)
2. What is the  maximum hardware polling rate? I'm looking at the EV3 Color Sensor currently, but would be good to get an idea of what is allowed for the other sensors.
Is it dependent on the interface type (e.g., UART, I2C, Analog)?
3. Is the [kernel loading issue](https://github.com/ev3dev/ev3dev/issues/324#issuecomment-100976535) with short polling intervals (< 10 ms) still significant in stretch, i.e., 10 ms was a good compromise to keep the system load within reasonable bounds?

**Comment by dlech** [comment]
When it comes to polling, there are basically 3 types of sensors, UART, I2C and analog. All of the EV3 sensors except the touch sensor are UART. These sensors send data to the EV3 whenever the value changes. So these sensors are not polled at all, therefore you cannot change the rate. I2C sensors are the NXT "digital" sensors and have the polling rate changed on an individual basis. Analog sensors receive data from the analog digital converter. The polling rate for this can be changed in ev3dev-stretch (see wiki). The default polling rate for all sensors (except UART, of course) is 100ms (not 10ms).

However, all of this should not make a difference for the timing of your program. All of the polling happens asynchronously in the kernel. When you read the `value0` attribute, it just reads the most recent value, whatever that happens to be.

If your "read" is taking 50ms, then you are probably also setting the sensor mode each time you "read". Don't do that, and you will get a much faster read time.

**Comment by tcwan** [comment]
@dlech:

Thanks for the explanation. I am the one setting the polling interval in my program by using timers to check every 10 ms based on the information I found previously. I guess that is not the correct approach.

Edit: [Relevant Wiki page](https://github.com/ev3dev/ev3dev/wiki/Internals:-ev3dev-stretch)

**Comment by dlech** [comment]
Maybe the analog polling is every 10ms (it probably is if that is what I wrote on the wiki). I would have to check the kernel code to be sure. But, that only applies to analog sensors, not UART or I2C.
