### ISSUE TITLE
Hitechnic color sensor v2

### ISSUE THREAD

**Issue by lvjonok** [ev3dev/ev3dev#1158]
Hello everyone. I tried to connect hitechnic color sensor v2 to my ev3 block, but i have an error that this device is not connected, i was searching for any examples of using this sensor and found nothing. I know that I need to use not ColorSensor class, but Sensor class. Can anyone help me with connecting this sensor and getting values from him?

cl = Sensor(address='in3:12c1')
print(cl.value())

  File "./new_moving.py", line 735, in <module>
    print(cl.value())
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1763, in value
    self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 219, in get_attr_int
    attribute, value = self._get_attribute(attribute, name)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 202, in _get_attribute
    raise Exception("%s is not connected" % self)
Exception: Sensor(in3:12c1) is not connected

**Comment by dlech** [comment]
Please answer all of the issue template questions:

```
### What are you trying to do?


### What did you expect to happen?


### What actually happened?


### What hardware and software are you using (including version numbers)?

<!-- Tip: copy and paste the output of `ev3dev-sysinfo -m` here -->

```

The answer depends on which version of ev3dev you are using.

P.S. the the sensor address looks wrong. You can find the correct address using the Device Browser on the EV3.

**Comment by lvjonok** [comment]
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2018-08-06
Kernel version:     4.14.61-ev3dev-2.2.2-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016535159F2
BOARD_INFO_TYPE=main
```

**Comment by lvjonok** [comment]
I saw address of this sensor in Device Browser and it is i2c-legoev33:i2c1

**Comment by lvjonok** [comment]
I changed address, so it works now, thank you!
