### ISSUE TITLE
wifi stops working after a little while (power shortage?)

### ISSUE THREAD

**Issue by schoolsplay** [ev3dev/ev3dev#116]
I just noticed that the wifi connection dies after only a short while running on batteries.
The voltage is a wild guess of course but when my batteries are full I have 8000000 as my voltage_now reading and when it drops below 7700000 the wifi stops working. (around 50000000 my brick will shutdown)
When I recharge my batteries wifi is working again.
Again values are just an indication.
USB connection is working correctly and I can run the motors for a long time after wifi stops working so I have power enough left (I guess)

Is this a known wifi issue or has it something todo with my wifi dongle, an edimax rtl8192cu ?
I only have an unsupported dongle so I can't swap them.

**Comment by dlech** [comment]
Is this still a problem with the v3.16.7 kernel?

**Comment by antonvh** [comment]
I used this solution before:
http://raspberrypi.stackexchange.com/questions/1384/how-do-i-disable-suspend-mode

**Comment by dlech** [comment]
Closing since this was reported against an older kernel. Please open a new issue if there are still similar problems.
