### ISSUE TITLE
Pressing the BACK button immediately terminates the program (brickman, ev3dev-stretch, Lego EV3)

### ISSUE THREAD

**Issue by xdsl** [ev3dev/ev3dev#1162]
### What are you trying to do?
I press BACK during program execution

### What did you expect to happen?
the program is terminated in 2-3 seconds

### What actually happened?
the program is terminated immediately

### What hardware and software are you using (including version numbers)?
Image file:         ev3dev-stretch-ev3-generic-2018-08-06
Kernel version:     4.14.61-ev3dev-2.2.2-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534C8680
BOARD_INFO_TYPE=main

**Comment by dlech** [comment]
This is working as designed.

**Comment by xdsl** [comment]
Very bad. Now I can not work with the BACK button in my programs.

**Comment by jabrena** [comment]
You could use that event but not in combination with Brickman.
In my case, I launch the programs by the terminal.

**Comment by xdsl** [comment]
I can not use the terminal on the WRO.

**Comment by jabrena** [comment]
You have more buttons...
The robots run in an autonomous way...

**Comment by xdsl** [comment]
Is it possible to add an option to the config file /etc/brickrun.conf?
For example:
[stop-button]
...
key_code=14
wait_time=3
...

**Comment by dlech** [comment]
That sounds reasonable.

**Comment by dlech** [comment]
Fix is released in `brickrun_1.1.0`.

The option is named `delay`.

**Comment by jabrena** [comment]
Hi @dlech who to set the parameter delay by command line?

**Comment by dlech** [comment]
This is not possible.
