### ISSUE TITLE
Gets error: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by Lakselord** [ev3dev/ev3dev#1165]
### What are you trying to do?
I am trying to run a shell script, but keeps getting this error when running it from the brick. I have tried to sudo visudo to add robot ALL = NOPASSWD : ALL at the end of the file
but i can't access the file when using robot:maker and i haven't been able to find the password for root. 

### What hardware and software are you using (including version numbers)?
brickman v0.08
kernel: 4.4.24-16-ev3dev-ev3
revision 0006

**Comment by dlech** [comment]
> What actually happened?

when you ran `sudo visudo`?

**Comment by Lakselord** [comment]
Found out that i was able to save the changes i made to  the file even though the standard message about that you must edit the file as root was displayed, so the issue is solved
