### ISSUE TITLE
Accidentally screwed up the sudoers file, any way to add myself back?

### ISSUE THREAD

**Issue by wlnirvana** [ev3dev/ev3dev#1167]
### What are you trying to do?

Grant password free root access.

### What actually happened?

I was `visudo`ing but left out a `%` sign, which now completely blocks root access for the `robot` user, like following. Is there any possibility to fix this without reimaging the sd card?

```
robot@ev3dev:~$ sudo ls
robot is not in the sudoers file.  This incident will be reported.
```

### What hardware and software are you using (including version numbers)?

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-jessie-ev3-generic-2017-09-14
Kernel version:     4.4.87-22-ev3dev-ev3
Board:              LEGO MINDSTORMS EV3 Programmable Brick
Revision:           0006
Brickman:           0.8.1
ev3devKit:          0.4.3
```

**Comment by dlech** [comment]
You can mount the SD card on another Linux system and try to fix it.

**Comment by wlnirvana** [comment]
Brilliant idea!
