### ISSUE TITLE
send a variable from a Python running on computer to program running on ev3

### ISSUE THREAD

**Issue by MirMSadeghi** [ev3dev/ev3dev#1168]
### What I'm trying to do?
I am trying to connect to an ev3 device running ev3dev Jessie software. I have some Python code that I would like to run on my computer, the code outputs a variable that I would like to pass it to my ev3 brick. On my ev3 brick, I have another program that performs a certain action based on the variable.

### What do I want to do?
I wanted to connect to my brick via ssh so I can run my program on ev3 and also run my other program on my laptop and connect these two with `MQTT`. Is that possible!

Is there any other way I can send a message from my python program that is running on my computer to the program that is running on my ev3dev. The programming language that I want to use to program the ev3 brick doesn't matter even legos graphical programming interface is enough as long as I can receive messages from my computer

### What actually happened?
I connected my brick via a USB cable to my laptop and I connected my brick so the status said connected. I then typed the command in terminal: `ssh robot@ev3dev.local` and the command `ssh robot@10.42.0.3`. The second one connected but gave an error `Permission Denied` when I typed the password `maker` into the terminal.

### Hardware and software versions?
- I'm running Ubuntu 18.04 on my computer
- brickman 0.8.1
- kernel: 4.4.87-22-ev3dev-ev3
- Jessie 2017-09-14

**Comment by dlech** [comment]
ev3dev-stretch comes with python MQTT pre-installed.

**Comment by MirMSadeghi** [comment]
Oh, I see. Thanks for that!
