### ISSUE TITLE
How to disable blink LEDs in brickrun?

### ISSUE THREAD

**Issue by xdsl** [ev3dev/ev3dev#1180]
My programs themselves use LEDs, and brickrun interferes with this process.
How to disable blink LEDs in brickrun? 
Maybe add a configuration parameter to /etc/brickrun.conf?

**Comment by dlech** [comment]
It shouldn't interfere. It only changes the LEDs before starting your program by setting the "trigger" to "heartbeat". Perhaps you need to change the LED trigger in your program?

**Comment by xdsl** [comment]
Thanks. At the beginning of the program I set the triggers to "none". Now everything works.
