### ISSUE TITLE
brickman control via web server

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev#1195]
### What are you trying to do?

I am trying to develop a web interface for navigating brickman.  I have written a small web server in python that:
- Uses https://github.com/AndrewFromMelbourne/fb2png to create a png of ``/dev/fb0``
- index.html is a web page that displays that png
- index.html also has some javascript that listens for up, down, left, etc keystrokes on the client keyboard and if it hears one it uses ajax to inform the web server about the keystroke
- when the web server hears about a keystroke from the client (via ajax) I want it to simulate that keystroke in order to navigate brickman

The last bullet is the gotcha.  I have tried pyautogui, pynput (these both barf due to no DISPLAY),  evdev and conspy but I have not found anything yet that actually allows me to navigate brickman remotely.  Of these evdev seems the most straightforward, I am doing

```
            with uinput.UInput() as ui:
                if key == "UP":
                    ui.write(e.EV_KEY, e.KEY_UP, 1)
                elif key == "DOWN":
                    ui.write(e.EV_KEY, e.KEY_DOWN, 1)
                elif key == "LEFT":
                    ui.write(e.EV_KEY, e.KEY_LEFT, 1)
                elif key == "RIGHT":
                    ui.write(e.EV_KEY, e.KEY_RIGHT, 1)
                elif key == "ENTER":
                    ui.write(e.EV_KEY, e.KEY_ENTER, 1)
                elif key == "ESC":
                    ui.write(e.EV_KEY, e.KEY_ESC, 1)
                else:
                    raise Exception("Invalid key {}".format(key))

                ui.syn()
```

brickman does not update though.  Ideas on how I can remotely navigate brickman?

### What hardware and software are you using (including version numbers)?

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-rpi2-generic-2017-12-13
Kernel version:     4.14.71-ev3dev-2.3.0-rpi2
Brickman:           0.10.0
BogoMIPS:           38.40
Board:              board0
BOARD_INFO_HW_REV=A22082
BOARD_INFO_MODEL=Raspberry Pi 3 Model B Rev 1.2
BOARD_INFO_SERIAL_NUM=000000002f94f0a9
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_FW_VER=1.4.3
BOARD_INFO_HW_REV=3.2.1
BOARD_INFO_MODEL=Dexter Industries BrickPi3
BOARD_INFO_SERIAL_NUM=E1DA1CC95150324336202020FF19312F
BOARD_INFO_TYPE=aux
```

**Comment by dlech** [comment]
You are simulating the key press: `ui.write(e.EV_KEY, e.KEY_UP, 1)`, but never the release `ui.write(e.EV_KEY, e.KEY_UP, 0)`. Other than that, it looks like it should work.

Also see: https://github.com/G33kDude/ev3dev-web-remote/blob/master/keyboard.py

also, the back button is mapped to backspace, not escape (although escape might work too, I don't remember).

>  to create a png of `/dev/fb0`

FYI, ev3dev ships with fbcat/fbgrab for this sort of thing.

**Comment by dwalton76** [comment]
Ack on fbgrab and the ev3dev-web-remote project....I gave it a try but it has the same issue where the keystrokes are not doing anything.  Something must have changed in stretch.

**Comment by dlech** [comment]
it works for me

**Comment by dwalton76** [comment]
ok ev3dev-web-remote is working for me on ev3 but not on a pi3. I suspect it has something to do with this delta:

EV3
```
robot@ev3dev:~$ ls -lh /dev/uinput
crw-rw---- 1 root input 10, 223 Nov 17 08:54 /dev/uinput
robot@ev3dev:~$ 
```

pi3
```
robot@pi3[ev3dev-web-remote]# ls -lh /dev/uinput
crw------- 1 root root 10, 223 Nov 17 13:58 /dev/uinput
robot@pi3[ev3dev-web-remote]# 
```

but even after change the pi3 ``/dev/uinput`` perms to 660 and changing the group to ``input`` it still doesn't work.

**Comment by dwalton76** [comment]
This ev3dev-web-remote is pretty cool :)  I forked it and have touch support working and the screen refreshing after a button press...you can drive the brickman menu from your smartphone.  Still don't have it working on pi3 though.

Would you be willing to ship this as part of ev3dev?  Having a web interface up and running by default could be a nice little feature.

**Comment by jabrena** [comment]
Hi @dwalton76, for brickpi although it doesnt have any display, is possible to show the content of framegrabber?

**Comment by dlech** [comment]
> but even after change the pi3 `/dev/uinput` perms to 660 and changing the group to `input` it still doesn't work.

Works for me

> Would you be willing to ship this as part of ev3dev?

If it gets packaged into a debian package


> Having a web interface up and running by default could be a nice little feature.

Except for the fact it uses lots of memory, so nack on enabling it by default.

**Comment by dwalton76** [comment]
@dlech if I connect a keyboard to a pi3 then it works.  If I disconnect the keyboard it still works but if I then reboot it no longer works.

Do you have a keyboard connected?

**Comment by dlech** [comment]
> Do you have a keyboard connected?

probably.

**Comment by dlech** [comment]
> If I disconnect the keyboard it still works but if I then reboot it no longer works.

This makes me think there is some kernel module that you could load manually to make it work (`sudo modeprobe ...`). Run `lsmod` before you attach a keyboard and after to see what modules are loaded.

**Comment by dwalton76** [comment]
Ah, that was indeed the issue....`evdev` is loaded when the keyboard is plugged in.  Doing a modprobe of it without a keyboard allows the webserver to work :)

One weird thing is the webserver locks up after 7 or 8 keystrokes and it does not do that on the EV3 so I need to dig into that.

**Comment by dwalton76** [comment]
I suspect the locking up issue is something python related....closing this issue.  Thanks for the help!!
