### ISSUE TITLE
Non-Mindstorms output devices

### ISSUE THREAD

**Issue by JorgePe** [ev3dev/ev3dev#121]
Hi!

I'm using a Logitech C170 webcam with ev3dev. Image isn' great unless environment room has plenty of light. So I'm trying to use LEGO Power Functions Lights with ev3dev so I can turn LEDs on, take a shot with fswebcam then turn LEDs off again.

I attached a 8528 NXT->RCX conversion cable (http://www.philohome.com/nxtcables/conv8528.jpg) to OutC with a Power Functions extension cable to convert RCX to Power Functions. Since there is no I2C here, ev3dev isn't aware that there is something connected to OutC. Can I tell EV3 that I have an unregulated motor? Or is it possible to drive pwm directly (tried to find something near "/sys/class/pwm/pwmchip0/device/driver/ecap.1/" but found nothing usefull).

**Comment by erichuang2013** [comment]
In my lastest version, "options legoev3 ports disable_out_port=1" in /etc/modprobe.d/ev3dev-ports.conf looks not working. Any help will be appreciated. 

my kernel.
Linux ev3dev 3.16.7-ckt9-ev3dev1 #1 PREEMPT Wed Apr 15 17:37:44 CDT 2015 armv5tejl GNU/Linux

**Comment by dlech** [comment]
You are missing the underscore (`_`) in

    options legoev3_ports disable_out_port=1

You need to reboot for this to take effect.

**Comment by erichuang2013** [comment]
dlech, thanks. now I have port A disabled. 
But I can not get pwm signal strangler after pwm export, duty_cycle, period, enable settings.  As you mentioned some gpio pin need to be enabled in order to get pwm output, can you specify which gpio to enable pwm, for expample, port A. Any hint or link will be very helpful.

**Comment by dlech** [comment]
You are in luck. I just put this up yesterday: <http://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-processor/#pin-assignments>.

GPIO X-Y on the chart translates to gpioZ in `/sys/class/gpio` where Z = X * 16 + Y. So, for example, if you want output port A, pin 1, that is GPIO 3-15. So, to make the gpio availible in sysfs, run `echo $(( 3 * 16 + 15 )) > /sys/class/gpio/export`, then you will have `/sys/class/gpio/gpio63` available to control the physical GPIO.

Also, LEGO has recently officially released the [EV3 Hardware Developer Kit](http://cache.lego.com/r/www/r/mindstorms/-/media/franchises/mindstorms%202014/downloads/firmware%20and%20software/advanced/lego%20mindstorms%20ev3%20hardware%20developer%20kit.zip), which includes the electrical schematic for the EV3. This will show you why the PWM does not work without also manipulating the GPIOs.

**Comment by erichuang2013** [comment]
dltech, I did google your pin-assignments page yesterday. It's nice for you to explain how to make a gpio pin enabled. Now I can take next move to control a RC ESC.

**Comment by erichuang2013** [comment]
Here is my script to enable port A & B pwm signals. for reference if someone needed:
echo 63 > /sys/class/gpio/export
echo 64 > /sys/class/gpio/export
echo 3 > /sys/class/gpio/export
echo 33 > /sys/class/gpio/export

echo out > /sys/class/gpio/gpio63/direction
echo in > /sys/class/gpio/gpio64/direction
echo out > /sys/class/gpio/gpio3/direction
echo in > /sys/class/gpio/gpio33/direction

echo 0 > /sys/class/pwm/pwmchip9/export 
echo 1 > /sys/class/pwm/pwmchip9/export 

echo 20000000 > /sys/class/pwm/pwmchip9/pwm1/period
echo 2000000 > /sys/class/pwm/pwmchip9/pwm1/duty_cycle
echo 1 > /sys/class/pwm/pwmchip9/pwm1/enable
echo 20000000 > /sys/class/pwm/pwmchip9/pwm0/period
echo 2000000 > /sys/class/pwm/pwmchip9/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip9/pwm0/enable

cat /sys/kernel/debug/gpio
cat /sys/kernel/debug/pwm

**Comment by erichuang2013** [comment]
I have problem to enable correct gpio to enable all output ports for motors via PWM. Those informations in  http://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-processor/#pin-assignments. is not matched as the lms2012 code: https://github.com/mindboards/ev3sources/blob/master/lms2012/d_pwm/Linuxmod_AM1808/d_pwm.c

**Comment by dlech** [comment]
Here is what is actually in the ev3dev kernel: <https://github.com/ev3dev/ev3-kernel/blob/ev3dev-jessie/arch/arm/mach-davinci/board-legoev3.h>

As far as I know, all motor ports work with the ev3dev kernel, so I assume that the link above is correct. If it does not match the "kernel hackers notebook" page, then please submit a pull request to fix it.

lms2012 has pins for 3 different hardware revisions. `FINAL` and `FINALB` are pre-release hardware and is not supported on ev3dev. `EP2` is the production hardware and should match what is in ev3dev.

**Comment by dlech** [comment]
Perhaps this is related: https://github.com/ev3dev/ev3-kernel/commit/2759e597544a916d89b38ab38dd4780d48c8e9ce#diff-82715ece61863b7fac95fb9f40a6c61f

**Comment by dlech** [comment]
@erichuang2013, I had to look at this some more due to another bug. I have updated the documentation. Can you confirm that it is now correct?

**Comment by erichuang2013** [comment]
#dlech GPIO pin assignments looks all good for me. However, I have realized the in/out do impact motor output PWM (PPM) correctly to for ESC (Servos). The following code is WORKING script in my side for whom may be interested.

//A GP3_15, GP3_6, 
echo 63 > /sys/class/gpio/export
echo 54 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio63/direction
echo out > /sys/class/gpio/gpio54/direction
//B GP2_1, GP0_3
echo 33 > /sys/class/gpio/export
echo 3 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio33/direction
echo out > /sys/class/gpio/gpio3/direction
//C GP6_8, GP5_9
echo 89 > /sys/class/gpio/export
echo 54 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio89/direction
echo in > /sys/class/gpio/gpio54/direction
//D  GP5_3, GP5_10
echo 83 > /sys/class/gpio/export
echo 90 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio83/direction
echo out > /sys/class/gpio/gpio90/direction

//A
echo 0 > /sys/class/pwm/pwmchip9/export 
//B
echo 1 > /sys/class/pwm/pwmchip9/export
//C
echo 0 > /sys/class/pwm/pwmchip5/export
//D
echo 0 > /sys/class/pwm/pwmchip6/export
 
//A ehrpwm1b
echo 20000000 > /sys/class/pwm/pwmchip9/pwm1/period
echo 1000000 > /sys/class/pwm/pwmchip9/pwm1/duty_cycle
echo 1 > /sys/class/pwm/pwmchip9/pwm1/enable
//B ehrpwm1a
echo 20000000 > /sys/class/pwm/pwmchip9/pwm0/period
echo 1000000 > /sys/class/pwm/pwmchip9/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip9/pwm0/enable
//C ecap.0
echo 20000000 > /sys/class/pwm/pwmchip5/pwm0/period
echo 1000000 > /sys/class/pwm/pwmchip5/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip5/pwm0/enable
//D ecap.1
echo 20000000 > /sys/class/pwm/pwmchip6/pwm0/period
echo 1000000 > /sys/class/pwm/pwmchip6/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip6/pwm0/enable

cat /sys/kernel/debug/gpio
cat /sys/kernel/debug/pwm
