### ISSUE TITLE
Brickd: make power limits configrable 

### ISSUE THREAD

**Issue by MichaelMraka** [ev3dev/ev3dev#1211]
### What are you trying to do?
I've created DIY ev3 power adapter powered from USB. It works fine, `cat /sys/class/power_supply/lego-ev3-battery/voltage_now` actually says 4830733, which a bit lower than 5V and actually quite close to voltage shutdown limit (4.8V). The issue is that sometimes (e.g. when running two large motors simultaneously) voltage can drop for a while bellow shutdown limit and ev3 reboots.
I'd like to be able to change voltage shutdown limit so the brick does not shutdown unexpectedly.

### What hardware and software are you using (including version numbers)?

Image file:         ev3dev-stretch-ev3-generic-2018-08-06
Kernel version:     4.14.61-ev3dev-2.2.2-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_TYPE=main

**Comment by dlech** [comment]
I'm not really comfortable saying that we support running the EV3 at < 5V. There are a number of things that need 5V to work right, most notably, the analog/digital converter that detects sensors and motors and handles analog sensor values.
