### ISSUE TITLE
Does the EV3 accept python functions?

### ISSUE THREAD

**Issue by AFosch** [ev3dev/ev3dev#1212]
I am using ev3dev python for programming my EV3 and I want to write a code that includes some functions. Does someone know if it is possible to do it with the regular function definition on python?  Or the EV3 does only reads scripts? Because I had issues with the EV3 not accepting the functions.

**Comment by dlech** [comment]
Can you share your code? What error messages did you get?

**Comment by AFosch** [comment]
Actually it was a coding error, the function was not accepting the variables I provided. But now it works perfectly. However thanks for everything.
