### ISSUE TITLE
wifi dongle ok on ev3dev-stretch but not on jessie

### ISSUE THREAD

**Issue by huaiwens** [ev3dev/ev3dev#1214]
### What are you trying to do?
Hi experts,
With the same wifi dongle (RA-LINK mini  usb dongle, not clear specification);

There is no problem to enable wifi and access internet with version:
ev3dev-stretch-ev3-generic-2018-11-13

but no wifi available  with
ev3dev-jessie-ev3-generic-2017-09-14

### What did you expect to happen?
There is 'power' shown in Wireless and Connection->wifi->
with jessie release;

### What actually happened?
not wifi available

### What hardware and software are you using (including version numbers)?

EV3

**Comment by dlech** [comment]
Sorry, we are no longer making updates to ev3dev-jessie.
