### ISSUE TITLE
no nodejs in stretch release

### ISSUE THREAD

**Issue by huaiwens** [ev3dev/ev3dev#1215]
### What are you trying to do?
I want to run node.js programs on EV3. Checked the posts in history that node.js was ever contained in ev3dev release but I cannot find it with latest stretch release even I can find it in Jessie release.

### What did you expect to happen?
run node.js on stretch release

### What actually happened?
node.js is not installed.

### What hardware and software are you using (including version numbers)?
ev3dev-stretch-ev3-generic-2018-11-13

**Comment by dlech** [comment]
nodejs (the underlying V8 engine actually) dropped support for the EV3's CPU in 2012 and nodejs was removed from the armel port of Debian in Stretch.

**Comment by huaiwens** [comment]
Thanks for your replay. Is there a way that I can install the nodejs for EV3 CPU (ARM V5?) for test purpose only?

**Comment by dlech** [comment]
You could try installing the debian package from jessie. Something like this...

    wget http://ftp.us.debian.org/debian/pool/main/libv/libv8-3.14/libv8-3.14.5_3.14.5.8-8.1_armel.deb
    sudo dpkg -i libv8-3.14.5_3.14.5.8-8.1_armel.deb
    wget http://ftp.us.debian.org/debian/pool/main/n/nodejs/nodejs_0.10.29~dfsg-2_armel.deb
    sudo dpkg -i nodejs_0.10.29~dfsg-2_armel.deb

But be aware it is v0.10, so isn't probably very useful (e.g. don't expect `npm` to work).

There is a JavaScript engine pre-installed on ev3dev called `gjs` if you just want JavaScript.
