### ISSUE TITLE
Newbie Question 

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev#1229]
### What are you trying to do?

Hello, I'm a newbie to robotics world. I'm trying to learn Robotics with Python.  Seems EV3 is very promising and very interesting. 

( This is dumb question but I still know it before I start with it.... ) 

Does this combo works ?  Did any body try or use it ? Any issue faced or any advise ? 

1. LEGO MINDSTORMS EV3 31313 Robot Kit
2. Python 3.7.2 
3. Visual Studio with ev3dev-browser extensions. 
4. MacOS ( either via Bluetooth or Network connectivity options )

**Comment by dlech** [comment]
Answered on IRC
