### ISSUE TITLE
Issue with ConnMan and DNS in snapshot-ev3dev-buster-ev3-generic-2019-03-03

### ISSUE THREAD

**Issue by DJuego** [ev3dev/ev3dev#1230]
I am testing the new **buster** ev3dev with EV3.

I got:

```
robot@E16:~$ ping www.google.es
ping: www.google.es: Name or service not known
robot@E16:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=30.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=30.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=30.4 ms
```
I used:

```
sudo ln -sf /run/connman/resolv.conf /etc/
```
It seems work!

@dlech made the next comment:

> So as a workaround, you should be able to create a file /etc/tmpfiles.d/connman.conf
>  ```d    /run/connman    - - - - ```
>  ```L+    /etc/resolv.conf    - - - -    /run/connman/resolv.conf ```
> and open an issue on GitHub to add this to the ev3dev-connman-config package
> oops, make that /etc/tmpfiles.d/connman_resolvconf.conf

DJuego

**Comment by dlech** [comment]
Should be fixed in `ev3dev-connman-config_1.3.0`.
