### ISSUE TITLE
unable to import ev3dev.ev3

### ISSUE THREAD

**Issue by Dodgy-Jedi** [ev3dev/ev3dev#1232]
### What are you trying to do?
Use Bluetooth to run programs on ev3 via vscode. Followed instructions here:
https://sites.google.com/site/ev3devpython/setting-up-vs-code

### What did you expect to happen?
Program to import and run.

### What actually happened?
![image](https://user-images.githubusercontent.com/48675128/54587325-85e76000-4a6b-11e9-9d61-4a4bd6c55438.png)

### What hardware and software are you using (including version numbers)?
whatever the latest version is...left robot and gear at school

**Comment by dlech** [comment]
Duplicate of #1220. Please comment there if you still have problems.
