### ISSUE TITLE
How do I give an input to my ev3 brickman? 

### ISSUE THREAD

**Issue by anzy0621** [ev3dev/ev3dev#1243]
### What actually happened?
I tried running the ev3 python file in my brick from my VScode but the input command appeared in the output window of VS code  and I could not enter any values as output window is jus read-only. I Dont know how to reroute it to the TERMINAL WINDOW so that the python programs on the brick take in some input values like regular non-ev3 python programs

**Comment by anzy0621** [comment]
![2](https://user-images.githubusercontent.com/37059022/55655670-cf051700-57c2-11e9-8ede-ceb565fb1a80.JPG)

It says "cannot edit in read-only editor" Does ev3 python take in any input values? I searched everywhere but did not find any example ev3 python files that ask to input any values to the brickman like the non-ev3 python does using the "input"command

**Comment by dlech** [comment]
To get a "real" terminal, you can open an SSH terminal in VS Code.

![](https://github.com/ev3dev/vscode-ev3dev-browser/raw/master/.README/device-context-menu.png)

Then run your program like this:

    brickrun -r ./Python_ev3_codes/motor.py

The `-r` option redirects the input and output to the terminal like you want.

**Comment by anzy0621** [comment]
Hi David thank you so much for helping me with that! But I have another issue while doing that. When I try to run the command you suggested above it says there’s no recognized “r” command. Then I ran brickrun —help to see the list of commands and the “ -r” command doesn’t seem to exist in the list of commands. Should I update something or add an extension? 
TIA 
Anusha

**Comment by dlech** [comment]
It sounds like you don't have the most recent version. You can upgrade via `apt` or re-flash your microSD card.

**Comment by anzy0621** [comment]
Thank you, David! It works,  I also, just have one last question! Sorry about that but really need help with it 
Does the input statement actually take in user input values in python ev3 or do I need a keyboard connected to brickman to enter values? Because when I run the program which has this statement 
x = input("enter a value") 

The ssh terminal takes in an integer value that I enter but does not do anything with it.. the program keeps running forever until I press the middle button on the brickman then the program just runs but doesn't do anything with the integer input value I just gave in. Is it possible that its something not yet included in the ev3 python yet? I'm trying to give in some integer values that the brickman takes and passes this value as an argument to to sensors/motors as distance or speed etc.
![2](https://user-images.githubusercontent.com/37059022/55696601-c27fea80-598b-11e9-9538-4a1886ce9219.JPG)

**Comment by dlech** [comment]
I don't see where you used the `-r` option. It won't work without it.

**Comment by anzy0621** [comment]
Sorry, I got confused, I thought the brick run --directory was the same thing. I have ev3 stretch 2018-11-13 version and I cannot find any other latest version than this. And my sudo apt commands don't work as shown below so I don't know how else to upgrade/update
![3](https://user-images.githubusercontent.com/37059022/55746002-a4a39b80-5a06-11e9-90ef-9bfa100467e3.JPG)
. Is it because I'm using vscode?

**Comment by dlech** [comment]
You have to connect your EV3 to the Internet to upgrade packages. https://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/

**Comment by anzy0621** [comment]
Thank you David! My issue is resolved! Thank you so much for your assistance, it was of great help to me! My brick is taking user input values now and running the motors!

**Comment by dlech** [comment]
Glad to hear it is working.
