### ISSUE TITLE
Simplifying host-side setup for ev3dev

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#126]
While working with ev3dev from a Windows machine, one of the most annoying things for me has been the ICS setup. I have had to change the device driver every time I flash a new image to the SD card, and I often have had to re-set the internet settings after I reboot either the host PC or the brick. Although there are other solutions (such as custom drivers), those are a lot of work, so I decided to try to automate as much of this as possible using PowerShell.

So far, I have written a script that sets up the connection sharing automatically, and I'm working on setting up the drivers. I was thinking that scripts like this might be something that other people would want. Would we be interested in creating either a folder in the main ev3dev repo or a new separate repo to hold scripts like this? I'm sure there are similar tasks that people would want to automate on other platforms, too.

For now, I have put the script in my fork of the ev3dev repo here: https://github.com/WasabiFan/ev3dev/blob/master/helper-scripts/Setup-Windows-Host.ps1. Feel free to check it out!

**Comment by dlech** [comment]
Is this something we should put on the www.ev3dev.org site?

**Comment by WasabiFan** [comment]
> Is this something we should put on the www.ev3dev.org site?

Are you talking about the PS script that I wrote? If so, I don't think it's required. There are still some quirks when using ev3dev with Windows (IP addresses change on each boot, internet connection sometimes must be reset, etc.) but I don't think a script would fix this either way.

**Comment by dlech** [comment]
The USB RNDIS Gadget driver is supposed to provide a fixed MAC address for the EV3. I'm not sure that it is doing this. (It does work correctly for the CDC gadget). If this is the case, it would be worth opening a new issue for that, we might be able to do something about it.

Probably not much we can do about having to reset ICS, although using a static IP for the EV3 seems to help.

**Comment by WasabiFan** [comment]
> Probably not much we can do about having to reset ICS, although using a static IP for the EV3 seems to help.

It would fix the issue of the changing IP, but I haven't been able to give the EV3 an internet connection and use a static IP at the same time -- the host Windows machine seems to only allow internet access if it is the DHCP server. But that's more of a Windows issue than an ev3dev issue.

**Comment by dlech** [comment]
Interesting. I don't use Windows much, but the static IP has always worked for me using the "Windows Defaults" in brickman.
