### ISSUE TITLE
Sensors not working

### ISSUE THREAD

**Issue by Chickenboy445** [ev3dev/ev3dev#1261]
Our ev3 brick won't recognize any sensors. They are plugged into the correct side of the brick. The motors work fine but the sensors don't work. I went into the Lego Mindstorms software to ensure that the hardware works and the Mindstorms recognizes that the sensors are connected. Any recommendations/solutions?

**Comment by DJuego** [comment]
Yes. I have a very similar problem (!!) (fully updated stretch ev3dev). It only detects the contact sensor...

DJuego

PS: It works the NXT-Light sensor, too. 
EV3 Ultrasound  and EV3 color doesn't work. I suspect that the affected sensors are "ev3-analog".

**Comment by JorgePe** [comment]
Yes, recent updates broke UART sensors, it's alredy being addresed: #1249
