### ISSUE TITLE
Cannot connect to Pixy with ev3dev

### ISSUE THREAD

**Issue by Combii** [ev3dev/ev3dev#1282]
I have a pixy 2 that I'm trying to connect with the following code

pixy = Sensor(address=INPUT_1)
assert pixy.connected, "Connecting PixyCam"

Unfortunately I cannot connect to my Pixy 2 and don't really know what to do.

Connecting to with TouchSensor(address=INPUT_4) works fine. But not when I try with Pixy 2.

I've found the code from here: https://www.ev3dev.org/docs/tutorials/using-pixy-camera/

Do anyone know what I can do? See picture for error code.
<img width="683" alt="62HHc" src="https://user-images.githubusercontent.com/17592401/58763011-3ab2f880-8556-11e9-86dd-8cdb260873c7.png">

**Comment by dlech** [comment]
Ev3dev does not have built-in support for the Pixy 2. It can still be used with the python smbus library though. Also see https://github.com/ev3dev/ev3dev-lang-python/issues/640.
