### ISSUE TITLE
ev3dev GUI not loading/opening after 'apt-get upgrade'

### ISSUE THREAD

**Issue by Glass2721** [ev3dev/ev3dev#1283]
**What are you trying to do?**

Run command 'sudo apt-get upgrade' - this command was run on a fresh copy of ev3dev stretch

Note: 'sudo apt-get update' works fine

**What did you expect to happen**

The command should have run successfully. (without errors)

**What actually happened**

While said command was running, the brick suddenly and unexpectedly turned from gui to console mode (I don't know if that's the correct way of saying that) - it also seemed to give some errors. Restarting didn't work (I restarted through the ssh server). The ssh server starts however, so I can interface with the brick. However the GUI never starts (a problem because I need bluetooth). The last line on the ev3 console states (everything else on the screen seems okay) when it gets stuck after restarting:

'[TIME] Timed out waiting..c.1.auto.device.'

I reimaged the sd card and ran the command again. The problem persists.

**Robot:**
 - Device: EV3
 - Versions: latest ev3dev stretch release

lf you want the output of 'sudo apt-get upgrade' on a fresh copy of ev3dev stretch outputs, I can give that to you.

**Comment by dlech** [comment]
> lf you want the output of 'sudo apt-get upgrade' on a fresh copy of ev3dev stretch outputs, I can give that to you.

Yes please.

**Comment by Glass2721** [comment]
I've attached a text file with the output here.
[Output.txt](https://github.com/ev3dev/ev3dev/files/3268044/Output.txt)

**Comment by Glass2721** [comment]
I've solved the problem - some important packages were 'held back'. I just had to bypass that and ev3dev rebooted fine.

**Comment by racheliurui** [comment]
> I've solved the problem - some important packages were 'held back'. I just had to bypass that and ev3dev rebooted fine.

Hi, @jonajia could you share more details about how to bypass the problem? I am having the same issue with booting my EV3

Thanks 
=====
BTW, while I am typing the question, I found this time the EV3 eventually started up , it just need a few restart.. Not sure why, but someone has mentioned this behavior of restarting several times to fix this issue.
