### ISSUE TITLE
Hitechnic Compass Ev3dev Driver Specifications

### ISSUE THREAD

**Issue by Glass2721** [ev3dev/ev3dev#1301]
Hey there,

Do you know if the Compass values from the Hitechnic Compass is presented 'As is' from the sensor, or are the values modified in any way by the driver code? (if so, how?)

Thanks.

**Comment by dlech** [comment]
They are directly from the sensor as far as I know.

Source code is here: https://github.com/ev3dev/lego-linux-drivers/blob/bd56e4527bfe7eacddf3e8135463e69e2bdcb6e3/sensors/nxt_i2c_sensor_defs.c#L1175

**Comment by Glass2721** [comment]
Ok thanks
