### ISSUE TITLE
EV3 wired and bluetooth is not working

### ISSUE THREAD

**Issue by AlphaPranav9102** [ev3dev/ev3dev#1303]
**What are you trying to do?**

I am trying to connect the robot to my computer via Bluetooth or wired connection in order to link up to a separate joystick program. I have looked at all tutorials applicable I think.

**What did you expect to happen**

The program should have connected in the wired version with a status of "Online" and the bluetooth attempt should have connected and the program should have worked.

**What actually happened**

The robot didn't connect with the status of "online" and instead shows "Connected". The bluetooth connection connects but the program spits out errors. My program is ...

```
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.sensor import INPUT_1

ts = TouchSensor(INPUT_1)
```
The error which I get is ...

```
Traceback (most recent call last):
  File "C:\Users\PenguinKid\Documents\sddcFolder\ps4main.py", line 4, in <module>
    ts = TouchSensor(INPUT_1)
  File "C:\Users\PenguinKid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ev3dev2\sensor\lego.py", line 49, in __init__
    super(TouchSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs)
  File "C:\Users\PenguinKid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ev3dev2\sensor\__init__.py", line 94, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "C:\Users\PenguinKid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ev3dev2\__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "C:\Users\PenguinKid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ev3dev2\__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: TouchSensor(in1) is not connected.
```

**Question**
How do I get my connections working and get my program connected and running on the EV3?

**Comment by wizard1066** [comment]
Alpha,
Sorry more questions than answers. The error message you posted is reporting that the touch sensor it is looking for is not connected. It may be a lose plug, a cracked wire or the wrong port. Nothing to do with the internet.
Assuming you're trying to connect a PS4 controller by the name pf your program, ps4main.py. Note connecting it is a different procedure to connecting a PS3 controller, make sure you're reading the right article. 
Finally you don't need the internet on a day to day basis for the LEGO brick, but beware if you're trying to connect it to say the school WiFi they may be blocking the ports you need to use to make that connection.
