### ISSUE TITLE
docker exec --tty brickman_armel make error in MACOS

### ISSUE THREAD

**Issue by zhanwen** [ev3dev/ev3dev#1321]
**Question**
docker exec --tty brickman_armel make

[  6%] Built target brickman_data
[  8%] Linking C executable brickman
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabi/8/../../../libev3devkit-0.5.so: undefined reference to `pow10'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/brickman.dir/build.make:1366: brickman] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/brickman.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Background Information**

i already install [ev3devKit](https://github.com/ev3dev/ev3devKit), brickman step have been success. ./docker/stepup.sh armel 

**Screenshots**
![image](https://user-images.githubusercontent.com/11382789/66012225-e9f9df00-e4f8-11e9-8324-a8a314763fcb.png)

**Comment by zhanwen** [comment]
./docker/setup.sh armel 

![image](https://user-images.githubusercontent.com/11382789/66012920-ab195880-e4fb-11e9-8ad2-35edad72d35b.png)

**Comment by dlech** [comment]
`pow10(...)` probably needs to be replaced with `pow(10,...)`

**Comment by jankow86** [comment]
I am expecting exactly the same issue. Could you please guide me how to solve this problem?
