### ISSUE TITLE
ev3dev open source ?

### ISSUE THREAD

**Issue by zhanwen** [ev3dev/ev3dev#1322]
**Question**
![image](https://user-images.githubusercontent.com/11382789/66030099-33ffb680-e533-11e9-95ce-88805e3cb5aa.png)

Thanks，Where can I find the ev3dev-stretch-ev3-generic-2019-03-03.zip
 source code？

**Comment by dlech** [comment]
ev3dev is an entire operating system based on Debian. So virtually everything has a Debian source code package. https://packages.debian.org/stretch/

Everything that was developed specifically for ev3dev is hosted in the ev3dev GitHub organization. https://github.com/ev3dev

**Comment by zhanwen** [comment]
thanks, i have try build brickman.
