### ISSUE TITLE
Automake/Make not working

### ISSUE THREAD

**Issue by gideongrinberg** [ev3dev/ev3dev#1330]
I was trying to download jhbuild and could not use the make command. I tried:

`sudo automake ./autogen.sh`
`sudo: automake: command not found`

`sudo make ./autogen.sh`
`sudo: make: command not found`

To install it i tried:
<img width="600" alt="Screen Shot 2019-10-14 at 11 10 44 AM" src="https://user-images.githubusercontent.com/49839886/66762116-57036200-ee73-11e9-8c91-49c2e8d2735c.png">
and 
<img width="598" alt="Screen Shot 2019-10-14 at 11 12 00 AM" src="https://user-images.githubusercontent.com/49839886/66762180-7b5f3e80-ee73-11e9-857a-f5f2c5495a31.png">

I am trying to do this so I can use GTK and ev3dev kit UI for a menu loader to run python scripts faster in FLL.

**Comment by dlech** [comment]
You need to run `sudo apt update` first.

You can start programs from the File Browser on the brick already, so I don't see how this would make things faster though.

**Comment by dlech** [comment]
Also, I just looked up what jhbuild is. I don't think it will be useful in this case since we don't use it in for anything ev3dev.

**Comment by dlech** [comment]
Although I suppose you could use ev3devKit in python to make something that could load programs faster if it doesn't start a new python process, but in that case you don't need any build tools to write python program.

**Comment by gideongrinberg** [comment]
I made a menu that runs functions on a button press so everything loads on startup. I use jhbuild to install GTK. ev3devKit includes a UI tool that needs GTK. Thanks for the input I will try this.
