### ISSUE TITLE
Pip not working

### ISSUE THREAD

**Issue by gideongrinberg** [ev3dev/ev3dev#1333]
Hi,
I have been trying to `pip install` a package and I get an error that says `pip not found`. To fix this I have used the `pip3` command which generates the same error. I have try `sudo apt-get install pip` and `sudo apt-get install pip3` and `sudo apt-get python3-pip` as well as the get-pip.py file from PyPA. All of these either finish running and still don't work or disconnect my SSH session and give a broken pipe error. I have tried this on the en3 and bridge100 interfaces.

**Comment by gideongrinberg** [comment]
I used both Mac and Windows OS

**Comment by dlech** [comment]
See #1273, #873, etc.

**Comment by gideongrinberg** [comment]
Thanks

**Comment by meglai** [comment]
> I am having the same issue running `pip3`. In #1273 and #873, the problem apparently was resolved by re-installing pip3 multiple times. I installed and uninstalled many times already, but when run `pip3 --version`, nothing happens after I waited for a long time. Please help. I am trying to install 'pip3 install paho-mqtt' to complete my ioT project.

**Comment by gideongrinberg** [comment]
Try `sudo apt-get install python3 paho-mqtt`. Hope I can help

**Comment by wiseOsprey1** [comment]
pip3 install always fails for me

robot@ev3dev:~$ sudo pip3 install paho-mqtt
Collecting paho-mqtt
  Could not find a version that satisfies the requirement paho-mqtt (from versions: )
No matching distribution found for paho-mqtt

I tried the following but it failed too:

robot@ev3dev:~$ sudo apt install python3 paho-mqtt
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package paho-mqtt

**Comment by dlech** [comment]
PyPi no longer supports Python 3.5. Ev3dev-stretch uses Python 3.5. So `pip3` is probably no longer usable for any package.

**Comment by wiseOsprey1** [comment]
Thanks.  What's the best way to install paho-mqtt?  Is there an image archive that I can download and install?  If so, can you provide instructions?

**Comment by dlech** [comment]
I would try installing the debian package from a newer version of debian. https://tracker.debian.org/pkg/python-paho-mqtt

Untested:
```
wget http://ftp.us.debian.org/debian/pool/main/p/python-paho-mqtt/python3-paho-mqtt_1.5.1-1_all.deb
sudo dpkg -i python3-paho-mqtt_1.5.1-1_all.deb
```

**Comment by dlech** [comment]
This seems to work (just tested that importing works in Python). So I copied the package to the ev3dev archive for stretch. So now this should work:

```
sudo apt update
sudo apt install python3-paho-mqtt
```

**Comment by wiseOsprey1** [comment]
Thanks.  I was able to import the module into my program.  My program acts like it's working properly, but the messages I'm posting to broker.hivemq.com from my EV3 aren't being seen by my subscriber on Windows 10.  That subscriber does see messages from my Windows 10 mosquitto_sub test application.  I'll look for discussions addressing that issue.  If you know of any, please advise.

**Comment by gideongrinberg** [comment]
You can also always use the [files section](https://pypi.org/project/paho-mqtt/#files) on PyPi to download a wheel or source distribution. Seeing as `pip` is no longer usable with ev3dev, I'm going to close the issue.
