### ISSUE TITLE
EV3SensorMUX and Split_NXT-v2 port splitters do not function simultaneously

### ISSUE THREAD

**Issue by naynt** [ev3dev/ev3dev#1335]
**Problem**
I have a split_NXT-v2 and a EV3SensorMux port splitter but only one splitter is able to function at any given time. If I add one splitter to port 1 and the other to port 2 (and vice versa), only the port splitter in port 1 functions, while the one in port 2 is not detected.

**Setup**
EV3SensorMux connected to either port 1 or 2 - sensors connected = EV3 Ultrasonic sensor, EV3 IR Sensor and EV3 Gyro

Split_NXT_v2 connected to either port 1 or 2 - sensors connected = NXT Barometer, NXT SoundSensor

**Question**
Might this be an address issue or are both splitters only meant to be function in port 1?
                                                                                                             
<!--Windows 10
Visual Studio Code with ev3.dev device browser extension (August 2019 version 1.38)
Image file: ev3dev-stretch-ev3-generic-2019-03-03
Kernel version: 4.14.96-ev3dev-2.3.2-ev3
Brickman v0.10.0

**Comment by dlech** [comment]
Can you draw a picture of how the ports are connected?

**Comment by naynt** [comment]
Sure. 
![sensor setup](https://user-images.githubusercontent.com/15710569/67246623-a9afd000-f4aa-11e9-8a73-d08943264eb0.jpg)

**Comment by naynt** [comment]
**The script I am using**

```python
#!/usr/bin/env python3 

#---------------------------------------------------------------------------------------------------------------

# Test: NXT2 MUX and EV3 MUX

#----------------------------------------------------------------------------------------------------------------

from ev3dev2.sensor.lego import TouchSensor, ColorSensor, GyroSensor, UltrasonicSensor, InfraredSensor
from ev3dev2.port import LegoPort
from ev3dev2.sensor import Sensor
from ev3dev2.sound import Sound
from ev3dev2.sensor.lego import SoundSensor
from sys import stderr
from time import sleep
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
import random

# port 1 = Ultrasonic sensor, Infrared Sensor and Gyro Sensor via EV3 Port splitter
# port 2 = Sound sensor, Barometer sensor
# port 3 = Thermometer EV3
# port 4 = 


sleep(1)

s = SoundSensor(INPUT_2)
s.set_device = 'lego-nxt-sound'
s.mode = 'DBA'
a = s.sound_pressure_low
a1 = print("sound pressure low: ",file=stderr)
b = s.value(0)
b1 = print("sound value: ",file=stderr)
sleep(1)

temp = Sensor(INPUT_2)
temp.mode = 'TEMP'
c = temp.value(0)
c1 = print("Temp NXT: ",file=stderr)

pressure = Sensor(INPUT_2)
pressure.mode = 'PRESS'
d = pressure.value(0)
d1 = print("Pressure: ",file=stderr)

tempC = LegoPort(INPUT_3)
tempC.set_device = 'lego-nxt-temp'
sleep(1)
temp = Sensor()
e = temp.value()
e1 = print("EV3 temp: ",file=stderr)

us = UltrasonicSensor(INPUT_1)
f = us.value(0)
g = us.MODE_US_DIST_CM
f1 = print("Ultrasonic value: ",file=stderr)
g1 = print("Distance CM: ",file=stderr)

ir = InfraredSensor(INPUT_1)
h = ir.value(0)
h1 = print("Proximity value: ",file=stderr)
i = ir.MODE_IR_PROX
i1 = print("Promity : ",file=stderr)

gyro = GyroSensor(INPUT_1)
j = gyro.value(0)
j1 = print("Gyro value: ",file=stderr)
k = gyro.MODE_GYRO_ANG
k1 = print("Angle: ",file=stderr)

#------------------------------------------------------------------------------------------

#EV3 Sensor Multiplexor

#EMX = LegoPort(INPUT_2)
#EMX.set_device = 'MUX'
#ev3multi = Sensor()

# NXT sensor Mutliplexor

#NMX = LegoPort(INPUT_1)
#NMX.set_device = 'MUX'
#nxtmulti = Sensor()

#---------------------------------------------------------------------------------------------
sleep(1)
print (a1,a,b1,b,c1,c,d1,d,e1,e,f1,f,g1,g,h1,h,i1,i,j1,j,k1,k, file = stderr)
sleep(2)
print (a1,a,b1,b,c1,c,d1,d,e1,e,f1,f,g1,g,h1,h,i1,i,j1,j,k1,k, file = stderr)`
```

```
Traceback (most recent call last):
  File "/home/robot/Main Scripts/Split-Sensors.py", line 28, in <module>
    s = SoundSensor(INPUT_2)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/lego.py", line 925, in __init__
    super(SoundSensor, self).__init__(address, name_pattern, name_exact, driver_name='lego-nxt-sound', **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 94, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: SoundSensor(ev3-ports:in2) is not connected.
----------
Exited with error code 1.
```

**Comment by naynt** [comment]
Traceback (most recent call last):
  File "/home/robot/Main Scripts/Split-Sensors.py", line 51, in <module>
    s = SoundSensor(INPUT_1)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/lego.py", line 925, in __init__
    super(SoundSensor, self).__init__(address, name_pattern, name_exact, driver_name='lego-nxt-sound', **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 94, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: SoundSensor(ev3-ports:in1) is not connected.
----------
Exited with error code 1.

**Comment by dlech** [comment]
The NXT sounds sensor is an analog sensor, so it won't work with either of the port splitters. The temperature sensor and the barometer are both I2C and have different I2C addresses, so they can both be connected to the NXT port splitter.

You can use the Device Browser on the EV3 to find the "address" of each sensor and port. The `INPUT_1` constants only work if a sensor is connected directly to the port, otherwise, you need to use a string that contains the full address.

**Comment by naynt** [comment]
Thank you, that clears things up.
