### ISSUE TITLE
EVB 1.0 Won't Boot with BBB

### ISSUE THREAD

**Issue by Xaplomian** [ev3dev/ev3dev#1362]
**What are you trying to do?**

I am trying to get the EVB to boot.

**What did you expect to happen**

I expected it to boot.

**What actually happened**

It just displayed a white screen. All the LEDs on the BBB did turn on though: power and all four user LEDs.

**Robot (please complete the following information):**
 - Device: EVB with BBB
 - Versions: ev3dev-stretch R1 and ev3dev-stretch R2
 - I have installed the normal firmware for EVB with the SD card to confirm that the hardware work and SD card work.

**Background Information**

I just want to use the EVB.

**Comment by dlech** [comment]
Did you edit the `uEnv.txt` on the SD card file first?

**Comment by Xaplomian** [comment]
I did not, as I was not aware that was necessary. It is now working.
