### ISSUE TITLE
Firgelli L12 EV3-100

### ISSUE THREAD

**Issue by MetallianFR68** [ev3dev/ev3dev#137]
Hi,

I just discovered EV3DEV some days ago and I'm very excited about the functionnalities
It's the ultimate solution for my project (a camera motion controller for timelapse)

I just tested it with my new firgelli actuators
I think that something is wrong when using these motors in position run_mode

For example : 
I reset the position to 0
I ask the actuator to go to position 100
but it runs in the opposite way, going from 0 to negative values.

the problem is the same when trying to retract the actuator
I reset the position to 0
I ask the actuator to go to position -100
but it runs in the opposite way, going from 0 to positive values.

Is it a bug in EV3DEV or am I missing something ?

**Comment by dinof** [comment]
Hi!
Please stop me if this is the wrong place to ask. I am looking for some user feedback on those Firgelli actuators. We would like to use it for a demonstration of a real time controller. For sure it is not an industrial actuator, but does it have a lot of freeplay, for example? And what is the resolution of the encoder? They don't provide much data on their website.
Thank you for the info!
