### ISSUE TITLE
Change device name from ev3dev?

### ISSUE THREAD

**Issue by kjtumminello** [ev3dev/ev3dev#1373]
**Question**
Is there a way to change the ev3dev device name to a different name?

**Background Information**
I am working with a group of students.  We have four robots and have trouble establishing our Bluetooth connections because all the robots are "ev3dev"

 - OS and version: Window 10 
- Connection Type: Bluetooth
- Software: ev3dev, Visual Studio Code

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: ev3-dev-browser 1.0.4

**Comment by dlech** [comment]
run `sudo ev3dev-config`

In the menu there is an option to change the host name.

**Comment by kjtumminello** [comment]
thanks!
