### ISSUE TITLE
Bluetooth not avaliable

### ISSUE THREAD

**Issue by bemxio** [ev3dev/ev3dev#1389]
**What are you trying to do?**

I am trying to turn on Bluetooth

**What did you expect to happen**

Just turning on and the configuration will be avaliable

**What actually happened**

it just says "not avaliable", even when i restart, it's the same

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS and version: [Windows 10 1903]
 - Connection Type: [Bluetooth]

**Robot (please complete the following information):**
 - Device: [EV3]
 - Kernel: 4.14.117-ev3dev-2.3.4-ev3
 - Model: LEGO MINDSTORMS EV3
 - Revision: 0000

**Comment by dlech** [comment]
See #1314

**Comment by bemxio** [comment]
nvm, i decided to use usb, but i have another problem (issue #1390)
