### ISSUE TITLE
Cannot Bluetooth-connect with EV3 device in VSCode EV3Dev Device Browser on 1 particular MacBook

### ISSUE THREAD

**Issue by TheVinhLuong102** [ev3dev/ev3dev#1412]
**What are you trying to do?**
I am trying to Bluetooth-connect with the EV3 brick via the Visual Studio Code EV3Dev Device Browser, and am unable to do so with my MacBook (MacBook Pro, Mid 2015) running MacOS Catalina.

**What did you expect to happen**
I have actually succeeded to make the connection with several *other* very similar MacBooks (e.g. my wife's), which all had similar VSCode and the EV3Dev Device Browser plug-in installed.

**What actually happened**
However, on my own MacBook, I keep failing to make the Bluetooth connection via the VSCode Device Browser. The error messages are captured in the screenshots attached.

`Failed to connect to ev3dev: connect EHOSTUNREACH fe80::217:e9ff:feb1:9303%**undefined**:22 - Local (:::<some-number>)`

<img width="542" alt="Screenshot 2020-06-07 01 30 26" src="https://user-images.githubusercontent.com/7796578/83964007-a3663c80-a85e-11ea-868a-9f2eb0256360.png">

I notice the word "**undefined**" in the error message and it seems to be related to the problem.

**Comment by dlech** [comment]
Does this help? https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Troubleshooting

**Comment by TheVinhLuong102** [comment]
@dlech thank you. I followed the troubleshooting guide above but that has not resolved the problem. The error messages like those in the screenshots persist -- even if the device appears as "Connected" in the System Preferences >> Bluetooth screen:

<img width="641" alt="Screenshot 2020-06-07 13 46 56" src="https://user-images.githubusercontent.com/7796578/83979769-9e88a380-a8c5-11ea-8dfd-0b2b6d929037.png">

The screenshots of my System Preferences >> Network settings are as follows:
- for Wifi: 
<img width="636" alt="Screenshot 2020-06-07 13 50 14" src="https://user-images.githubusercontent.com/7796578/83979806-d42d8c80-a8c5-11ea-86c4-eca3db9308a4.png">

- for Bluetooth PAN:
<img width="624" alt="Screenshot 2020-06-07 13 51 20" src="https://user-images.githubusercontent.com/7796578/83979826-fa532c80-a8c5-11ea-9d1e-d538ed6eb2e5.png">

Is there something that I am missing? Thank you very much, @dlech.

**Comment by TheVinhLuong102** [comment]
By the way, @dlech one thing that is different between my case and the troubleshooting scenario described in https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Troubleshooting is that I see the "undefined:22". I'm not sure what that means. Does that look symptomatic of some known problem?

**Comment by dlech** [comment]
`undefined` is supposed to be the name of the network interface. Maybe try removing the "Bluetooth PAN" device and set it up again. Also try turning off Internet Sharing and turning it on again. And try removing the Bluetooth device from Bluetooth as well and try pairing it again.

**Comment by TheVinhLuong102** [comment]
@dlech ah, I have just restarted my laptop to make sure the setting changes you specified get applied, and the connection is working now! :) Maybe you can consider adding Rebooting the Mac to the advice given in https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Troubleshooting#macos?

This issue is now resolved. Thank you so much, @dlech !

**Comment by dlech** [comment]
Great. Rebooting fixes so many problems. :smile:

**Comment by TheVinhLuong102** [comment]
Many thanks again @dlech :)
