### ISSUE TITLE
What is subscribe via Atom on the news page?

### ISSUE THREAD

**Issue by PythonAtSea** [ev3dev/ev3dev#1441]

**Comment by WasabiFan** [comment]
It's an [atom news feed](https://en.wikipedia.org/wiki/Atom_(Web_standard)). If desired, you can add it to an RSS/Atom reader (e.g. many email clients) so posts show up in an easily-accessible place for you.

**Comment by PythonAtSea** [comment]
Can I connect gmail to it?
