### ISSUE TITLE
Branding and SEO

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#146]
We have been having a discussion on some of these topics over in another thread (54 comments so far!), but I wanted to make a dedicated (and more direct) issue about it.

Currently, we have the tagline "Debian Linux for the LEGO MINDSTORMS EV3!". This is fine, but it's not very catchy (as @dlech mentioned in the other issue). So, I think this would probably be a good thing to discuss. @dlech had suggested "The world's most advanced firmware for LEGO MINDSTORMS EV3", and there were a few others being tossed around.

The second thing that goes with this is the logo. We have been passing around a few ideas in #109 for the past few weeks, so it's clear that there is some interest in choosing a logo. There have been many ideas that either include the text "ev3dev" stylized in some way, or the name in some sort of an image form. From discussion over there, I think we probably want to try to avoid LEGO's trademarks/symbols so that we don't get caught up in legal issues.

The third item (and the bigger reason that I opened this issue) is discoverability. Currently, searching for something along the lines of "ev3 custom OS" in Bing or Google returns very little on ev3dev; the first mention occurs around page 5 of the search results, in an excerpt from @mattrajca's blog. I'm thinking we might want to use Microsoft and Google's free SEO tools to make sure that ev3dev.org shows up high on the list in searches like this. Capturing more people's attention when searching would get us more users, and more contributors (which would definitely be good). What do you guys think about that?

I'd be happy to look in to the last item more if we are interested in pursuing it.

**Comment by dlech** [comment]
Still interested in working on this? Or should we close the issue?

**Comment by WasabiFan** [comment]
I did a bit of research on the subject and ran some tests on my own fork of the site, but I was not really able to get good results. If I get some free time, I think I'll take another look, but I'm not an expert in this area so results may vary (the main task is just adding a description somewhere that search engines will index). I think it would be great to get ev3dev higher up in the search results but I think we can close this issue for now.

**Comment by dlech** [comment]
Just for kicks, here is a current snapshot from Google webmaster tools. Looks like people are searching for "ev3 programming" along with "language" or the name of a specific language. Seems like it would be good to target that since that is one of the core features of ev3dev.

**Comment by dlech** [comment]
I'd say we can call this one closed.
