### ISSUE TITLE
cannot poweroff after executing halt

### ISSUE THREAD

**Issue by chubbyginger** [ev3dev/ev3dev#1477]
**Describe the bug**

**To Reproduce**
1. Connect to brick via SSH.
2. Execute `halt`
3. Something scrolled on the screen
4. The indication light kept on and I cannot shut that down but to remove the battery.

```
Please paste a simple program to reproduce the problem here!
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Window 10, macOS 10.14]
 - Connection Type: [e.g. USB, Bluetooth, Wi-Fi]
 - Other software: [e.g. Visual Studio Code, PuTTY]

**Robot (please complete the following information):**
 - Device: [e.g. EV3, BrickPi3]
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

```
Please paste the system info from the ev3dev VS Code extension or the output of `ev3dev-sysinfo -m` here!
```

**Additional context**

**Comment by dlech** [comment]
This is expected. The power button on the EV3 doesn't work unless the OS is running. If you want to turn off the EV3, use `sudo poweroff` or `sudo halt -p`
