### ISSUE TITLE
Keyboard not connecting

### ISSUE THREAD

**Issue by PythonAtSea** [ev3dev/ev3dev#1494]
**What are you trying to do?**

I am trying to connect a bluetooth keyboard to the brick

**What did you expect to happen**

The keyboard show up in brick man

**What actually happened**

The  keyboard did not show up in brickman

**Comment by dlech** [comment]
Can you give the exact steps to reproduce the problem?

**Comment by PythonAtSea** [comment]
1. Turn on keyboard
2. Put keyboard in pairing mode
3. Enter bluetooth settings in brickman
4. Select start scan
5. Keyboard does not show up

The Keyboard does work on my computer
