### ISSUE TITLE
May I drive a LEGO Technic 43362 motor using pybricks?

### ISSUE THREAD

**Issue by chubbyginger** [ev3dev/ev3dev#1499]
**Question**
May I drive a LEGO Technic 43362 motor (picture below) using pybricks?
![pic01](https://user-images.githubusercontent.com/67225026/123503084-2ed98800-d683-11eb-9ab7-bbaec74895b0.jpg)
![pic02](https://user-images.githubusercontent.com/67225026/123503092-3d27a400-d683-11eb-964a-77e43b487000.jpg)
![pic03](https://user-images.githubusercontent.com/67225026/123503093-40229480-d683-11eb-9114-413f6fe1debd.jpg)
When I drive it as a normal motor, vscode returns an OSError 19 ENODEV (as screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/67225026/123503924-9e05ab00-d688-11eb-85fe-8c81b41c3a3a.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 7 64-bit
 - Connection Type: Wi-Fi
 - Software: Visual Studio Code

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

```
Image file:         ev3dev-stretch-ev3-generic-2020-04-10
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534DE339
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
You will need to use the [DCMotor](https://pybricks.com/ev3-micropython/iodevices.html#dc-motor) class for this.
