### ISSUE TITLE
How to unistall brickman (micropython extension)  from ev3 brick? 

### ISSUE THREAD

**Issue by David-Kristek** [ev3dev/ev3dev#1510]
Hello, I would like to know how to remove or unistall brickman (micropython extension)  from ev3 brick : 
![image](https://sites.google.com/site/ev3python/_/rsrc/1529279975214/setting-up-vs-code/brickman.png)

and return it back to basic interface with the possibility to code it in Lego Mindstorm Ev3 : 
![image](https://user-images.githubusercontent.com/77566262/132132713-5793c898-f4f9-4a21-869f-8b8747474150.png)
Thanks for help.

**Comment by dlech** [comment]
Remove the microSD card and the EV3 will boot the original firmware.

**Comment by David-Kristek** [comment]
Thanks, I didnt see it there.
