### ISSUE TITLE
Error when initializing the OS: emergency mode

### ISSUE THREAD

**Issue by MiguelSarraf** [ev3dev/ev3dev#1516]
I am trying to start ev3dev on my brick, but it gets stuck somewhere in the process.

I was trying to install the flask module for an assignment I am currently working on. I opened an SSH connection to my EV3 brick and tried to install pip, then it didn't work and I tried to reboot. After that it keeps showing the message  "You are in emergency mode. After logging in type 'journalclt -xb' to view system logs, 'systemctl reboot' to reboot, 'systemctl default' or ^D to try again to boot into default mode." and nothing more happens.

The commands I used to try to install pip are:

```
sudo apt-get update
sudo apt-get install python3-pip
pip3 install flask #This is the command which does not work
pip install flask #Gives the same error
```

Version I am using:
 - OS and version: Ubuntu 18.04
 - Connection Type: SSH via NAP on Bluetooth

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: ev3dev2.0

**Background Information**

I am trying to install this module because I want to build a robot that can receive requests from other applications.

**Comment by dlech** [comment]
This is usually caused by a defective microSD card or the card is larger than 32GB.

**Comment by MiguelSarraf** [comment]
Understood.
My card is exactly 32GB and brand new (bought it one week ago...). It had worked previously, the problem happened when "installed" pip. Is there anything I can try?

**Comment by dlech** [comment]
You can try a different microSD card.

**Comment by KooshaKayani** [comment]
try flashing the microSD card and make sure that you are running a released version not a beta.

**Comment by MiguelSarraf** [comment]
Thank you all for the replies.
I just got it working again, I had to format the microSD before flashing it and didn't have to get a new one.
