### ISSUE TITLE
Cross-compilation for ev3 on x86_64 pc

### ISSUE THREAD

**Issue by chubbyginger** [ev3dev/ev3dev#1526]
**Question**

How to cross-compile on a x86_64 pc for the ev3 brick (arm926ej-s)?

**Background Information**

I am not going through the official tutorial because apt is working very slowly. Instead I am going to cross-compile my program for ev3 so it will be faster.

After cross-compilation, the ELF file is unable to run on ev3 because the architecture is not right, shell showing output `Exec format error`.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS and version: Windows 7 Service Pack 1
 - Connection Type: SSH
 - Software: Visual Studio Code, WinSCP, MobaXterm

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

```
Image file:         ev3dev-stretch-ev3-generic-2020-04-10
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534DE339
BOARD_INFO_TYPE=main
```

p.s. My makefile:
```makefile
# Makefile for mobile-safe.

# Cross-Compile options
CROSS_COMPILE=arm-linux-gnueabi-
ARCH=armv5te
CPU=arm926ej-s
# The compiler
CC=$(CROSS_COMPILE)gcc

LIBRARY_PATH=./lib
CFLAGS=-march=$(ARCH) -mcpu=$(CPU) -g -static -I$(LIBRARY_PATH) -L$(LIBRARY_PATH)
SRC_LIST=$(wildcard *.c)
OBJ_LIST=$(patsubst %.c,%.o,$(SRC_LIST))
TARGET=mobile-safe.elf

default: all

all:
	$(CC) $(CFLAGS) -o $(TARGET) -c $(SRC_LIST) 

# Simple target to test the environment.
test-env:
	echo int main() {} > dummy.c
	$(CC) $(CFLAGS) dummy.c -o dummy.elf
	rm dummy.elf dummy.c

clean:
	rm mobile-safe.elf
```

**Comment by dlech** [comment]
The recommended method is to use Docker to cross compile. See https://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/.

However Docker requires Windows 10.

You could try running `file mobile-safe.elf` to see what the actual file format is.

**Comment by chubbyginger** [comment]
file shows that this is an `ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), with debug_info, not stripped`

**Comment by chubbyginger** [comment]
Sorry for bothering. After checking my makefile, I found out that there is a small error at line 19. The `-c` should be removed because it will only give some binary object files (actually not executable). 

This makefile should be right:
```makefile
all:
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC_LIST) 
```
