### ISSUE TITLE
need a better wiki?

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#153]
I would like to pick back up on the discussion we started in ev3dev/ev3dev.github.io#13 about the wiki.

I'm starting to get a bit irritated with the limitations of the GitHub wiki. There are 2 main things that are bothering me.
1. The new sidebar. Although the search function is nice, many of our pages use tables. Since the sidebar is taking up so much real estate on the screen, nearly all of the tables have to be scrolled horizontally to see all of the data, which is really annoying. Before the sidebar, the tables displayed just fine. I contacted GitHub support about this and there is currently not a way to disable the sidebar.
2. There is no templating. We currently have about 20 sensor pages that follow the same format. Due to some changes in the kernel, I am having to manually edit all of these files. It would be really nice if there was a template so that I only had to change to formatting once. Also, adding new sensor pages is a bit of a pain because the content gets lost in the formatting (tables).

I'm thinking that maybe we just use MediaWiki. I can install it on my webserver and we can have wiki.ev3dev.org.

Any better ideas?

EDIT: TODO List...
- ~https://github.com/ev3dev/ev3dev/wiki/Frequently-Asked-Questions~
- [x] https://github.com/ev3dev/ev3dev/wiki/Posting-A-Project
- [x] https://github.com/ev3dev/ev3dev/wiki/Set-Up-An-nfs-FileShare
- [x] https://github.com/ev3dev/ev3dev/wiki/Using-Sound
- [x] https://github.com/ev3dev/ev3dev/wiki/Using-the-LEDs
- [x] https://github.com/ev3dev/ev3dev/wiki/Using-brickstrap-to-cross-compile-and-debug
- [x] https://github.com/ev3dev/ev3dev/wiki/Using-the-Buttons
- [x] https://github.com/ev3dev/ev3dev/wiki/Using-the-LCD

**Comment by dlech** [comment]
This issue seems to have been forgotten about, so I'm resurrecting it. The following wiki pages still need to be migrated to the ev3dev.org website...

- [ ] https://github.com/ev3dev/ev3dev/wiki/Frequently-Asked-Questions
- [ ] https://github.com/ev3dev/ev3dev/wiki/Posting-A-Project
- [ ] https://github.com/ev3dev/ev3dev/wiki/Set-Up-An-nfs-FileShare
- [ ] https://github.com/ev3dev/ev3dev/wiki/Using-Sound
- [ ] https://github.com/ev3dev/ev3dev/wiki/Using-the-LEDs
- [ ] https://github.com/ev3dev/ev3dev/wiki/Using-brickstrap-to-cross-compile-and-debug
- [ ] https://github.com/ev3dev/ev3dev/wiki/Using-the-Buttons
- [ ] https://github.com/ev3dev/ev3dev/wiki/Using-the-LCD

These all seem like they should go under "tutorials", so pick one and copy it over.

**Comment by dwalton76** [comment]
Is there an alternative to jekyll to view your changes locally? I'm on Ubuntu 14.04 and cannot get RedCloth -v '4.2.9' to install.

**Comment by dlech** [comment]
Hmm... I'm on Ubuntu 14.04 as well and it is working for me. What is the specific error message? Do you have the `ruby2.0-dev` package installed?

**Comment by dwalton76** [comment]
yep, rub-dev is installed

dwalton@laptop[ev3dev.github.io]# sudo apt-get install ruby-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ruby-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
dwalton@laptop[ev3dev.github.io]# 
dwalton@laptop[ev3dev.github.io]# ruby --version
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
dwalton@laptop[ev3dev.github.io]# 
dwalton@laptop[ev3dev.github.io]# 
dwalton@laptop[ev3dev.github.io]# 
dwalton@laptop[ev3dev.github.io]# sudo gem install RedCloth -v '4.2.9'
Building native extensions.  This could take a while...
ERROR:  Error installing RedCloth:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking for main() in -lc... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--with-redcloth_scan-dir
	--without-redcloth_scan-dir
	--with-redcloth_scan-include
	--without-redcloth_scan-include=${redcloth_scan-dir}/include
	--with-redcloth_scan-lib
	--without-redcloth_scan-lib=${redcloth_scan-dir}/lib
	--with-clib
	--without-clib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
	from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
	from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
	from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/RedCloth-4.2.9 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/RedCloth-4.2.9/gem_make.out
dwalton@laptop[ev3dev.github.io]#

**Comment by dlech** [comment]
so what is in `/var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/RedCloth-4.2.9/gem_make.out`?

**Comment by dlech** [comment]
Also, what is `dpkg-query -W ruby-dev`? I've got:

    $ ruby --version
    ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]

so maybe you have a version mismatch between `ruby` and `ruby-dev`

**Comment by dwalton76** [comment]
```
dwalton@laptop[ev3dev.github.io]# cat /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/RedCloth-4.2.9/gem_make.out
/usr/bin/ruby2.1 extconf.rb
checking for main() in -lc... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--with-redcloth_scan-dir
	--without-redcloth_scan-dir
	--with-redcloth_scan-include
	--without-redcloth_scan-include=${redcloth_scan-dir}/include
	--with-redcloth_scan-lib
	--without-redcloth_scan-lib=${redcloth_scan-dir}/lib
	--with-clib
	--without-clib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
	from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
	from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
	from extconf.rb:5:in `<main>'

extconf failed, exit code 1
dwalton@laptop[ev3dev.github.io]# 

```

**Comment by dwalton76** [comment]
```
dwalton@laptop[ev3dev.github.io]# dpkg-query -W ruby-dev
ruby-dev	1:2.1.0.4ubuntu1
dwalton@laptop[ev3dev.github.io]# 
```

**Comment by dlech** [comment]
Does this help? http://stackoverflow.com/questions/29317640/gem-install-rails-fails-on-ubuntu

**Comment by dwalton76** [comment]
ok the list of packages suggested in that post didn't help but using kvm to install ruby did. I removed my existing ruby and ruby-dev packages and then installed via kvm:
https://rvm.io/rvm/install

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --ruby

I am not running

dwalton@laptop[ev3dev.github.io]# ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
dwalton@laptop[ev3dev.github.io]# 

Thanks!
