### ISSUE TITLE
NameError: name 'Warning' isn't defined

### ISSUE THREAD

**Issue by Allen-1216** [ev3dev/ev3dev#1537]
**Question**

I follow this download kociemba into ev3
```
$ sudo apt-get update
$ sudo apt-get install build-essential libffi-dev
$ cd ~/
$ git clone https://github.com/dwalton76/kociemba.git
$ cd ~/kociemba/kociemba/ckociemba/
$ make
$ sudo make install
```

**Background Information**
I am trying to kociemba algorithms because I want to build a rubik's cube solver robot

**Screenshots**

The terminal can run kociemba with the command

![image](https://user-images.githubusercontent.com/64456248/180993376-5d0427be-d0aa-4bff-96d4-68eb1641c7c7.png)

but
![image](https://user-images.githubusercontent.com/64456248/180997770-7da55a58-ae78-4f80-80f7-775d6edcf30c.png)
![image](https://user-images.githubusercontent.com/64456248/180997815-4f8b990e-666e-4611-abcd-cf344fbd677b.png)
![image](https://user-images.githubusercontent.com/64456248/180996059-ddd92299-699d-4e34-a13d-fe7b49de752c.png)

Error message

```
Traceback (most recent call last):
  File "/home/robot/ev3micropython_kociemba_test/main.py", line 9, in <module>
  File "/home/robot/ev3micropython_kociemba_test/kociemba/__init__.py", line 4, in <module>
NameError: name 'Warning' isn't defined
```
kociemba/__init__.py
![image](https://user-images.githubusercontent.com/64456248/180998571-a8be1e27-edaa-4f7a-8fc5-1acc7465024c.png)

Desktop :
 - OS: Window 11
 - Connection Type: USB
 - software: Visual Studio Code

Robot:
 - Device: EV3
 - Versions: ev3-micropython-v2.0

```
Image file:         ev3-micropython-v2.0.0-sd-card-image
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534AA73E
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
MicroPython is not Python, so unless `kociemba` was written specifically for MicroPython, it probably isn't going to work. You could try https://github.com/ev3dev/ev3dev-lang-python instead. Or you could fix all of the compatibility issues to make `kociemba` work with MicroPython.

**Comment by dlech** [comment]
Or you could possibly use `system()` in MicroPython to run `kociemba` as a command line tool and save the output to a file, then open the file in MicroPython.

**Comment by Allen-1216** [comment]
thank you for your help @dlech 
I solved the problem using `system()`
