### ISSUE TITLE
i2c sensor driver structure

### ISSUE THREAD

**Issue by Eisverygoodletter** [ev3dev/ev3dev#1540]
**Question**
From my understanding, information about the individual sensors are placed in [nxt_i2c_sensor_defs.c](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-buster/sensors/nxt_i2c_sensor_defs.c) , and the non-individual code that operates on this information is placed in  [nxt_i2c_sensor_core.c](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-buster/sensors/nxt_i2c_sensor_core.c) . Is this correct?

**Comment by dlech** [comment]
That is correct.
