### ISSUE TITLE
Reliable way to recalibrate ev3 gyro sensor

### ISSUE THREAD

**Issue by Eisverygoodletter** [ev3dev/ev3dev#1542]
**Question**
How do you reliably calibrate a gyro sensor?
**Background Information**
When I was searching around for a way to recalibrate the gyro sensor, I found https://github.com/ev3dev/ev3dev/issues/1387 and it seems like there is no reliable way to recalibrate it.

I found this later https://ev3lessons.com/en/ProgrammingLessons/advanced/GyroRevisited.pdf which mentions a way to reliably recalibrate the gyro sensor.
![image](https://user-images.githubusercontent.com/76079042/188626771-ab37aef3-1d06-40dd-9199-bd46b578e070.png)

It suggests that reading the gyro as an infrared sensor would work on the default EV3.

Is there a way to replicate this on ev3dev?

**Comment by Eisverygoodletter** [comment]
Recalibration strategies shown on the document shows how to do it in the default Ev3 software, but not in ev3dev (I'm trying to figure out how to do it in C++ with https://github.com/ddemidov/ev3dev-lang-cpp)

**Comment by dlech** [comment]
You can change the mode of the port to `other-uart` for a few hundred milliseconds (same effect as the IR sensor block) and then back to `auto` (same effect as the gyro block) and then wait for the sensor to re-sync to force the sensor to reset (same effect as the wait block).
