### ISSUE TITLE
Network error: Connection timed out!

### ISSUE THREAD

**Issue by pichenka007gd** [ev3dev/ev3dev#1599]
I'm trying to connect to ev3 via ssh

he should connect

It seems to connect via bluetooth but doesn’t want to connect via ssh from which device I wouldn’t try

**Desktop:**
 - OS and version: Window 7, android 10
 - Connection Type: Bluetooth
 - Software: PuTTY, ConnectBot

**Robot:**
 - Device: EV3
 - Versions: ev3dev-stretch-ev3-generic-2020-04-10.img

```
I can't connect ssh lol
```

Actually, I'm making a 2D printer for a competition, but damn, how do I connect this damn ssh

I really hope for more attention

**Comment by dlech** [comment]
Can you give the exact steps to reproduce the problem? All of the clicks, button presses, etc. Screen shots if possible.

**Comment by pichenka007gd** [comment]
I don't know. For example, I was just able to connect to it using a USB modem from my phone (ConnectBot)
and already from the PC via PuTTY I have a "timeout error"

**Comment by pichenka007gd** [comment]
here is my telegram:
@pichenka007gd

**Comment by pichenka007gd** [comment]
I'll try it now via Xshell

**Comment by pichenka007gd** [comment]
no, it's the same with Xshell

**Comment by pichenka007gd** [comment]
It connects through a tablet that distributes the Internet, but not through a PC.

**Comment by pichenka007gd** [comment]
![Screenshot_20231114_110537_org connectbot](https://github.com/ev3dev/ev3dev/assets/144206119/e1ef4565-e155-4276-9d98-55d158f8e3b8)
![Screenshot_20231114_110542_org connectbot](https://github.com/ev3dev/ev3dev/assets/144206119/c6872956-2846-401b-916f-dd8f57e3d5b8)
![Screenshot_20231114_110550_org connectbot](https://github.com/ev3dev/ev3dev/assets/144206119/79984f8b-aa07-4811-9e56-839310465e2f)
![Screenshot_20231114_110554_org connectbot](https://github.com/ev3dev/ev3dev/assets/144206119/f14ad503-e67e-478b-aa49-ad2e692d33ec)
![Screenshot_20231114_110603_org connectbot](https://github.com/ev3dev/ev3dev/assets/144206119/faf1b12a-4ab0-41fb-a239-53e5a1cfbe05)

**Comment by pichenka007gd** [comment]
I’ll explain in the 1st picture I enter the ip
in the second picture I turn on the checkbox for connection attempts (this is under the 1st enable checkbox)
on the rest it is written

connecting to ssh

The authenticity of the server cannot be established

server key fingerprint *****-*******************

want to continue trying to connect (yes)

key exchange algorithm: ******************

we use the algorithm: **********************************

trying to log in

attempt to log in using public keys from memory

trying to log in

attempt at "interactive keyboard" authorization

then I enter the password (maker)

and everything works

**Comment by pichenka007gd** [comment]
))) ssh 192.168.42.146
Connecting to 192.168.42.146:22...
Could not connect to '192.168.42.146' (port 22): Connection failed.
this is in Xshell

**Comment by pichenka007** [comment]
![Uploading img1.png…]()

**Comment by pichenka007gd** [comment]
![img1](https://github.com/ev3dev/ev3dev/assets/144206119/14afbf67-39fc-49e7-a9af-6617954a1d27)

**Comment by pichenka007gd** [comment]
![img1](https://github.com/ev3dev/ev3dev/assets/144206119/53e1839f-d611-4633-bc47-5901341a7bcd)

**Comment by pichenka007gd** [comment]
![img1](https://github.com/ev3dev/ev3dev/assets/144206119/c587ea96-14dc-49b8-a320-a7a2b70f60d9)

**Comment by pichenka007gd** [comment]
Well, this is in PuTTY

**Comment by pichenka007gd** [comment]
uh but that's bad, now in bluetooth and wifi it says "Not avaible
