### ISSUE TITLE
EV3 wont boot with sd card

### ISSUE THREAD

**Issue by AverageSugar** [ev3dev/ev3dev#1616]
I installed the image with etcher and followed all the steps but when i start my EV3 it just stayes red, even if i let it boot over night it just stayes red.

I use a Laptop with Windwows 11, my used file was the official one for lego education with micro python(ev3micropythonv200sdcardimage.zip) and i flashed it via etcher

Pls help!

**Comment by dlech** [comment]
Newer versions of Etcher are unfortunately broken. You can use an older version of Etcher or unzip the file first.
