### ISSUE TITLE
View USB flash drive or SD card in ssh

### ISSUE THREAD

**Issue by moonmantee** [ev3dev/ev3dev#1621]
How do I view a USB or SD card on EV3 after I have ssh'd into it? I'm trying to be able to use a USB drive to upload code to my ev3 without a wired connection.

This is a screenshot of the file directory in the ev3:
![image](https://github.com/ev3dev/ev3dev/assets/57419657/ef105823-ef34-47c8-b9a7-2380ff206939)

**Comment by dlech** [comment]
If it automatically mounts, I would expect it to be under `/media` (or maybe `/mnt`). Otherwise you may have to manually mount the file system.

**Comment by moonmantee** [comment]
Thank you I was able to see the sd card.
