### ISSUE TITLE
Setting the brickrun terminal to graphics mode

### ISSUE THREAD

**Issue by majohadev** [ev3dev/ev3dev#1643]
**Question**

If I understand correctly, executing a program with `brickrun` will open a virtual terminal - how would I set it to "graphics" mode in C++ code?  Is there any danger in doing so?

**Background Information**

I'm writing C++ code for the EV3 brick to experiment with drawing things on its LCD, and using its arrow buttons for interactivity.  When I run a program with `brickrun` and press the arrow buttons, I see that their keycodes are printed to the onscreen terminal - I'd like to keep the screen clear, without terminal output.

I've read a few other GitHub issues that ask about "controlling the screen" or something similar.  The common solution seems to be opening a virtual terminal and switching it to graphics mode - but those issues were written before `brickrun` was available, and the suggested way of opening a virtual terminal was with a terminal command over SSH (which I'd like to avoid).  Given how old those issues were, I figured I'd ask how this might work with `brickrun` now.

I do see the pseudocode in issue https://github.com/ev3dev/ev3dev/issues/260 that might work for me, but I want to check whether that's the right way to access the terminal used by `brickrun`.

---
Note:  At some point I'm interested in using GRX to draw shapes, which seems to be graphics-only (see https://github.com/ev3dev/ev3dev/issues/1480#issuecomment-812878360).  I wanted to see how far I could get without it - but if creating a graphics-only virtual terminal turns out to be tedious, I might go straight to GRX.

---

**Environment details:**
 - Windows 10, VS Code (with EV3 plugin), Docker container for cross-compiling C++ code
 - EV3 brick, connected by USB cable

```
========== ev3dev-sysinfo ==========
Image file:         ev3dev-stretch-ev3-generic-2020-04-10
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=001653483962
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
> I do see the pseudocode in issue #260 that might work for me, but I want to check whether that's the right way to access the terminal used by `brickrun`.

Yes, this is the right way. The nice thing about `brickrun` is that if your program crashes, it will still restore the terminal settings and you won't get stuck. (So do the `ioctl` stuff, but use `brickrun` instead of `sudo openvt`)

**Comment by majohadev** [comment]
Great, thank you for the quick response!

For future reference, this seems to work:
```
#include <fcntl.h>      // For open()
#include <sys/ioctl.h>  // For ioctl()
#include <linux/kd.h>   // For KDSETMODE and KD_GRAPHICS
#include <unistd.h>     // For close() (you might be able to open/close the file another way with only one header - I haven't checked)
int main()
{
    // Get the file descriptor for the virtual terminal (started when using 'brickrun' from SSH, or when running program from the brick)
    int virtualTerminalFile = open("/dev/tty", O_RDWR);

    // Set the virtual terminal to "graphics mode", to prevent terminal text from showing up on the screen
    ioctl(virtualTerminalFile, KDSETMODE, KD_GRAPHICS);
    
    // Close the file descriptor
    close(virtualTerminalFile);
    ...
    // Draw things on screen, etc.
    ...
    // We don't need to change back to "text mode" before quitting, since the terminal settings are always restored
    return 0;
}
```
