### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Project516** [ev3dev/ev3dev#1647]
Is it possible to make a up to date version of Ev3 dev with the newest packages? How would I do that? Since there’s a kernel for bookworm public could I include it too?

**Comment by dlech** [comment]
You will probably be interested in this discussion: https://github.com/orgs/ev3dev/discussions/1636

The bookworm branch of the kernel is not working and needs a lot of work to get working again.

**Comment by Project516** [comment]
Thanks a lot!
