### ISSUE TITLE
Can't set manual IP ADDRESS in BRICKMAN

### ISSUE THREAD

**Issue by MetallianFR68** [ev3dev/ev3dev#166]
Hi,

I just installed the new ev3dev-jessie-2014-10-07 image
The implementation of BRICKMAN is very useful
It's much easier to configure the wifi connection without having to connect via USB first
It's working "out of the box" when I select "USE DHCP"

But I noticed a bug when using "ENTER CUSTOM VALUES"
I can set the GATEWAY or the MASK
But it's impossible to set the IP ADDRESS
When I enter the field, I can't input anything. The virtual keyboard doesn't show up

Is there another way to set the IP ADDRESS manually ? By editing a conf file or something ?
Where does BRICKMAN store it's settings ?
I tried editing the /etc/network/interfaces manually but it seems that BRICKMAN doesn't like that

Bonus question: How to exit BRICKMAN ?
My current project uses the display driver to write some stuff on the screen.
It doesn't work anymore because BRICKMAN is running at boot.
Is there a way to exit Brickman and free the screen ?

**Comment by AnushRobotics** [comment]
We have problem in changing the IP address  static in Ev3dev.....please is anyone aware of this,tell us the step by step process and it is very urgent

**Comment by snaildos** [comment]
Bump ^o^,
I can't get static ip to work. This is *Very* important. I don't know what to do... Anyone? Please?
