### ISSUE TITLE
USB camera for EV3

### ISSUE THREAD

**Issue by sharived** [ev3dev/ev3dev#175]
Hi,
  I'm developing a USB camera to be used in a lego robotics environment.  I am currently running with a RaspberryPi and a BrickPi from Dexter Industries.  I'd like to get this working on an EV3 as well.  It seems like it should be pretty straight forward to use ev3dev (please let me know if there are any issues I should be aware of with USB - didn't see any references in the wiki), but would also like to use ev3 out of the box.  Do you know if anyone has successfully hooked up a USB device (such as a camera) to the ev3?  I'm new to EV3 and appreciate any pointers that can be provided.

Thanks,
Shari

**Comment by Odame** [comment]
@sharived Can you give me some heads up/tips on how to use the pixy camera with ev3dev over usb?
