### ISSUE TITLE
Cannot su to a different user in the brickstrap shell

### ISSUE THREAD

**Issue by aracanid** [ev3dev/ev3dev#177]
I'm not entirely sure why but I simply cannot change user to a normal user instead of root while in the brickstrap shell. I am constantly met with the error "initgroups: Operation not permitted".

I do apologise if this is something very trivial that I have missed, but I've been banging my head over this for a while now and just can't get it resolved.

Thanks in advance,

Justin

**Comment by dlech** [comment]
We are moving away from using proot in brickstrap, so this issue is no longer valid.
