### ISSUE TITLE
Try to enable USB and WIFI on boot without brickman on image 2014-10-07

### ISSUE THREAD

**Issue by cho934** [ev3dev/ev3dev#179]
Hello,

I tried to stop/disable brickman, then to use /etc/network/interfaces for wifi, then stop/disable connman, and reboot, but it's not working in this release.

Moreover, I can't have usb connection. I want to keep a safe and automatique ssh connection by usb if the wifi is not available. It was possible using the old release from may 2014.
Is it possible to retrieve the possibility to use ev3dev.rc.local like before this release (step 4: https://github.com/ev3dev/ev3dev/wiki/Getting-started-v2) ?

Best regards,

**Comment by dlech** [comment]
Is this still a problem?

**Comment by cho934** [comment]
Using last image, we can easily using commandctl for brickman and connman services.
We can also launch our C++ program directly from brickman.
So it is resolved for us.

**Comment by dlech** [comment]
> Just put this information in the wiki for beginners who don't know commandctl.

I've added #347 for this.
