### ISSUE TITLE
brickman networking screen stays "loading"

### ISSUE THREAD

**Issue by BertLindeman** [ev3dev/ev3dev#196]
Running 
`kernel 3.16.1-6`
`connman 1.26-0ev3dev4`
`brickman        0.1.2`

After a day with numerous wifi interuptions have set on debugging for connman.
Not sure if that is related.
Not sure if it's repeatable.
In brickman `enter` on `Networking` shows:
![ev3screen](https://cloud.githubusercontent.com/assets/8142081/4923321/629f9ebe-6519-11e4-9954-c81bf67eee64.png)
After a long time (diner was fine ;-) no change.
Notice NO IP-address on the top-line, but I **am** using a wifi connection at the moment.
Back-button still works. Press on enter produces the same screen as in the picture above.

`systemctl status brickman -l` shows

```
● brickman.service - Brick Manager
   Loaded: loaded (/lib/systemd/system/brickman.service; enabled)
   Active: active (running) since Wed 2014-11-05 18:04:27 CET; 1h 15min ago
 Main PID: 9514 (brickman)
   CGroup: /system.slice/brickman.service
           └─9514 /usr/sbin/brickman

Nov 05 18:04:26 ev3dev systemd[1]: Stopping Brick Manager...
Nov 05 18:04:27 ev3dev systemd[1]: Starting Brick Manager...
Nov 05 18:04:27 ev3dev systemd[1]: Started Brick Manager.
Nov 05 18:04:36 ev3dev brickman[9514]: ** (process:9514): CRITICAL **: file /tmp/buildd/brickman-0.1.3/lib/connman/Manager.vala: line 57: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.connman was not provided by any .service files (g-dbus-error-quark, 2)
```

In the meantime an hour and a half further, no change.
`journalctl --since "2014-11-05 18:01:50" --until "2014-11-05 18:04:00"`
Placed the log extract in [gistfile1](https://gist.github.com/BertLindeman/c72f6c4cbe4b48b6c80c#file-gistfile1-txt)

Saw a few times of brickman and connman stop/start. Maybe related?

Just to be sure doing a brickman restart by hand.
 `systemctl restart brickman.service`
**That** helps. But probably not very repeatable.

**Comment by topikachu** [comment]
Well, this problem happens at my device on the latest image
ev3dev-jessie-2015-05-01
brickman 0.6.0
