### ISSUE TITLE
Bluetooth audio with BlueZ 5

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#198]
This is the continuation of some discussion that started in #185.

Here is what I would like to see accomplished with this issue:
- [ ] Write a tutorial for Bluetooth audio (A2DP) with PulseAudio.
- [ ] See if we can get HSP/HFP using `ofono`.

I will update these items as they evolve.

New tutorials go [here](http://www.ev3dev.org/docs/tutorials/).
Old docs are [here](https://github.com/ev3dev/ev3dev/wiki/Using-Bluetooth).

**Comment by sup2069** [comment]
Sorry, I know this thread is close to a year old, but I feel the internet is here forever (to an extent) and new folks will find this thread in the future; why not add my findings here?

Anyhow, I managed to get a single bluetooth bass speaker connected. The added script for system.pa, the module failed to load. Found out by running 

Ran <code>pactl list modules | grep blue </code> to see if the module was installed then ran <code>pactl load-module module-bluetooth-discover</code> which loaded up fine. Connected the speaker from GUI didnt run it from <code>bluetoothctl</code>.

Connected succesfully, but no sound was coming through

Installed pulse audio control panel <code>pavucontrol</code> then forced the laptop speakers as other than speakers, put the bluetooth speaker in fallback mode, and set it to ad2p. Restart bluetooth (cant remember if I did this) refreshed youtube and KAPOW! Spent months trying to get this to work! Thanks all, mhopefully this helps others.

Other thread which helped:

https://github.com/blueman-project/blueman/issues/158

**Comment by rhempel** [comment]
Oh hey, that's GREAT news - can't wait to try it and set up proper instructions! Will mark as closed once a few more folks can confirm it's working.

**Comment by icemadsen** [comment]
Small note: 
I had to do `systemctl enable pulseaudio.service` in order to have the pulseaudio service to start during boot time. My EV3 can now connect to my bluetooth speaker and play soundfiles after startup without any need for command line interaktion! :-)

**Comment by Risto-Stevcev** [comment]
I can that what @sup2069 said works. I'm on Arch Linux. I first installed `bluez` and `bluez-utils` and started the `bluetooth.service`. I could pair the speaker through `bluetoothctl` but it wouldn't connect. Then I read in the wiki that I need `pulseaudio-bluetooth` for audio devices. After I got that I managed to connect the device, but no sound came out. Then I just started up `pavucontrol`, clicked the "Set as fallback" button for the bluetooth device, and then muting/unmuting the laptop speakers triggered it as a fallback and it started working :smile:

**Comment by jeff-54321** [comment]
Every thing seems to be connected, but im getting no audio and this error.  Is there something im missing?

`ALSA lib pulse.c:272:(pulse_connect) PulseAudio: Unable to connect: permission denied`

**Comment by dlech** [comment]
Closing in favor of #940

**Comment by PraneetKaur** [comment]
Hi,
Did anyone try getting bluez5 to work on openWRT for audio streaming using A2DP as source and sink?

**Comment by jmv2009** [comment]
PraneetKaur: Yes, got it working, to some extent. You have to rebuild openWRT.
Remove `--disabled-dbus` and add `+sbc +libdbus` after e.g. +alsa-lib in feeds/packages/sound/pulseaudio/Makefile

In `make menuconfig` make sure at least `pulseaudio-daemon` and `bluez-daemon` are going to be available (e.g. built in)
Do this after getting the source and feeds with git.


Furthermore, once on the OpenWRT system use 

```
<busconfig>
    <!-- ../system.conf have denied everything, so we just punch some holes -->
    <policy context="default">
        <allow own="org.pulseaudio.Server"/>
	<allow send_type="method_call"/>
	<allow send_type="method_return"/>
    </policy>

 </busconfig>
```


for pulseaudio.conf in /etc/dbus-1/system.d



and 

```
<busconfig>

  <!-- ../system.conf have denied everything, so we just punch some holes -->

  <policy user="root">
    <allow own="org.bluez"/>
    <allow send_type="method_call"/>
    <allow send_type="method_return"/>
  </policy>

  <policy at_console="true">
    <allow send_path="/"/>
    <allow send_path="/org/bluez"/>

    <allow send_destination="org.bluez.Manager"/>
    <allow receive_sender="org.bluez.Manager"/>

    <allow send_destination="org.bluez.Adapter"/>
    <allow receive_sender="org.bluez.Adapter"/>

    <allow send_destination="org.bluez.Device"/>
    <allow receive_sender="org.bluez.Device"/>

    <allow send_destination="org.bluez.Service"/>
    <allow receive_sender="org.bluez.Service"/>

    <allow send_destination="org.bluez.Database"/>
    <allow receive_sender="org.bluez.Database"/>

    <allow send_destination="org.bluez.Security"/>
    <allow receive_sender="org.bluez.Security"/>
  </policy>

</busconfig>
```
for bluetooth.conf in /etc/dbus-1/system.d

add
```
load-module module-bluez5-discover
load-module module-bluetooth-policy
```
to /etc/pulse/system.pa

remove
`--disable-module-loading`
from
/etc/init.d/pulseaudio

For avahi/zeroconf,
remove `--disable-avahi` , and add `+libavahi-client` to the DEPENDS in the pulseaudio Makefile
and add `load-module module-zeroconf-publish` to /etc/pulse/system.pa on the openwrt system.

After modification of /etc/pulse/system.pa issue `service pulseaudio restart`

It's not working as well as on kali linux. Both run Bluez 5.47 and pulseaudio 11.1. But Openwrt only works as a a2dp sink when connecting from windows upon pairing.

Run bluetoothctl, and issue
```
power on
discoverable on
```
connect from windows
`trust XX:XX:XX:XX:XX:XX`
disconnect from windows
connect from windows
once you get "Connected music" you're golden. You can set the discoverable time in /etc/bluetooth/main.conf

Things may depend a bit on the bluetooth version for the pairing. In my case, when doing it this way no pin or other authentication was required. Note: pulseaudio/bluez do not suspend the stream when there is no audio. So if you have had some loss of packets, the audio stream may get interrupted and delayed, and you pretty much need to remove the device to resync.

I'm trying to figure out why I don't get Connected Music when reconnecting without repairing. The output from `bluetoothd -n -d` after `service bluetoothd stop` should give this information, but I haven't deciphered it. Anybody?

**Comment by jmv2009** [comment]
I think if the commit at
https://github.com/openwrt/packages/commit/4b1fad86f85bed0d867324c21d7e4a75d9957bfc is reversed, bluetooth would work.

**Comment by jmv2009** [comment]
or use 
```
<busconfig>

  <!-- System-wide PulseAudio runs as 'pulse' user. This fragment is
       not necessary for user PulseAudio instances. -->

  <policy user="pulse">
    <allow own="org.pulseaudio.Server"/>
  </policy>

</busconfig>
```
for pulsaudio-system.conf from the pulseaudio source??
