### ISSUE TITLE
Missing [Visible] and [Start Scan] on brickman 0.2.0 after bluetooth restart

### ISSUE THREAD

**Issue by BertLindeman** [ev3dev/ev3dev#201]
While looking at brickman `Bluetooth` screen did a `systemctl restart bluetooth.service`
Screen after the restart shows:

![ev3screen](https://cloud.githubusercontent.com/assets/8142081/5043578/3e71173c-6be7-11e4-837a-82bf97957619.png)

After `systemctl restart brickman.service` and tabbing to the Bluetooth screen again, the screen shows:
![ev3screen](https://cloud.githubusercontent.com/assets/8142081/5043667/c2d3a86e-6be7-11e4-85d8-24481f9e6289.png)

**Comment by dlech** [comment]
Fix released in brickman v0.3.0

**Comment by BertLindeman** [comment]
Thanks David,
Confirmed: problem gone now.
