### ISSUE TITLE
Brickman "dup" bluetooth devices if more than one BT-controller

### ISSUE THREAD

**Issue by BertLindeman** [ev3dev/ev3dev#202]
No problem issue but rather an enhancement I think.

Situation: More than one BT-controller is used in the EV.
This control level is not shown on brickman.
So it looks like duplicate BT-devices are present.
![ev3screen](https://cloud.githubusercontent.com/assets/8142081/5057149/ade25c0e-6cad-11e4-9e0e-3f94d03051ff.png)

`connmanctl services` also shows the controller-id:
```
    Ivoor                bluetooth_0017E7BCF2C1_0808C26228D6
    Ivoor                bluetooth_0015832A8FB2_0808C26228D6
    MUMBA                bluetooth_0017E7BCF2C1_B4749FD151A1
    MUMBA                bluetooth_0015832A8FB2_B4749FD151A1
```
But there is not enough real-estate on the EV3 screen.

Maybe something for the far future....

**Comment by dlech** [comment]
This just popped into my head. I think a good solution here would be if there is more than one Bluetooth adapter present, then append the adapter name, in parenthesis, to the device name so that you can tell the devices apart in brickman.

**Comment by BertLindeman** [comment]
Simple and effective I'd say. 
But I am a bit confused by the difference  in field names in `bluetoothctl` and `hciconfig`

In `bluetoothctl` what is called `alias` is named `name` in `hciconfig`

`bluetoothctl show xx:xx:xx:xx:xx:xx`

```
Controller xx:xx:xx:xx:xx:xx
        Name: Bert's EV3
        Alias: BT EV3 internal
        Class: 0x200000
        Powered: yes
        Discoverable: no
        Pairable: yes
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0517
        Discovering: no
```

`hciconfig -a`

```
hci0:   Type: BR/EDR  Bus: UART
        BD Address: xx:xx:xx:xx:xx:xx  ACL MTU: 1021:4  SCO MTU: 180:4
        UP RUNNING PSCAN
        RX bytes:1689753 acl:12507 sco:0 events:1456 errors:0
        TX bytes:650076 acl:1379 sco:0 commands:68 errors:0
        Features: 0xff 0xff 0x2d 0xfe 0x9b 0xff 0x79 0x83
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF PARK
        Link mode: SLAVE ACCEPT
        Name: 'BT EV3 internal'
        Class: 0x200000
        Service Classes: Audio
        Device Class: Miscellaneous,
        HCI Version: 2.1 (0x4)  Revision: 0x0
        LMP Version: 2.1 (0x4)  Subversion: 0x191f
        Manufacturer: Texas Instruments Inc. (13)
```

The `alias` is in `/var/lib/bluetooth/*/settings`
The `name` I am ashamed cannot find how I changed that :-(

Either can be used I think.

**Comment by dlech** [comment]
`name` is "immutable" - at least from `bluetootctl`. You can probably change it using `/etc/bluetooth/main.conf`by setting `Name = whatever-you-want`., but by default, it is the (network) hostname if your EV3. From a UI point of view though, we just use `alias` and not `name`, which it looks like this is what `hciconfig` is doing. [Here are the docs.](https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/adapter-api.txt) [Devices are similar to adapters in this regard.](https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/device-api.txt)

**Comment by BertLindeman** [comment]
Thanks David.

**Comment by dlech** [comment]
In brickman v0.6.0, the device list will show the adapter name in parentheses after the device name.
