### ISSUE TITLE
ev3dev wifi connection to edimax timeout?

### ISSUE THREAD

**Issue by alanwilter** [ev3dev/ev3dev#204]
I got my Edimax to work with ev3dev and all starts automatically with DHCP, very nicely. The issue I face now is if I leave my ev3dev idle for like 2 min, I can't connect anymore or, if I am connected, I cannot issue commands via terminal any longer.

I guess there may be some kind of power saving management or the like, but I am wondering if there's a kind of timeout or the behaviour I am seeing should not be expected at all?

**Comment by ensonic** [comment]
I think there are still issues. I am not even half through with entering the wifi password when I get this error:
https://drive.google.com/file/d/1TwPluL6EDOQoMjiu9SxAZPOivw7u2cafvw/view?usp=sharing
You get the same error, if you cancel.

I've tried several times to enter the pasword, but I get the timeout error after ~ 2 min.
https://drive.google.com/file/d/1GRb4Rx7EtbG5UOWNzHLptNj-ViQj7WWXcQ/view?usp=sharing
Why is there a timeout after all. Can't we just give the user all the time in the world to enter the password?

Also why does the connect dialog not show the previously entered password, then the user could fix a typo if there was one or continue entering the password.

**Comment by dlech** [comment]
@ensonic, you are looking for issue #328. This is a totally different issue here.
