### ISSUE TITLE
ev3 control via bluetooth

### ISSUE THREAD

**Issue by bdubbs** [ev3dev/ev3dev#206]
I've been exploring ev3 and like it.  I can connect via usb or wifi and build control programs. However I would also like to have the capability of controlling the ev3 without a wired connection or a wireless access point.  Is there some wireless way to communicate from a laptop directly to the ev3?  My first thought is via a console that uses bluetooth much as the way ssh uses IP for connectivity.  Does such a thing exist?

**Comment by ameysutavani** [comment]
Have a look at this:
http://www.pabr.org/bricks/brickfpv/brickfpv.en.html
