### ISSUE TITLE
No "Wired" connection on brickman after reboot for upgrade to kernel v3.16.1-7-ev3dev

### ISSUE THREAD

**Issue by BertLindeman** [ev3dev/ev3dev#214]
Reboot was done with the usb-cable connected. Had no problem with that before.
**Circumvention** for now after boot: unplug USB-cable - wait a bit - re-plug USB-cable.
Result in `dmesg`

```
[ 4494.642644] g_ether gadget: high-speed config #2: RNDIS
```

Now the `Wired` option is back... :-) 
And it can be connected again.

### Below this the debugging I did:

On brickman in `Network Connections` there is no `Wired` option, so cannot activate the USB connection to the EV3.

`Gadget` is enabled (was already after boot):
![ev3screen](https://cloud.githubusercontent.com/assets/8142081/5180978/2a27addc-7492-11e4-92a5-08696c460522.png)

RNDIS is active:
![ev3screen](https://cloud.githubusercontent.com/assets/8142081/5181052/f2e863ba-7492-11e4-8d52-36d21995734a.png)

In connmanctl Gadget **is** powered-on:
```
/net/connman/technology/gadget
  Name = Gadget
  Type = gadget
  Powered = True
  Connected = False
  Tethering = False
```

But **no** gadget entry in `connmanctl services`

```
~# dmesg|grep -i gadg
[   61.699123] g_ether gadget: Ethernet Gadget, version: Memorial Day 2008
[   61.699165] g_ether gadget: g_ether ready
```

According to `ifconfig usb0` usb **is** UP:

```
usb0      Link encap:Ethernet  HWaddr 02:16:53:3d:f2:5e
          UP BROADCAST MULTICAST DYNAMIC  MTU:1500  Metric:1
```
connman service is OK:

```
# systemctl status connman.service
● connman.service - Connection service
   Loaded: loaded (/lib/systemd/system/connman.service; enabled)
   Active: active (running) since Tue 2014-11-25 10:04:57 CET; 1h 6min ago
 Main PID: 424 (connmand)
   CGroup: /system.slice/connman.service
           └─424 /usr/sbin/connmand -n

Nov 25 10:17:05 ev3dev connmand[424]: wlan0 {newlink} index 2 address 80:1F:02:F2:F9:D0 mtu 1500
Nov 25 10:17:05 ev3dev connmand[424]: wlan0 {newlink} index 2 operstate 6 <UP>
Nov 25 10:17:11 ev3dev connmand[424]: Setting domainname to lan
Nov 25 10:17:11 ev3dev connmand[424]: wlan0 {add} address 192.168.2.16/24 label wlan0 family 2
Nov 25 10:17:11 ev3dev connmand[424]: wlan0 {add} route 192.168.2.0 gw 0.0.0.0 scope 253 <LINK>
Nov 25 10:17:11 ev3dev connmand[424]: wlan0 {add} route 192.168.2.254 gw 0.0.0.0 scope 253 <LINK>
Nov 25 10:17:11 ev3dev connmand[424]: wlan0 {add} route 0.0.0.0 gw 192.168.2.254 scope 0 <UNIVERSE>
Nov 25 10:17:16 ev3dev connmand[424]: wlan0 {add} route 87.106.208.187 gw 192.168.2.254 scope 0 <UNIVERSE>
Nov 25 10:17:16 ev3dev connmand[424]: wlan0 {del} route 87.106.208.187 gw 192.168.2.254 scope 0 <UNIVERSE>
Nov 25 10:20:07 ev3dev connmand[424]: wlan0 {del} route 192.168.2.254 gw 0.0.0.0 scope 253 <LINK>

```

Unplug/replug the USB-cable to to be able to enable USB ethernet.

**Comment by dlech** [comment]
I have changed some boot order dependencies in the latest release (ev3-ev3dev-2015-05-20). It is possible it may help with this issue.

**Comment by BertLindeman** [comment]
Closing as I no longer run this level and no one else reported here.
