### ISSUE TITLE
sysfs group permissions created too late

### ISSUE THREAD

**Issue by jdchristensen** [ev3dev/ev3dev#225]
If I do 

    cd /sys/class/leds/ev3:green:left
    echo timer > trigger
    ls -l delay_on
    ls -l delay_on

I get the output

    -rw-r--r-- 1 root root 4096 Dec 13 19:39 delay_on
    -rw-rw-r-- 1 root ev3dev 4096 Dec 13 19:39 delay_on

So there's a short period where the new file exists but has the wrong group permissions.  And unfortunately, the python-ev3 package is fast enough that it seems to consistently have a problem with this, when run as a non-root user in the ev3dev group:

    led.right.blink(color=LED.COLOR.GREEN, delay_on=1000, delay_off=1000)

gives a permission denied error when writing to the file delay_on.

Is it possible for the write to the trigger file to block until any new files have been created and set-up properly?

**Comment by dlech** [comment]
closing this since it is "wontfix"
