### ISSUE TITLE
USB 2.0 Host support ?

### ISSUE THREAD

**Issue by pabr** [ev3dev/ev3dev#230]
As @dlech mentioned in [issue 43](https://github.com/ev3dev/ev3dev/issues/43), the mini-USB port of the EV3 is OTG capable as far as the AM1808 is concerned.

In principle OTG requires a mini-AB receptacle, but there are OTG cables on the market with a Type-A receptacle at one end and a mini-B plug with grounded ID at the other end.

Hopefully the only thing that prevents the mini-B port from acting as a USB 2.0 Host is that the EV3 lacks circuitry to drive VBUS to +5V when the USB0_DRVVBUS pin toggles. As a workaround I intend to supply +5V externally (e.g. by picking VBUS from the USB 1.1 port). I don't think using a powered USB hub would suffice because (1) the AM1808 probably monitors VBUS to detect overcurrent, and (2) the hub probably needs to see +5V before it will enumerate.

From what I read in TI forums it is important to switch the port to Host mode before driving VBUS, otherwise the MUSB logic may decide that it is already connected as a B-device from a previous session, and refuse to switch to host mode.

What I have tried so far is:

Starting with ev3dev-jessie-2014-12-01.img
Recompile linux 3.16.1-8-ev3dev-pre with:

```
CONFIG_USB_MUSB_HDRC=m
CONFIG_USB_MUSB_HOST=y
# CONFIG_USB_MUSB_GADGET is not set
# CONFIG_USB_MUSB_DUAL_ROLE is not set
CONFIG_USB_MUSB_DA8XX=m
```

(I am saving dual-role support for later)

```
echo on > /sys/devices/platform/musb-da8xx/musb-hdrc.1.auto/power/control
cat /sys/devices/platform/musb-da8xx/musb-hdrc.1.auto/mode
cat /sys/devices/platform/musb-da8xx/musb-hdrc.1.auto/vbus
echo 1 > /sys/devices/platform/musb-da8xx/musb-hdrc.1.auto/srp
echo "force host" > /sys/kernel/debug/musb-hdrc.1.auto/testmode
cat /sys/kernel/debug/musb-hdrc.1.auto/regdump
```

... while plugging/unplugging the OTG cable and connecting/disconnecting VBUS to/from  +5V, in various sequences.

The "force host" trick does change musb-hdrc.1.auto/mode from "b_idle" to "a_idle". But musb-hdrc.1.auto/vbus always reads "Vbus off", which suggests the chip is not detecting my +5V. Next I will have to disassemble my EV3 to check for activity on USB0_DRVVBUS. Maybe the pin definitions in arch/arm/mach-davinci/board-legoev3.h need to be patched.

Any help is welcome.

**Comment by pabr** [comment]
I now have USB 2.0 Host partially working with CPPI 4.1 DMA on EV3 with linux-3.16.1-8-ev3dev-pre.

The work-in-progress patch is [here](http://www.pabr.org/tmp/ev3usb2host/20150102-dt-workaround-cppi41-am1808.patch).

Most of it is trivial stuff:
* Quick-and-dirty temporary workarounds for the missing DT support:
  * A dummy platform_device in board-legoev3.c to bind drivers/dma/cppi41.c
  * Hardcoded DT property lookups in drivers/dma/cppi41.c and drivers/usb/musb/musb_cppi41.c.
* Kconfig changes to allow USB_TI_CPPI41_DMA instead of MUSB_PIO_ONLY.
* Kconfig changes to allow drivers/dma/cppi41.c to be compiled as a module (useful for debugging).

The salient parts are:
* Replacing __iowmb() with wmb() and __iormb() with rmb() in drivers/dma/cppi41.c.
  Otherwise DMA interrupts never fire and USB transactions time out after 20 seconds.
  It looks like IO memory is less coherent than the driver (or Linux) expects on AM1808.
  Either that, or I broke things somewhere else.
* Customising drivers/dma/cppi41.c for AM1808. Despite being written for DT, it has AM33xx-specific interrupt handling and CPPI constants.
* There is also the "angelo" fix for re-plugging USB devices (disabled).

Performance is a bit disppointing. Maybe the driver does not take full advantage of the hardware yet.
```
|                        | USB 1.1  | USB 2.0 PIO | USB 2.0 DMA |
|------------------------+----------+-------------+-------------|
| USB storage [1]        | 1 MB/s   | 6 MB/s      | 10 MB/s     |
| WiFi (Ralink RT5370)   | 0.5 MB/s | 0.5 MB/s    | NA [2]      |
| Webcam (Logitech C170) | TBD      | NA [3]      | NA [3]      |
```

[1] Reading from a microSD card which achieves 17 MB/s on a PC.
[2] WiFi is unstable under high load (but ssh works).
[3] V4L2 fails with EMSGSIZE, [possibly because the MUSB driver does not fully implement High-Speed High-Bandwidth transfers](http://lists.scusting.com/index.php?t=msg&goto=1786492).

**Comment by dlech** [comment]
I found this in `arch/arm/include/asm/io.h`:

```
/* IO barriers */
#ifdef CONFIG_ARM_DMA_MEM_BUFFERABLE
#include <asm/barrier.h>
#define __iormb()		rmb()
#define __iowmb()		wmb()
#else
#define __iormb()		do { } while (0)
#define __iowmb()		do { } while (0)
#endif
```

So it looks like you just need to enable `ARM_DMA_MEM_BUFFERABLE` in the kernel config.

**Comment by dlech** [comment]
I was actually thinking about this last night and wondering if you were still working on the of if you gave up, so thanks for the update. I am glad that you are still making progress.

It sounds like to really take full advantage of this, we will need the patch (or similar) that you linked in [3].

**Comment by pabr** [comment]
@dlech: Sorry for the delay, I had to dig deeper into the AM1808 documentation than I expected. Also, I should stop compiling kernels natively on the EV3 as you already suggested :-)

About memory barriers: Yes, CONFIG_ARM_DMA_MEM_BUFFERABLE would do the trick, but I find it hard to believe that both TI and the linux-arm-kernel developers forgot to enable it by default on AM18xx if the hardware really requires it. So it is worth investigating further.

About video4linux: Webcams (and Kinect-like sensors) were my main motivation for working on USB 2.0. So yes, fixing the EMSGSIZE issue is definitely a priority.

**Comment by pabr** [comment]
The MUSB silicon in the AM1808 does not support high-bandwidth isochronous transfers. This can be seen when the driver decodes the CONFIGDATA register: Flags "HB-ISO Rx" and "HB-ISO Tx" are missing.
```
musb-hdrc: ConfigData=0x06 (UTMI-8, dyn FIFOs, SoftConn)
```

But I was able to capture up to 2.2 MB/s from a Logitech C170 by forcing uvcvideo to select a USB altsetting with non-HB packets (wMaxPacketSize=1x1024). This is in PIO mode with 90% CPU utilization; DMA mode is unreliable.

I can also stream MJPEG video from a C170 on USB2.0 to an ethernet adapter on USB1.1: 640x480 at about 13 fps, 320x240 at about 27 fps.

**Comment by dlech** [comment]
Oh no! I thought for sure we had something really amazing going here. It's a major bummer that the hardware just won't support it.

**Comment by G33kDude** [comment]
I've had limited success in using mjpeg-streamer on my EV3 using a webcam and Wi-Fi dongle on the usb port on the side of the bot. For some reason (I assume it's some kind of limitation of the USB 1.0 support in the webcam), mjpeg-streamer will only let me stream at a ridiculously small size (172x144 or something like that), but it gets the point across well enough for my purpose. I've also installed nginx and php such that I can remotely operate the EV3 through a web interface, and have nginx reverse-proxy the webcam so everything is accessible through port 80. The result is a fairly fun to drive battery powered webcam streaming rover.

**Comment by pabr** [comment]
@G33kDude: It looks like video remote control is everyone's favority application :-) I used to stream over Bluetooth to reduce the load on the USB 1.1 port:
http://www.pabr.org/bricks/brickfpv/brickfpv.en.html

With a webcam and a WiFi dongle on a hub you might be experiencing well known problems, i.e. webcams tend to request more bandwidth than they actually need. For uncompressed modes "modprobe uvcvideo quirks=128" may help. For MJPEG you may need to patch ev3dev-kernel/drivers/media/usb/uvc/uvc_video.c as suggested at the end of this discussion:
http://stackoverflow.com/questions/9781770/capturing-multiple-webcams-uvcvideo-with-opencv-on-linux

My RT5370 WiFi dongle apparently cannot stream more than 0.5 MB/s, even on the USB2.0 port. This is limited by CPU usage, not by USB bandwidth. Tests with usb-storage show that 6 MB/s is possible, even in PIO mode. Maybe someone can recommend a WiFi dongle with a more efficient Linux driver ? Otherwise, as far as video streaming applications are concerned, I  see no point in trying to improve webcam bandwidth further.

Another motivation for USB2.0 support was Kinect: Imagine maze-navigating and brick-sorting EV3 robots with depth-sensing cameras... My ASUS Xtion (Kinect-like sensor) does enumerate on the EV3 but unfortunately it requires high-bandwidth packets on all altsettings.

**Comment by dlech** [comment]
I saw that there sas and off-by-one fix in musb in the 3.16.7-ckt6  kernel changelog, just FYI. Don't know if it is related to DMA or not, but if it is, it may be worth revisiting this.

**Comment by dlech** [comment]
A couple of updates here. The EV3 kernel will have proper device tree support starting with v4.9. Also, there is a setting to adjust the max packet size I have discovered that could help improve the bandwidth some. https://github.com/ev3dev/ev3-kernel/commit/9ec76c1fcd15cdaf9d08a96b58aaee39e79c0d10

**Comment by dlech** [comment]
More updates: Someone is working on getting cppi41 working with da8xx in the mainline kernel.

https://patchwork.kernel.org/project/linux-omap/list/?submitter=170841

**Comment by dlech** [comment]
It is hard to find all of his patches in one place.

https://patchwork.kernel.org/project/linux-dmaengine/list/?submitter=170841

**Comment by dlech** [comment]
It looks like all of the mainline patches have make it though and the CPPI 4.1 DMA is enabled by default in the mainline kernel. It did see a comment that said that it is just flaky in general. Some device work and some don't.

So, I guess I'll go ahead and close this issue. Whenever we upgrade to kernel v4.12 or higher, all the pieces should be in place where anyone can enable host mode from userspace and see what they can do with it.
