### ISSUE TITLE
Help building brickman

### ISSUE THREAD

**Issue by sharived** [ev3dev/ev3dev#232]
I'm trying to follow the directions on https://github.com/ev3dev/brickman but I think I'm missing something.  I've successfully built brickstrap, but when I try doing apt-get build-dep brickman I get the error "You must put some 'source' URIs in your sources.list."

I wasn't sure what was needed for the step - "Install the build-deps in debian/control" so perhaps this is my problem.  Would appreciate some help.

BTW, the reason I want to build brickman is because I'd like to add my menus to the GUI for my application.  Let me know if I'm not heading in the right direction.

**Comment by sharived** [comment]
Finally getting back to this.  So here's my idea for the lite version of bluetooth setup.

I'd like a top level option called "Bluetooth network"
Once selected it would automatically scan for available devices.  Listing most recently used devices first.
When select a device, if it has already been paired just use it.  If it hasn't been paired then initiate pairing automatically and start using it.

What do you think?  Let me know if you need a better explanation or something more graphical.  I'm not sure how this fits in with the rest of the lite version or if this could just be used with the current version.

**Comment by dlech** [comment]
For your use case, assuming that networking is the *only* thing you ever use Bluetooth for, then I guess this would be OK. For the general user though, it is too specialized.

Have you tried connecting by enabling tethering on bluetooth on the EV3? this is by far the easiest way (except for the fact that there is no UI for enabling tethering on the EV3 yet). The only downside is that the EV3 cannot connect to the Internet using tethering. Another plus to this method is that you will be able to connect to more host devices (basically anything that can use a smartphone bluetooth tether)

The flow would go something like this:

1. Make sure bluetooth is power on on the EV3.
2. Enable tethering via bluetooth on the EV3. (For now, run `connmanctl` then `tether bluetooth on`. It will give an error message that it is in progress. This seems to be a bug, so just ignore it.)
3. Pair the EV3 to the host computer. This can be initiated either from the EV3 or the host computer.
4. On the host computer
    * Windows 7: Open Bluetooth devices, select the EV3 and click "Connect using Access Point".
    * Linux: Open bluetooth settings and check the box that says "Use your mobile phone as a network device".

That's it. The EV3 is always at 192.168.1.1.

**Comment by sharived** [comment]
I am communicating to the Ev3 via snap! so I probably need internet, but I thought I'd try it and see.   I tried following the directions above, but I must be misunderstanding something.
Here's what I did.
My bluetooth is "on" on the Ev3.  I used my "wired" connection to ssh into Ev3 to run conmanctrl - not sure if there is another way.
I deleted the old pairing I had with my Mac and then paired it again to the Ev3.
I tried ssh'ing with 192.168.1.1, but nothing there.  I then went back and connected via bluetooth the "old" way and I could ssh into my 192.168.2.3 address.

When you say - EV3 is always at 192.168.1.1 - is this on power up of the Ev3?

**Comment by dlech** [comment]
I forgot you were on Mac, so I didn't try that before. Unfortunately, there seems to be problems with Mac - at least on 10.10. (I've tested and it works fine with Windows, Linux and Android).

So, to recap:
* Enable tethering on the EV3. I found you can to this in a single command. `connmanctl tether bluetooth on`.
*   Repair the EV3 with the Mac. 
*   Now, in the Mac Bluetooth tray icon, there is a "Connect to Network" option for the EV3.
    ![screenshot_1_12_15__12_20_pm](https://cloud.githubusercontent.com/assets/963645/5708423/66ffc7b4-9a56-11e4-9f05-981a72b29e77.png)
    
    Alternately, you can connect via network preferences.
    ![network_and_mac_bluetooth_pan_won_t_stay_connected_-_google_search](https://cloud.githubusercontent.com/assets/963645/5708442/815d0c16-9a56-11e4-8819-63692df6b564.png)

Now, here is where the problems start. For some reason my EV3 was not automatically setting the new connection as trusted, so there is a possible bug in brickman. When I tried to connect, a dialog popped up on the EV3 asking me if I wanted to allow the connection. You can select "Accept" and it will proceed, but this will continue to pop up every time you connect. To fix this, I had to use `bluetoothctl` on the EV3 to set the connection as trusted.

That wasn't so bad, but after connecting everything looks good, then a few seconds later, it just disconnects itself. I'm not seeing anything obvious in the error logs, so I have not got to the bottom of it yet.

If you haven't upgraded to OS X 10.10 yet, it would be worth trying with an older OS version to see if the behavior is different.

**Comment by sharived** [comment]
I'm using 10.9.5 - I'm still having issues though.

I enabled tethering using my "wired" connection.
Re-paired my ev3dev from my host.
But I don't see the ev3dev on the bluetooth option (from the tray)
![screen shot 2015-01-12 at 1 14 41 pm](https://cloud.githubusercontent.com/assets/1163591/5711171/357cdce8-9a5d-11e4-8580-ac931ce53319.png)

If I connect via bluetooth the "old" way I can only disconnect
![screen shot 2015-01-12 at 1 18 11 pm](https://cloud.githubusercontent.com/assets/1163591/5711202/7f22e8e2-9a5d-11e4-93d1-8d8822866980.png)

Here's my network screen if I don't connect via bluetooth and I unplug my wire
![screen shot 2015-01-12 at 1 23 47 pm](https://cloud.githubusercontent.com/assets/1163591/5711317/45a34b60-9a5e-11e4-8479-0b3b2c1ff60b.png)

Here's what my network screen says when I'm connected the "old way"
![screen shot 2015-01-12 at 1 19 36 pm](https://cloud.githubusercontent.com/assets/1163591/5711237/be7c0c58-9a5d-11e4-8a1e-56669547bef3.png)

Do I not have PAN set up correctly?

**Comment by dlech** [comment]
> I enabled tethering using my "wired" connection.

No. You need to enable tethering on the Bluetooth connection. `connmanctl tether bluetooth on`.

**Comment by sharived** [comment]
How do I enter the "connmanctl" command?  I am ssh'ing via my wired connection to enter the command.  Or are you saying I use the "old" bluetooth connection to run the command?

**Comment by dlech** [comment]
Use your wired connection for ssh like you said.

**Comment by sharived** [comment]
So does it seem like I'm missing something with my PAN setup then?

**Comment by dlech** [comment]
If bluetooth tethering was not turned on when you paired, then you need to repair for the Mac to see the new service. I haven't figured out a way for the Mac to re-enumerate bluetooth services otherwise.

**Comment by sharived** [comment]
I had turned on bluetooth tethering before I paired...  I have a window's machine I can try it on.  I'll do that next.

**Comment by dlech** [comment]
One thing I forgot to mention is that Mac also seems to be picky about the Bluetooth device class. You can change the device class by editing `/etc/bluetooth/main.conf`. Find the line

    #Class = 0x000100

And delete the '#' to uncomment the line. Then restart bluetooth.

    systemctl restart bluetooth

And repair *again*. The EV3 will now tell what it is connecting to that it is a "Computer".

**Comment by sharived** [comment]
Didn't seem to help, other than now I lost the options in the Ev3 bluetooth menu to make it visible (I had to do it with bluetoothctl) and scan for devices.  I'll try windows.

**Comment by dlech** [comment]
You must be using an older version of brickman. If fixed that bug. Restarting brickman should bring them back. `systemctl restart brickman`.

**Comment by sharived** [comment]
I had been using brickman v0.2.0 - I just upgraded to v0.3.0  - now my "visible" option is visible again on the bluetooth menu, but everything else is happening the same.

Another thing to note is that after I pair the ev3 is not connected via bluetooth - the only way for me to see if from the mac bluetooth screen is to manually connect again.  Not sure if this is what I was supposed to be doing.

I'll try again on my windows 8 machine.

**Comment by sharived** [comment]
I finally got the ev3 paired on my windows 8.1 machine, but I can't figure out how to do the next step.  
Windows 7: Open Bluetooth devices, select the EV3 and click "Connect using Access Point".

Do you know where this is on windows 8.1?

**Comment by dlech** [comment]
Double-click the bluetooth icon in the taskbar.

**Comment by dlech** [comment]
Hmm. It's a bit different...

**Comment by sharived** [comment]
I had done that.  Here is the screen I get when I select "Show Bluetooth Devices".   I can only remove the Ev3 it seems.

![image](https://cloud.githubusercontent.com/assets/1163591/5727011/bc4bc9ac-9b14-11e4-84ca-093b6c03dba7.png)

**Comment by dlech** [comment]
Try right-clicking the bluetooth icon in the taskbar and selecting "Join a Personal Area Network".
![selection_030](https://cloud.githubusercontent.com/assets/963645/5727108/345dae7c-9b26-11e4-85f5-6f4de8a6c0f1.png)

**Comment by dlech** [comment]
![selection_031](https://cloud.githubusercontent.com/assets/963645/5727275/627f7776-9b27-11e4-8134-30b128f8fff5.png)

**Comment by dlech** [comment]
![selection_033](https://cloud.githubusercontent.com/assets/963645/5727328/dd56497a-9b27-11e4-8ad7-246155ca5cbf.png)

Double-click the connection (highlighted in blue).

![selection_034](https://cloud.githubusercontent.com/assets/963645/5727351/01c02402-9b28-11e4-9d0b-10f58b8a98fd.png)

Select "Details..."

![selection_035](https://cloud.githubusercontent.com/assets/963645/5727369/28630f7a-9b28-11e4-9e58-dbd05be716f4.png)

The IP address of your EV3 is the once circled.

**Comment by sharived** [comment]
Finally got it paired again, but I'm not seeing the options you have.  
Showing I'm connected
![image](https://cloud.githubusercontent.com/assets/1163591/5731660/143c1fe2-9b3b-11e4-8cf2-54810ba5bf8f.png)

but I don't get a device listed here
![image](https://cloud.githubusercontent.com/assets/1163591/5731676/49daa236-9b3b-11e4-9b36-5a9e49586ccc.png)

and it doesn't show that I'm connected
![image](https://cloud.githubusercontent.com/assets/1163591/5731670/2ff7da14-9b3b-11e4-8e00-21079472652d.png)

It's seems like I am missing some bluetooth setup on my ev3

**Comment by dlech** [comment]
If you right-click on the Bluetooth Network Connection (last image) can you tell it to connect?

**Comment by dlech** [comment]
Although the fact that you did not see the "Connect to Network" option on Mac and you are not seeing the connection on Windows too tells me something is not right on the EV3 itself.

**Comment by dlech** [comment]
For example, I for got to turn on bluetooth tethering before I paired to Win8 and nothing showed up. So I had to remove the connection, enable tethering and repair, then it showed up.

**Comment by dlech** [comment]
Also, I have noticed if things get botched, you have to turn tethering off and back on, otherwise it disappears from bluetooth even though it is "on".

**Comment by sharived** [comment]
If I right-click on the Bluetooth network connection - I don't get an option to connect.  It just has view, disable, rename, properties, etc.
I just tried again and am sure that I had tethering on (I turned it off and an again) before I paired.

It seems like it doesn't know that the Ev3 is a network device. 
Are there any setting I should check on the EV3 itself?  Anything PAN related?

**Comment by dlech** [comment]
On the EV3, you can verify that tethering is working correctly by running `bluetoothctl` and looking at the output of `show'. You should see something like this:

```
[bluetooth]# show
Controller 00:17:E7:B4:71:28
	Name: ev3dev
	Alias: ev3dev
	Class: 0x020100
	Powered: yes
	Discoverable: yes
	Pairable: yes
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: NAP                       (00001116-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0517
	Discovering: no
```

If you see `UUID: NAP`, then it is working correctly.

**Comment by dlech** [comment]
Also check the `Class:` line.

**Comment by sharived** [comment]
I notice my class is different.  No NAP
[bluetooth]# show
Controller 00:17:E7:AE:4E:D7
        Name: ev3dev
        Alias: ev3dev
        Class: 0x000100
        Powered: yes
        Discoverable: no
        Pairable: yes
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0517
        Discovering: no

**Comment by dlech** [comment]
The most important part of the class is the last 4 numbers, so it should be OK.

However, no NAP is a problem. It means that ConnMan did not register it correctly.

To be certain, the command you are using to enable tethering is `connmanctl tether bluetooth on`.

If you leave `bluetoothctl` running in one terminal and run `connmanctl` in a separate terminal, you should see something like this:

Terminal 1 (bluetootctl):

```
[CHG] Controller 00:17:E7:B4:71:28 Class: 0x000100
[CHG] Controller 00:17:E7:B4:71:28 UUIDs:
	00001200-0000-1000-8000-00805f9b34fb
	00001800-0000-1000-8000-00805f9b34fb
	00001801-0000-1000-8000-00805f9b34fb
	0000110e-0000-1000-8000-00805f9b34fb
	0000110c-0000-1000-8000-00805f9b34fb
[CHG] Controller 00:17:E7:B4:71:28 Class: 0x020100
[CHG] Controller 00:17:E7:B4:71:28 UUIDs:
	00001200-0000-1000-8000-00805f9b34fb
	00001800-0000-1000-8000-00805f9b34fb
	00001801-0000-1000-8000-00805f9b34fb
	0000110e-0000-1000-8000-00805f9b34fb
	0000110c-0000-1000-8000-00805f9b34fb
	00001116-0000-1000-8000-00805f9b34fb
```

Terminal 2:

```
root@ev3dev:~# connmanctl tether bluetooth off
Error disabling bluetooth tethering: In progress
root@ev3dev:~# connmanctl tether bluetooth on
Error enabling bluetooth tethering: In progress
root@ev3dev:~# 
```

`00001116-0000-1000-8000-00805f9b34fb` is the UUID corresponding to NAP. You can see that it was removed when I turned tethering off and added when I turned it back on.

If you still aren't getting anything, check the output of `journalctl -r` for errors related to `connmand` or `bluetoothd`. (And reboots always work wonders).

**Comment by dlech** [comment]
And I just realized that you never said what kernel version you are running. If you were running an old version of brickman, then you are probably running an old kernel. The modules required for tethering were added in 3.16.1-7-ev3dev. This is probably what the problem is.

And this is why *everyone* is supposed to follow [these instructions](https://github.com/ev3dev/ev3dev/blob/master/CONTRIBUTING.md) *every* time you post an issue (it's the link in the big yellow box when you click "New Issue").

It would have saved both of us a lot of trouble if I would have thought to ask earlier.

**Comment by sharived** [comment]
Thanks for pointing out the big yellow box - I hadn't noticed it.  I definitely wasn't up to date when we started all this.  However, I'm using 3.16.1-7-ckt3-ev3dev1 now.  Does that work?

**Comment by dlech** [comment]
You probably mean 3.16.7-ckt3-ev3dev1, but yes that is > 3.16.1-7-ev3dev, so it has the required modules.

**Comment by sharived** [comment]
So I rebooted everything and ran in to windows.  Here's my output for bluetoothctl.  BTW, is it normal to lose my wired connection when I turn tether on?

[bluetooth]# show
Controller 00:17:E7:AE:4E:D7
        Name: ev3dev
        Alias: ev3dev
        Class: 0x000100
        Powered: yes
        Discoverable: yes
        Pairable: yes
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0517
        Discovering: no
[CHG] Controller 00:17:E7:AE:4E:D7 Discoverable: no
[CHG] Controller 00:17:E7:AE:4E:D7 Class: 0x020100
[CHG] Controller 00:17:E7:AE:4E:D7 UUIDs:
        00001200-0000-1000-8000-00805f9b34fb
        00001800-0000-1000-8000-00805f9b34fb
        00001801-0000-1000-8000-00805f9b34fb
        0000110e-0000-1000-8000-00805f9b34fb
        0000110c-0000-1000-8000-00805f9b34fb
        00001116-0000-1000-8000-00805f9b34fb
[CHG] Controller 00:17:E7:AE:4E:D7 Class: 0x000100
[CHG] Controller 00:17:E7:AE:4E:D7 UUIDs:
        00001200-0000-1000-8000-00805f9b34fb
        00001800-0000-1000-8000-00805f9b34fb
        00001801-0000-1000-8000-00805f9b34fb
        0000110e-0000-1000-8000-00805f9b34fb
        0000110c-0000-1000-8000-00805f9b34fb

**Comment by dlech** [comment]
It looks like it is getting turned on, but then turns back off. Perhaps this has to do with losing the Wired connection. I am using a wired USB Ethernet adapter instead of the USB Gadget connection. I will give it a try the other way and see if it makes a difference.

**Comment by dlech** [comment]
I don't lose the USB Gadget connection when I turn on bluetooth tethering.

Just want to make sure you *do not* run `connmanctl tether gadget on`. This will kill your wired connection.

**Comment by sharived** [comment]
No I have never run "connmanctl tether gadget on"

**Comment by dlech** [comment]
Well, something is telling bluetooth tethering to turn off after you turn it on. Or it crashes or something happens to make it unregister from bluetoothd. Did you ever check `journalctl` for error messages?

**Comment by dlech** [comment]
On the plus side, bluetooth tethering seems to be playing nice with my Mac now. I think it was just my Mac being weird and not any problem with anything on the EV3. If we could just get to the bottom of what the heck is different between our EV3's, I think you would be up and running on both Mac and Windows.

**Comment by sharived** [comment]
Just doing that now.  here are all messages in red (I think)

Jan 14 00:48:12 ev3dev connmand[612]: Method "ListAdapters" with signature "" on interface "org.bluez.Manager" doesn't exist
Jan 14 00:48:11 ev3dev connmand[612]: The name net.connman.vpn was not provided by any .service files
Jan 14 00:48:10 ev3dev connmand[612]: iptables support missing error 2 (No such file or directory)
Jan 14 00:48:10 ev3dev connmand[612]: No IPv6 support
Jan 14 00:48:10 ev3dev connmand[612]: No IPv6 support
Jan 14 00:48:10 ev3dev connmand[612]: Failed to flush table 'mangle': Invalid argument
Jan 14 00:48:10 ev3dev connmand[612]: iptables support missing error 2 (No such file or directory)
Jan 14 00:48:10 ev3dev connmand[612]: Failed to flush table 'filter': Invalid argument
Jan 14 00:48:10 ev3dev connmand[612]: iptables support missing error 2 (No such file or directory)
Jan 14 00:38:44 ev3dev connmand[346]: Method "ListAdapters" with signature "" on interface "org.bluez.Manager" doesn't exist
Jan 14 00:38:43 ev3dev bluetoothd[442]: sap-server: Operation not permitted (1)
Jan 14 00:38:43 ev3dev bluetoothd[442]: Sap driver initialization failed.
Jan 14 00:38:38 ev3dev ntpd[406]: restrict: error in address '::1' on line 42. Ignoring...
Jan 14 00:38:38 ev3dev ntpd[406]: restrict: error in address '::' on line 38. Ignoring...

**Comment by dlech** [comment]
We don't have IPV6 on the EV3, so that is expected. However, I think you are missing a package (that we need to add to the image that we distribute). Try installing `iptables` (`sudo apt-get install iptables`).

**Comment by sharived** [comment]
Yay!  That was it.  Thanks for your dedication on this.  I just got it working on my Mac, will verify windows next.  The only deviation is that I didn't get address 192.168.1.1 - mine is at 192.168.0.2.  I'll play around with it a bit and let you know if I see any other issues.

**Comment by dlech** [comment]
Here's to persistence! :relieved:

I found out that the IP address doesn't always use the same subnet. But you can use the network properties to figure it out easily. We should of course add it to brickman to.

**Comment by sharived** [comment]
Actually it was at 192.168.0.1.  And I verified that my Snap! app works, so I can use the tethered mode.  So right now I would need to use connmanctl each time, right?  But once you add this to brickman it would be automatic?

**Comment by dlech** [comment]
Looks like we would need to add something to [/etc/connman/main.conf](http://manpages.debian.org/cgi-bin/man.cgi?query=connman.conf&apropos=0&sektion=0&manpath=Debian+testing+jessie&format=html&locale=en) for it to remember the tethering setting, but then it would be automatic.

**Comment by sharived** [comment]
Tried windows, but not completely working.  I can not connect to the access point and I'm connected and can look at the status details.  I'm not getting an IPv4 Default gateway though

![image](https://cloud.githubusercontent.com/assets/1163591/5734334/297cbf9c-9b68-11e4-9bf2-071403852f2b.png)

**Comment by sharived** [comment]
false alarm.  I didn't realize that my ev3 had hung during the process.  Rebooted everything and it worked!

**Comment by dlech** [comment]
Should we close this issue?

**Comment by sharived** [comment]
Sure.  Thanks!

**Comment by nesteruk** [comment]
Having read the discussion above, I can note that *sometimes* the EV3 is not visible in the list of connectable devices. Also, plenty of random errors on the brick itself when attempting to initiate network connection. It's hit and miss, sometimes it works, sometimes it doesn't.

**Comment by tommasoclini** [comment]
I can't view any images, I get the 503 error, backend is unhealthy, how can I solve this?
