### ISSUE TITLE
Bluetooth Network on Windows

### ISSUE THREAD

**Issue by ljcrapo** [ev3dev/ev3dev#236]
I've done everything I need to and followed previous issues to try and connect to my EV3 via bluetooth from my Windows 7 laptop. I've run bluetoothctl and run: 
<code>agent on </code>
<code>default-agent </code>
<code>pairable on</code>
<code>discoverable on </code>
when I try to connect from my windows machine I get the following error message:
![image](https://cloud.githubusercontent.com/assets/7049913/5575121/9917716c-8f8d-11e4-9ec4-810ea7678fdc.png)
As you can see, it appears to be trying to perform some sort of authentication and failing. does anyone have any insight as to what is actually the problem?

**Comment by dlech** [comment]
We now have a tutorial for this. http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-bluetooth/?os=Windows

If that doesn't work, please open a new issue.
