### ISSUE TITLE
ev3dev-kernel refers to non-existent lego-linux-drivers submodule commit

### ISSUE THREAD

**Issue by woodcoder** [ev3dev/ev3dev#240]
Currently, cloning --recursive the kernel gives the following error

```
Cloning into 'drivers/lego'...
fatal: reference is not a tree: 51a21ba4c4c81c470fc8a0dbad295f135efe5ae4
```

I'm working around this using `cd ev3dev-kernel/drivers/lego; git checkout 14c8da6` (submodule fix as described at http://stackoverflow.com/a/2161389).

**Comment by dlech** [comment]
Not sure what happened to that commit, but I have just pushed the latest changes that I have been working on, so you should be good now. Do `git pull` in `ev3dev-kernel`, then `git submodule update`.

**Comment by woodcoder** [comment]
Great, that works, thank you!
