### ISSUE TITLE
OS X networking instructions don't work on 10.9

### ISSUE THREAD

**Issue by mattrajca** [ev3dev/ev3dev#25]
After setting up ev3dev to use CDC and connecting the device to a MacBook Pro running 10.9.1, I open the Network pref pane, click + and select CDC Composite Gadget. Nothing happens (the device is not added to the list).

The same procedure works fine inside of a VM running 10.7.

Console.app does not show any interesting error messages.

**Comment by burf2000** [comment]
Sorry to open a issue but this does not appear in 10.11.12
<img width="682" alt="screen shot 2015-12-27 at 21 10 24" src="https://cloud.githubusercontent.com/assets/319453/12012010/4938cc44-acde-11e5-85ab-fc37b0f943cf.png">

**Comment by dlech** [comment]
It's always best to create a new issue rather than commenting on a closed issue. Just to check the obvious, the USB cable is plugged in and you have selected "CDC" in the USB menu on the EV3? If not, please open a new issue.
