### ISSUE TITLE
problem with update to 3.16.7-ckt4-ev3dev1

### ISSUE THREAD

**Issue by in4lio** [ev3dev/ev3dev#262]
**# uname -r**
`3.16.1-7-ev3dev`

**# apt-get update**

**# apt-get upgrade**
...
`dpkg: error processing package dbus (--configure):`
` dependency problems - leaving triggers unprocessed`
`dpkg: dependency problems prevent processing triggers for dbus:`
` dbus depends on libdbus-1-3 (>= 1.7.6); however:`
`  Package libdbus-1-3:armel is not configured yet.`
...
`dpkg: too many errors, stopping`
`Errors were encountered while processing:`
` dbus`
` dbus`
...
` dbus`
`Processing was halted because there were too many errors.E: Sub-process /usr/bin/dpkg returned an error code (1)`

**# apt-get dist-upgrade**
Same result...

**Comment by ddemidov** [comment]
Duplicate of #239

**Comment by WasabiFan** [comment]
See #239.

**Comment by in4lio** [comment]
Thanks,
the solution is:
`apt-get install libdbus-1-3`
before upgrade.
Maybe we should mention about it in Getting Started?)
