### ISSUE TITLE
ev3dev.cpp with kernel v3.16.7-ckt4-ev3dev1

### ISSUE THREAD

**Issue by caldes** [ev3dev/ev3dev#264]
In ev3dev.cpp line 452 
  static const std::string _strClassDir { SYS_ROOT "/class/msensor/" };
shouldn't be changed to
  static const std::string _strClassDir { SYS_ROOT "/class/lego-sensor/" };

Thanks.

**Comment by ddemidov** [comment]
See ev3dev/ev3dev-lang#36 and ev3dev/ev3dev-lang#40. You could also use code from any of those PRs while the main branch is being updated.

**Comment by caldes** [comment]
Thanks!
