### ISSUE TITLE
Can I boot my SD installation on other bricks

### ISSUE THREAD

**Issue by andybets** [ev3dev/ev3dev#271]
I have installed ev3dev on an SD card, and customised it by adding software etc.  Would it now boot ok if I were to insert it into a different Mindstorms brick?  or would different MAC addresses, SSH issues, or something else cause a problem with that?  I would just try it, but don't have a second brick.

Many Thanks.

**Comment by dlech** [comment]
Yes, it should work with no problem. The Bluetooth MAC address will be different, so if you are using Bluetooth, you will need to re-pair. In all other respects, you won't be able to tell that it is a different EV3 brick.

**Comment by andybets** [comment]
That's great. Thanks for your work on this.
