### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by gvukasin** [ev3dev/ev3dev#275]
I have updated to the new kernel and I am missing the following classes and drivers:
tacho-motor-class
ev3-tacho-motor
ev3-analog-sensor
lego-sensor-class

Should I manually put them on from the github file "lego-linux-drivers-master"?

**Comment by dlech** [comment]
> I have updated to the new kernel

Please be specific about exactly which version (`uname -r`)

> I am missing the following classes and drivers

If you are, there is something wrong with your installation (like bad SD card or something). More than likely though, you do have them.

Plug in a sensor and a motor then run `ls /sys/class` on your EV3. You should see `lego-port`, `lego-sensor` and `tacho-motor`. If you do, then you have all of these drivers.

**Comment by gvukasin** [comment]
I was being an idiot, I found the drivers. Sorry for the premature posting.

**Comment by dlech** [comment]
I think we all do things like that sometimes. :wink:
