### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by LarsBudek** [ev3dev/ev3dev#276]
I try to install ev3dev-jessie-2014-10-07 and follow the “get started guide”… Everything seems to work. Format sdhc 8GB card. Install the image fil on the card using Win32diskimager. Boot the EV3 on the card… Flashing LED for some time and the Green LED. But the screen is blank…  What is wrong? Please give me a hit…

**Comment by dlech** [comment]
Try rebooting. If that does not work, try flashing the SD card again. If that does now work, try a different SD card.

**Comment by WasabiFan** [comment]
@dlech
>  If that does now work

That looks like a typo, but makes the sentence meaning change (and could be confusing)

**Comment by dlech** [comment]
Thanks for pointing that out. I have corrected it.

**Comment by dlech** [comment]
I noticed that you are trying to install an old release (ev3dev-jessie-2014-10-07). Please use the latest image file.

**Comment by marecl** [comment]
I had the same problem, blank screen or ev3 stock OS was booting
Try to dd if=/dev/zero of=/path/to/disk and then write image to raw disk
Or in the format settings select "write disk with zeros" to make sure there will be true "free space"
It has worked for me.

**Comment by dlech** [comment]
Hmm... I think this might be related to #267.

**Comment by dlech** [comment]
Pretty sure this is fixed in the ev3dev-jessie-2015-03-31 release
