### ISSUE TITLE
A critical look at the tacho-motor class.

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#282]
I am working on writing a driver for the [mindsensors.com NxtMMX](http://www.mindsensors.com/index.php?module=pagemaster&PAGE_user_op=view_page&PAGE_id=134) which of course will use the tacho-motor class. And although I don't have access to one, I am also taking into consideration the [HiTechnic motor controller](http://www.hitechnic.com/blog/wp-content/uploads/HiTechnic-Motor-Controller-Specification.pdf) (I can't write a driver since I don't have one, but just making sure that if someone were to write a driver, it will fit with what we are doing). While I am at it, I am planning on streamlining the tacho-motor class which involves making some breaking changes. So, if anyone has any suggestions for the tacho-motor class, now is an excellent time to make them heard. Here is what I am thinking...

### Speed and position related attributes

It has been suggested that we rename the `position` attribute to `pulses` to make it more obviously related to the `pulses_per_second[_sp]` attributes. (Comes from https://github.com/ev3dev/ev3dev/issues/229#issuecomment-67282237). This was also a point of confusion in #128, so maybe a good idea. Although my inclination is to call the attributes `position` and `speed[_sp]` and just make it clear in the documentation that the units are tachometer "ticks" or "counts". These two words seem to be used much more commonly than "pulses". Thoughts?

Another issue related to speed is that the motor controllers referenced here do not have speed feedback, only position. So, do we try to calculate speed or do we just return `-ENOTSUPP`?

### Commands and Modes

I would like to reconcile the `tacho-motor` class with the concepts of "commands" and "modes" that we have in the `lego-sensor` class. In the `lego-sensor` class, changing a "mode" changes which value(s) we are reading, how we read the value or units of measurement of the value. For example, for the LEGO ultrasonic distance sensors (both EV3 and NXT versions), changing the mode can change the scaling from centimeters to inches or it can change from continuous reading to single-shot reading (how we read it). "Commands" on the other hand tell the sensor to do something that does not change which value we are reading or how the value is read or the units. For example, on the LineLeader sensor, we have commands to calibrate white and black. This may change the actual numeric value that we are reading, but it doesn't change how (i.e. reflected or ambient by turning the LEDs on or off) or the units (it is still % of calibrated range).

One thing we don't have terminology for yet though is passing parameters to commands. This doesn't exist (yet) in the `lego-sensor` class. In the tacho-motor class, if a value is numeric, we are calling these parameters "setpoints", but if they are non-numeric, we are calling them "modes". I guess this is OK, but maybe we could find a different word that means both?

Getting back to motors, I think most attributes in the `tacho-motor` class should actually be called commands rather than modes. Also, there is some opportunity for some consolidation.

First, let's have a look at some commands existing motor driver implementations:

<table>
<tr>
<th>Command</th>
<th>NXT-G</th>
<th>EV3-G</th>
<th>NxtMMX</th>
<th>HiTechnic</th>
<th>ev3dev</th>
</tr>
<tr>
<td>Run forever/unlimited</td>
<td>Called "unlimited". Takes parameters of direction, power, and control (power regulation) enabled/disabled.</td>
<td>Called "On". Takes parameters of power (sign indicates direction).</td>
<td>Called "unlimited" (In NXT-G block). Takes parameters of speed and speed regulation enabled/disabled. Not sure on the units. Also doesn't seem to do anything if speed regulation is disabled.</td>
<td>Two commands called "Run with power control only" and "Run with constant speed". Takes parameter of power or degrees/second (divided by 10).
<td>Called "forever" ("run_mode" attribute). Takes parameters of "duty_cycle_sp" or "pulses_per_second_sp" and "regulation_mode"</td>
</tr>
<tr>
<td>Run for rotations/degrees</td>
<td>Two commands, called "rotations" and "degrees". Takes parameters of direction, ramping, power, control (power regulation), duration (rotations or degrees). Parameters are all relative to current position.</td>
<td>Two commands called "On for Degrees" and "On for Rotations". Takes parameters of power and degrees or rotations. Parameters are all relative to current position.</td>
<td>Three commands in NXT-G, "degrees", "rotations" and "To Encoder Position" (in NXT-G block - two commands or command with extra parameter in I2C). Takes parameters of power, duration (degrees/rotations). Degrees and rotations are relative values and encoder position is absolute value.</td>
<td>Called "Run to position". Takes parameter of max speed (degrees/second) and encoder position (absolute).</td>
<td>Called "position" ("run_mode" attribute). Takes parameters of "duty_cycle_sp" or "pulses_per_second_sp" and "regulation_mode", "position_mode" (relative or absolute).</td>
</tr>
<tr>
<td>Run for time</td>
<td>Called "seconds". Takes parameters of direction, power, control (power regulation enabled/disabled), and duration (seconds).</td>
<td>Called "On for Seconds". Takes parameters of power and seconds.</td>
<td>Called "seconds" in NTX-G or "Timed control" in I2C docs. Takes parameters of speed (regulated mode only?) and seconds (whole numbers only).</td>
<td><i>No timed mode.</i></td>
<td>Called "time" ("run_mode" attribute). Takes parameters of "duty_cycle_sp" or "pulses_per_second_sp" and "regulation_mode", and "time_sp" (milliseconds).</td>
</tr>
<tr>
<td>Stop</td>
<td>Two actions called "Brake" (active) and "Coast"</td>
<td>Two actions called "Brake" (active) and "Coast"</td>
<td>Two actions called "Brake" (passive) and "Coast". Also at the end of the run to encoder command there is the possibility of "Active encoder feedback".</td>
<td>Two special speed values "Off/Brake" (passive?) and "Off/Float". Also, The "run to position" command actively holds the position upon completion until another command is given.</td>
<td>Three "stop_mode" (attribute) values "coast", "brake" (passive) and "hold" (active).</td>
</tr>
<tr>
<td>Reset</td>
<td><i>No reset.</i></td>
<td><i>No reset.</i></td>
<td>Resets all parameters and current encoder value to 0. (Does not reset PID parameters).</td>
<td>Resets current encoder value and set to Off/Braked</td>
<td>Resets all parameters (including PID) and stops motor.</td>
</tr>
</table>

As you can see, things line up fairly well already. However, for better consistency with the lego-sensor class, I am planning on renaming the `run_modes` attribute to `commands` and renaming the `run_mode` attribute to `command`. We will drop the `run` attribute and instead writing a command to the `command` attribute will actually start the command. There will be a new `stop` command to take the place of writing `0` to `run`. Additionally, there will be a `reset` command and we will drop the `reset` attribute.

Another possibility is we could have two position commands, one for relative and one for absolute. This way we could drop the `position_mode[s]` attributes.

So, proposed new `commands` are: `run-forever`, `run-to-abs-pos`, `run-to-rel-pos`, `run-timed`, `stop` and `reset`.

The term `pos` (short for position) here will depend on the resolution of the previous section (position vs. pulses vs. ticks vs. counts).

### Stop modes

Since we have several commands that run until a condition is met and then stops, I think it makes sense that we still have a separate stop mode attributes. However, for consistency, I think we should rename them to `stop_command[s]`.

I like our existing names of `coast`, `brake` and `hold`. But, we need to clarify in our documentation the difference between `brake` (passive) and `hold` (active). There is the possibility for some confusion here because NXT-G and EV3-G use "brake" to mean an active brake instead of passive.

For those that don't know what I mean when I am saying "active" or "passive", and "active" brake (what we call `hold`) actually powers the motor to try to hold a fixed position. If you try to apply a force to turn the motor, the motor will push back with enough force to stop the motor from turning. A "passive" brake just shorts the motor terminals together to create a virtually infinite load. This makes the motor harder to turn by an external force, but no power is applied to the motor, so it won't push back to counter the force. If a motor is running and then stopped, the passive brake will cause the energy stored in the inertia of the motor to be dissipated faster and the motor will stop turning more quickly than it would if it was set to coast.

### Inversion modes

We have two sets of attributes to invert something: `encoder_mode[s]` and `polarity_mode[s]`. These have the possible values of `normal` and `inverted`. Since these are the only two values and and there is not the possibility of there ever being more values, I propose that we drop the `*_modes` attributes that just list the two possible values. Additionally, I propose we simplify the names to `polarity` (or `motor_polarity` or `output_polarity`) and `encoder_polarity`. The main point of renaming here is to disambiguate from the concept of "modes" discussed earlier.

Another feature that will be added is that `encoder_polarity` will return `-ENOTSUPP` if a motor controller cannot handle backwards encoder inputs. This will be the case with the NxtMMX and the Firgelli linear actuators. This combination can't work together, so it makes sense to get an error here.

### Driver names

Currently, we have the `type` attribute that returns `tacho` or `minitacho` (and it is also writable). To make the tacho-motor class more like our other driver classes, the `type` attribute will be renamed to `driver_name` (read-only). Also, we will use proper driver names instead of `tacho` and `minitacho`. The EV3 Large motor will be `lego-ev3-l-motor` and the EV3 Medium Motor will be `lego-ev3-m-motor`. Additionally the Firgelli actuators will have their own "driver" (`fi-l12`). These drivers won't actually be separate kernel modules, they will just determine preset parameters, such as PID parameters and in case of the Firgelli's, the `encoder_polarity`. Since not all motor types can be automatically detected you will be able to manually select the motor type by writing to the `set_device` attribute of the motor port (instead of writing to the `type` attribute in the tacho-motor class). This is how the other ev3dev drivers work already.

Additionally, related to the position attributes mentioned earlier, we should add a new `ticks_per_rot` attribute that will be specified by the selected driver. This will allow user programs to know how many counts returned by the `position` attribute equals one rotation of the motor.

### Motor status

We currently have a `state` attribute that returns the state of the tacho motor driver. The states are: `run_forever`, `setup_ramp_time`, `setup_ramp_position`, `setup_ramp_regulation`, `ramp_up`, `ramp_const`, `position_ramp_down`, `ramp_down`, `stop`, and `idle`. These represent the internal state of the state machine in the ev3_tacho_motor driver (which is currently the only implementer of the tacho-motor class).

There are a number of problems with this. 1) It only works with the one driver and doesn't take into consideration that other drivers may be implemented differently. 2)  Some of these modes last for very short periods of time and it is highly unlikely that reading the `state` attribute would ever return these values. 3) It is missing some obvious cases, like running for time and running to position. 4) It is missing some non-obvious cases, like is the speed regulation able to keep up or is the motor maxed out?

Before we get into what to do about it, let's have a look at our motor controls. EV3-G and NXT-G don't give you access to the motor state, so we are leaving those out.

<table>
<tr>
<th>Status Item</th>
<th>NxtMMX</th>
<th>HiTechnic</th>
<th>ev3dev</th>
</tr>
<tr>
<td>Speed Control enabled</td>
<td>Has status bit that indicates if speed control is on or off</td>
<td>No status bit, just depends on which command was used.</td>
<td>"regulation_mode" attribute.</td>
</tr>
<tr>
<td>Ramping</td>
<td>Has status bit to indicate ramping. Note: This definition of ramping is not the same as ev3dev - see section below.</td>
<td>N/A</td>
<td>Has 7 states related to ramping</td>
</tr>
<tr>
<td>Sending power to motor</td>
<td>Has status bit that indicates if power is being sent to motor</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>Position control active</td>
<td>Has bit to indicate that position control command is active - includes holding position after setpoint is reached.</td>
<td>Has busy bit that is set while driving towards setpoint, but cleared after setpoint is reached event though controller is still trying to hold that position.</td>
<td>N/A</td>
</tr>
<tr>
<td>Brake (passive) is active</td>
<td>Has status bit that indicates that the (passive) brake is enabled.</td>
<td>The status can be determined by reading the power parameter.</td>
<td>N/A</td>
</tr>
<tr>
<td>Speed regulation is maxed out (100% power output but &lt; speed setpoint)</td>
<td>Has status bit for this called "overloaded".</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>Timed mode</td>
<td>Has status bit to indicate that motor is running in timed mode</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr>
<td>Stalled (motor not moving)</td>
<td>Has status bit to indicate that the motor is stalled.</td>
<td>Has error bit that indicates that motor shut down due to a fault (most likely caused by overload/stall).</td>
<td>N/A (requested in #224) - actually, could check for speed == 0</td>
</tr>
</table>

The first question that comes to my mind is: Do we return multiple status at the same time or do we have a single state that returns only the highest priority status value. I'm leaning more towards the multiple status, but that leads to another question. Do we have a single attribute that returns multiple state flags or do we have multiple attributes that return a single state. Keeping in mind that the sysfs motto is "one thing per attribute", perhaps we need one attribute per status item. This makes for a lot of attributes, but I have seen in other driver where they add a subdirectory to group together related attributes. So, we could have a `state/` subdirectory that contains a number of attributes based on the table above. What makes the most sense here?

### Ramping

In ev3dev, we have `ramp_up_sp` and `ramp_down_sp` (which could be renamed to `*_ms` to be consistent with the other motor classes). When these are set to non-zero values, the speed will ramp up from 0 to 100% duty cycle over the specified time period. If the duty cycle is limited by the `duty_cycle_sp` or speed regulation mode is on, then the ramp time will be less. For example if we have `duty_cycle_sp` set to 50 (and speed regulation mode is off) and `ramp_up_sp` is 500ms, when we start the motor, it will ramp up from 0 to 50% duty cycle over the span of 250ms and then stay at 50% duty cycle until there is a stop command.

I like how this is setup, so I am not planning on changing it, but the motor controllers I am looking at either don't implement ramping (HiTechnic) or have a different definition of ramping (NxtMMX). In the case of the NxtMMX, "ramping" is a fixed time (on the order of 100s of milliseconds), so it is actually not visibly noticeable. It just makes wheels not slip as much when starting  abruptly.

Also, just for reference, in NXT-G, there is a parameter for ramping up or down when running a motor for rotations/degrees. It ramps the speed  up from 0 to the specified value over the span of the specified rotation (or down from the specified valued to 0). 

We could probably implement ev3dev-style ramping with these controllers using i2c commands, but I am not sure how smooth it would be. I am probably going to leave it unimplemented for the time being unless there is demand for it. In this case, reading or writing the `ramp_*` attributes will return `-ENOTSUPP`.

### PID Parameters

Both the NxtMMX and the HiTechnic motor controllers have parameters to adjust the PID tuning constants. Actually, in the case of the NxtMMX, there are 2 sets of constants, one for the speed regulation PID and one for the position regulation PID. Also, in the case of the NxtMMX, these values are share by two motors, so changing the values for one motor will change the other.

Both motor controllers have 3 constants: P, I and D. In the `tacho-motor` class, we have a 4th constant: K, which I am planning on removing. This value will be integrated into the other 3 constants.

I don't know if this will be possible, but it would be nice if the same constant values plugged into the ev3_tacho_motor driver yielded the same results as the constants used in the motor controllers. In other words, hopefully we are all using the same PID algorithm.

### Tacho motor pairs

One thing we haven't addressed yet in ev3dev is: how do you start 2 motors at exactly the same time? This probably isn't too much of a problem for our existing ev3_tacho_motor driver since writing to each `run` attribute happens within milliseconds, but it sure will be a problem with these motor controllers that communicate via I2C which is much slower (same with trying to remote control using the existing driver). To solve this, I am planning on adding a new "type" to the tacho motor class. Right now, we have "motor0", "motor1"... The new type will actually be a new driver class, but we'll keep it in the same `/sys/class/tacho-motor` directory, but will be named "pair0", "pair1"...

I will modify the existing ev3_tacho_motor driver so that output ports B/C will be a pair and output ports A/D will be a pair. The pair will only show up if both ports have the same motor driver loaded (i.e. both are EV3 Large motors). The NxtMMX driver will always create a pair for its motors since it doensn't know about other motor types.

**Comment by dlech** [comment]
@rhempel, I know this is an epic novel, but since you are the motor man, I hope you can make some time in the near future to plow through it and offer feedback, otherwise, I'm just going to go for it.

**Comment by rhempel** [comment]
I have plowed through most of David, and I'm seeing things that we visited and struggled with months ago, like separating the polarity modes, and distinguishing modes from setpoints.
Overall, the unification makes a lot of sense, especially separating out modes from commands.
I am glad that we had a number of users that worked through issues with the motors, notable the Figelli tacho polarity and the confusion of updating setpoints before the motor was in the idle state.
Let's talk about this tomorrow (maybe we can have a Skype session in the afternoon) and divide up the task - bear in mind I am still working on getting my full dev environment up. I can build the kernel modules, but not a full SD image.
Thanks for taking the time to assemble the backgorund informatio and posting it here for review.
I encourage other users of the existing motor drivers to leave some comments before we plow ahead with this - but in the end I think it's the right direction, minor course corections will be considered, of course.

**Comment by dlech** [comment]
> the confusion of updating setpoints before the motor was in the idle state.

I forgot to touch on this. The way the NxtMMX handles this is that uses the parameters that were set when a command was started. If a parameter is changed while the motor is running, it has no effect until a new command is issued. I think the ev3_tacho_motor driver should do the same. When we start a command, make a copy of the parameter variables and uses those in the PID and timer calculations.

Tomorrow afternoon sounds good for Skyping.

**Comment by rhempel** [comment]
Cool, I have to go in to the office (day job) in the morning, I have some time free in the afternoon

**Comment by in4lio** [comment]
**Motor pairs** also are necessary in case of the remote access to the brick over LAN. The original Lego VM allows mask of output ports in direct commands for this purpose, if I understood correctly, you would like to do something in the same style. Here are some other tentative ways to realize synchronization:

**`slave` attribute** (works only for tacho-motors of same types)
All commands for the host will be retranslated to the slave. _"Run together"_ example:
```
$ ls /sys/class/tacho-motor/
motor2/
motor3/

$ echo motor3 > /sys/class/tacho-motor/motor2/slave
$ cat /sys/class/tacho-motor/motor2/slave
motor3

$ echo 1 > /sys/class/tacho-motor/motor2/run

$ cat /sys/class/tacho-motor/motor2/state
run
$ cat /sys/class/tacho-motor/motor3/state
run
```
Moreover, it allows to create a chain more than two motors.

**`slave` attribute and pending command** (tacho-motors may have different types)
Slave receives the command but executes it only when the host will get any command. _"Host runs the slave stops"_ example:
```
$ echo motor3 > /sys/class/tacho-motor/motor2/slave
$ cat /sys/class/tacho-motor/motor2/slave
motor3

$ echo 0 > /sys/class/tacho-motor/motor3/run
$ cat /sys/class/tacho-motor/motor3/state
run

$ echo 1 > /sys/class/tacho-motor/motor2/run

$ cat /sys/class/tacho-motor/motor3/state
idle
$ cat /sys/class/tacho-motor/motor2/state
run
```

**`group` attribute or an execution of any motor commands synchronously**
_"Different commands for different motors"_ example:
```
$ ls /sys/class/tacho-motor/
motor2/
motor3/

$ ls /sys/class/dc-motor/
motor1/

$ echo 10 > /sys/class/tacho-motor/motor2/group
$ echo 10 > /sys/class/tacho-motor/motor3/group
$ echo 10 > /sys/class/dc-motor/motor1/group

$ ls /sys/class/motor-group/
group10/

$ echo sync > /sys/class/motor-group/group10/mode

$ echo 0 > /sys/class/tacho-motor/motor3/run
$ echo 1 > /sys/class/tacho-motor/motor2/run
$ echo coast > /sys/class/dc-motor/motor1/command

$ cat /sys/class/tacho-motor/motor2/state
idle

$ echo 1 > /sys/class/motor-group/group10/exec

$ cat /sys/class/tacho-motor/motor2/state
run
```

**Comment by dlech** [comment]
I actually proposed some master/slave motor attributes in <https://github.com/ev3dev/ev3dev/issues/40#issuecomment-36183880>. However, what I am proposing now is different. In the case of motors controlled via I2C, this sort of chaining will still be less than ideal because it would still send two separate commands to start each motor. Sending the commands takes some amount of time, so the motors would not actually start at the *exact* same time. The controllers I am looking at have special commands to start both motors at the same time, which is what the motor pair will utilize. This is why pairs will not be configurable - because they depend on the specific underlying drivers.

I like the idea of a motor group. I it doesn't seem useful enough to spend time implementing it right now though (well, I'm not going to do it, but pull requests are always welcome - and wait until we have made these other changes). And, I think it should be done in configfs rather than using sysfs attributes. Then (assuming we have made the other proposed changes) it might look like:

```
$ cat /sys/class/tacho-motor/motor0/state/running
0
$ cat /sys/class/dc-motor/motor0/state/running
0

$ cd /sys/kernel/config/motor-group
$ ls
command
dc-motor/
servo-motor/
tacho-motor/

$ cd tacho-motor
$ mkdir motor0
$ cd ../dc-motor
$ mkdir motor0

$ cd ..
$ echo run-forever > command

$ cat /sys/class/tacho-motor/motor0/state/running
1
$ cat /sys/class/dc-motor/motor0/state/running
1
```

Mixing motor types might get a little tricky though since they won't all have the same commands.

**Comment by MetallianFR68** [comment]
Hi,
I just read this article.
There are 2 things i really want to see in future versions:
- motor groups (not only pairs)
- ability to detect the FIRGELLI L12 automatically
So I give a big +1 to this suggestions

**Comment by rhempel** [comment]
While it would be nice to be able to detect Firgelli motors automatically, I'm afraid that it's impossile because they were made electrically identical to the standard servo motor.
Well, not exactly compatible becuase the motor tacho counts "backwards" relative to the standard LEGO motor, given the same direction setting, which is why we have an invert tacho attribute.
Most ev3dev based creations know which port a motor is plugged into, so it is not too big of a deal to force the Firgelli mode when you start your program.
Is there another specific use case where automatic detection would be a bonus?

**Comment by dlech** [comment]
I've been making progress. See commits above.

**Comment by dlech** [comment]
To be a little more verbose, I have pretty much made all of the changes I described except for doing something with motor state. Any one that wants can give this a test and see how badly I broke things. :grin:

I'm going to start on the actual implementation of the NxtMMX now and see how it fits into the "new" tacho-motor class.

**Comment by MetallianFR68** [comment]
Hi,

I see that you're working hard on the motor class. ! good job !

Here's another feature suggestion : min and max values.

Example : you set a "max position" value for the motor and it stops when it reaches it (or even better it ramps down and stops at the value)

**Comment by dlech** [comment]
What you are describing sounds like the run to position commands with a ramp up/down setpoint, which are features we already have (although possibly not working correctly).

**Comment by rhempel** [comment]
I think @MetallianFR68 is asking for hard stops so that he can turn the motor on and check position and adjust output duty cycle and direction as long as the motor position is inside the stops. If the motor hits either min or max setpoints - stop the motor.

**Comment by dlech** [comment]
OK, I see. I still think you can accomplish this using the run to position command. You just have to check the sign of your duty_cycle_sp to know whether to use the min or max value as the position_sp. Keep in mind that we are modifying the driver so that changing a setpoint while the driver is running has no effect until you send another command.

**Comment by MetallianFR68** [comment]
Yes that's what I meant. The idea was to implement LIMITS value.
For example the limit is set to 5000
If i try to send the motor to position 10000, it stops at 5000 (the upper limit)
But I agree this can be done in another way using the already available commands...

**Comment by dlech** [comment]
I've just pushed a new kernel package with many of these proposed changes. To save me from having to type everything again, read the [announcement](http://www.ev3dev.org/news/2015/04/15/Kernel-Release-v3.16.7-ckt9-ev3dev1/), check out the new tutorial and let me know how it goes.

A few notable things I have *not* done yet...
1. Anything with ramping - I have no idea if it works, so don't be surprised if it does not.
2. Implemented motor pairs yet, so still nothing available with that.
3. The "stalled" flag does not work with the `legoev3-motor` driver.
4. The settings for the Firgelli actuators need to be looked at [here](https://github.com/ev3dev/lego-linux-drivers/blob/master/ev3/legoev3_motor_defs.c#L41). I don't own one of these, so someone else will have to fix it (or send me one). 

If you find any problems with the "new" tacho-motor class, please open a new issue rather than posting here.

**Comment by rhempel** [comment]
I'll look at the new drivers tomorrow or Friday - I have a Firgelli actuator to test with. I also have a bunch of test scripts that need to be rewritten but that's OK

**Comment by MetallianFR68** [comment]
Is there any update on motor groups ?
I'm really looking forward for this feature

**Comment by dlech** [comment]
Sorry, not yet.

**Comment by rhempel** [comment]
I'll probably be poking around and fixing a few small issues in the tacho motor driver soon - the `run-to-abs-pos` is not hitting the target very reliably at all.

**Comment by ericpascual** [comment]
First of all, kudos to everybody in the ev3dev team for such an amazing work. I've been using LeJOS a lot, (and contributing a small bit to) but I really enjoy having Debian running on the EV3, and being able to program it with languages such as C/C++ and Python (I manage a volunteer association in amateur robotics, and could note that the last one being IMHO the best suited for teaching programming to youngsters). Once again, many thanks to all of you.

While discovering and experimenting with the latest ev3dev version, using Python for programming, I could observe a constant behaviour with `run-to-abs-pos` which is perhaps the one you are referring to in the previous post. Note that the programming language has nothing to do here, since echoing to the `/sys/sclass/tacho-motor` pseudo files gives the same result.

When the `stop` command is `brake`, the final position is always past the target. When `stop` is set to `hold`, it reaches the target perfectly, but with an overshoot every time (i.e. it first pass the target and then goes back to it). I have tested with the large motor only for the moment, but using various speeds (from 50% to 100%). 

I haven't played with the PID settings, not being an expert in the domain, but I guess it would be possible for people mastering the topic to find the right triplet for reaching the target without overshoot. Maybe this overshoot has something to do with the brake stop behaviour.

Observing the behaviour in brake stop mode, it seems that the motor starts to decelerate when reaching the target position. Even with no speed down ramp, this has chances to too late for stopping at the right position. But I cannot ensure that the observation is precise enough.

I'll try to have a look to the source code of motor regulation, but am not sure to be competent enough for finding clues. In case I could, I'll share them here of course.

**Comment by rhempel** [comment]
Note that the Python API is under active development right now and may change slightly.
The overshoot depends a lot on things like motor loading, speed, how far the absolute position is from the start position and so on. If you really need the precision, `hold` mode is the way to go, and you can also play with the `ramp_down_sp`. For fine tuning, the PID parameters may help along with a tutorial that you can probably find via Wikipedia.
Some users just read the `position` property and handle the motor position themselves.
I may look at the motor drivers in between other tasks.

**Comment by ericpascual** [comment]
Thanks Ralph for replying so quickly. 
I too came to the conclusion that the hold mode was the way to go for the moment.
By the way, I've found somewhere a proposal related to linking motors in some master-slave relation. It would be great since I could also notice a small glitch at the end of straight moves, one motor stopping a small delay after the other, leading to the robot heading getting wrong. This is maybe caused by the small delays created by controlling motors with separate calls.

**Comment by dlech** [comment]
This issue is getting rather old. Most items have been implemented, but there are a few things still left to do. I am opening individual new issues for these so we can close this one.

Ramping: #453 
Motor pairs (aka synchronized starting of motors): #454
Stall detection on EV3: #455

If I left out anything important, feel free to open a new issue.
