### ISSUE TITLE
Connecting in Linux Mint

### ISSUE THREAD

**Issue by MolarAmbiguity** [ev3dev/ev3dev#289]
I've installed ev3dev on my brick, and was able to connect fine under Ubuntu. Now when I try in Mint I cannot connect over both USB and Bluetooth. Has anyone had any success in Mint before?

Edit: My OS is Linux Mint 17.1 32-bit Cinnamon

**Comment by rex-j** [comment]
Yes, I am using Mint 17.1 and I can connect by USB.

**Comment by MolarAmbiguity** [comment]
It seems I cannot find the option in the ipv4 settings called "shared to other computers". Could you see this option?

**Comment by dlech** [comment]
Which version of Mint are you using? 17.x? Cinnamon? MATE? LMDE?

**Comment by MolarAmbiguity** [comment]
1.7.1 32-bit Cinnamon

**Comment by dlech** [comment]
Looks like you have to go to "Network Connections" instead of "Network Settings", then you can find "shared to other computers".

**Comment by MolarAmbiguity** [comment]
Ok that worked (after I fiddled around with turned of tethering). I will update the tutorial with this info.

**Comment by dlech** [comment]
FYI, I sent a pull request to fix Network Settings in Linux Mint.

https://github.com/linuxmint/cinnamon-control-center/pull/109

**Comment by MolarAmbiguity** [comment]
Ah ok cool, I'll hold off for now. Should probably just make sure people are using the latest version of cinnamon control center.

**Comment by dlech** [comment]
Bug also exists in gnome-control-center.

https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1385674

**Comment by dlech** [comment]
I saw that Mint 17.2 was released today. I wonder if my patch was included?
