### ISSUE TITLE
Enabling Bluetooth by default?

### ISSUE THREAD

**Issue by andybets** [ev3dev/ev3dev#290]
Is it possible/easy to change some configuration setting so that Bluetooth is enabled by default when the BrickMan menu loads?  Starting a script automatically would be really great too - if possible.

**Comment by dlech** [comment]
What do you mean by "enabled"? Do you mean powered on? If so, once you power it on, it should stay powered on across reboots. If not, this is a bug. If by "enabled" you mean connected to something else, please explain further.

**Comment by andybets** [comment]
Hi David - Yes, I think it's must be a bug then.  I'm having to go to 'Network' and select 'Bluetooth' every time the BrickMan menu loads up.

**Comment by dlech** [comment]
It sounds like you don't have the latest version of brickman - not that it would make a difference for this issue. Please upgrade your packages (at least `brickman`, `connman` and `bluez`) and may sure you install the new packages `iptables` and `ev3dev-connman-config` and then try again.

Then have a look at `journalctl -r` to see if there is anything related connmand or bluetoothd that may give a hint as to why it is not staying powered on.

**Comment by andybets** [comment]
Thanks.  I'll have a look in the next few days, and get back to you.  What about automatically running scripts automatically when it loads?  What's the best way to arrange it?

**Comment by dlech** [comment]
Search is your friend: https://github.com/ev3dev/ev3dev/issues?q=is%3Aissue+startup+script

**Comment by andybets** [comment]
Thanks.

**Comment by dlech** [comment]
Is this still an issue with the latest release?

**Comment by andybets** [comment]
Sorry, not sure. I haven't had a chance to work on the project since we
last spoke.



On Wed, 20 May 2015 20:29 -0700, David Lechner
<notifications@github.com> wrote:
> Is this still an issue with the latest release?


> — Reply to this email directly or view it on GitHub[1].

>

DataDevil Limited (Company Number: 8979820) Telephone: 016973 32492 |
Website[2] Registered Office: DataDevil Limited, Fairview House,
Victoria Place, Carlisle, Cumbria, UK CA1 1HP

DataDevil Limited has taken reasonable steps to ensure that outgoing
communications do not contain malicious software. Please carry out your
own checks on this email before accepting it and opening attachments.
Any views or opinions expressed may not necessarily represent those of
DataDevil Limited.



Links:

  1. https://github.com/ev3dev/ev3dev/issues/290#issuecomment-104113264
  2. http://www.datadevil.co.uk

**Comment by dlech** [comment]
OK. I'm going to close the issue since it is working for me and presumably others. Feel free to reopen if you find the problem still exists next time you have a chance to use ev3dev.
