### ISSUE TITLE
Create ev3dev-config tool

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#316]
As discussed in #280, we think it would be nice to have a simple tool to do most of the [first things](http://www.ev3dev.org/docs/getting-started/#step-5-first-things-to-do-with-ev3dev) from the ev3dev getting started page. Raspian (Debian wheezy on Raspberry Pi) already has a tool called `raspi-config` to do this that I think we could build from.

If anyone has been looking for something they could do to contribute to ev3dev, here is a good opportunity. This should be a fairly easy task if you are not afraid of shell scripts. It's mostly removing stuff anyway.

I have cloned [raspi-config](https://github.com/asb/raspi-config) into [ev3dev-config](https://github.com/ev3dev/ev3dev-config), so fork [ev3dev-config](https://github.com/ev3dev/ev3dev-config) and get hacking.

Here are the changes I think need to be made:

- [ ] Add a `README.md` file explaining what this is. Be sure to include a note that this is a fork of `raspi-config`.
- [ ] Rename files and replaces all instances of `raspi-config` with `ev3dev-config`. Please do file renames in a separate commit from other changes (it makes git history easier to follow).
- [ ] Remove the "Expand Filesystem" bits. This will be included in the firstboot script.
- [ ] Remove the "Enable Boot to Desktop/Scratch", "Enable Camera", "Add to Rastrack", and "Overclock" menu items. Can leave the functions in case we decide we need them later.
- [ ] Remove all? of the items from the "Advanced Options" menu.
- [ ] Modify the `do_change_hostname()` function to use `hostnamectl` instead.
- [ ] Add "Services" menu to disable/enable various services:
    - [ ] `systemd-journald`: This either uses lots of memory or lots of disk activity, so people probably want to turn it off unless they are having a problem they need to troubleshoot.
    - [ ] `avahi-daemon`: This is only needed for name resolution with a Mac or Linux host.
    - [ ] `nmbd`: For windows (NETBIOS) name resolution.
    - [ ] `brickman`: You never know.
- [ ] Add option for enabling debugging using a serial console on input port 1. See #55. This sounds like a candidate tor the "Advanced Options".

**Comment by MolarAmbiguity** [comment]
So is the idea to have ev3dev-config at first boot, then use the brickman menu for any further configuration? Or will ev3dev config be used for any configuration that needs to happen?

**Comment by dlech** [comment]
`ev3dev-config` is for the stuff that you don't do very often, so you forget how to do it - and for stuff that would not work well on the small screen or without a keyboard.

brickman if for things you might want (or need) to do without having a separate computer connected.

**Comment by WasabiFan** [comment]
I _would_ volunteer for this now, but I am pretty well-loaded with ev3dev projects at the moment. If someone doesn't claim this within a few weeks, I might be able to get this started.

**Comment by WasabiFan** [comment]
Cool, I'm officially assigned to something! :grin:

**Comment by dlech** [comment]
That's what happens when you make significant contributions. :wink:

**Comment by dlech** [comment]
Hmm... I'm wondering if we should just include this in the ev3dev-tools package instead of a separate repository instead of having a separate repository. We already have lots of `*-config` packages, but the others all have to do with config files (as in `/etc`).

**Comment by WasabiFan** [comment]
I have no vote either way... All I'll say is that the sysinfo tool is pretty lonely at the moment in its repo :wink:

**Comment by dlech** [comment]
Do you want to copy and paste the `ev3dev-config` script to `source/scripts` in [ev3dev-tools](https://github.com/ev3dev/ev3dev-tools) and make a pull request? Name the new file `ev3dev-config.sh`.

**Comment by WasabiFan** [comment]
Give me a minute and I should have a PR ready.

**Comment by dlech** [comment]
This has been released in `ev3dev-toos 1.1.0`.
