### ISSUE TITLE
brickman networking screen stays "loading"

### ISSUE THREAD

**Issue by topikachu** [ev3dev/ev3dev#325]
Just same as #196

But this happens on ev3dev-jessie-2015-05-01

**Comment by dlech** [comment]
Exactly the same? So output of `systemctl status -l brickman` is the same? And restarting brickman with`systemctl restart brickman` brings the network menu back?

**Comment by topikachu** [comment]
well. I have no network. how to input these commands? By a keyboard?

**Comment by dlech** [comment]
It sounds like this is on a fresh install. If rebooting does not fix it, then you might try writing the image again. If that does not fix it, then you can attach a keyboard to the EV3 and press ALT+CTL+F6 to get a terminal and try to see what is going on.

**Comment by topikachu** [comment]
well, it seems my sd card is corrupted. I use a new one and it's ok now.
