### ISSUE TITLE
Can't connect via bluetooth on a chromebook

### ISSUE THREAD

**Issue by sharived** [ev3dev/ev3dev#326]
Wanted a cheap laptop for folks to play with at the Maker's Faire and decided to buy a chromebook.  I was trying to connect via Bluetooth.  I was able to pair, but not connect.  I tried pairing from both directions.  Before returning it, I thought I'd ask if anyone has tried one before and if you might have any recommendations.  Also tried connecting wired, but no luck there either.

**Comment by dlech** [comment]
Install Ubuntu on the Chromebook or use Wi-Fi maybe?
