### ISSUE TITLE
Hard to read the IP address at the top of the brickman display

### ISSUE THREAD

**Issue by sharived** [ev3dev/ev3dev#332]
Hoping we can move it down a few pixels.

**Comment by dlech** [comment]
I am thinking that you have the same shadow at the top of the screen that I see on my EV3 that is making it hard to read.

I was going to suggest maybe moving the statusbar to the bottom of the screen, but then whatever else happens to be at the top of the screen will be hard to read, so this is probably not a good idea.

**Comment by sharived** [comment]
RIght, I'm busy turning it different angles to see it.   And with the small lettering it is even harder.

**Comment by dlech** [comment]
Fix has been released in brickman 0.7.0. More casual users will want to wait for the next image release before updating. See the [announcement](http://www.ev3dev.org/news/2015/12/15/Package-Release/) for more info.

Just making the font bigger seems to be good enough to make it more readable.
