### ISSUE TITLE
Link to ev3 via USB

### ISSUE THREAD

**Issue by TonyReese** [ev3dev/ev3dev#34]
Apologies if this is a silly very basic Linux question 
I installed Ubuntu 13.10 on my laptop to develop thses ideas.
I have created a micro SD card which powers the EV3 brick and gets to the welcome screen and the flashing orange lights
But I have no idea how to set up the host laptop PC to communicate with it.
I don't see any reference to usb0 anywhere in the linux files on my laptop
I am sure I am missing something very basic to Linux, but as I said I am really an absolute beginner in Linux (although this is my third attempt in over 50 years of playing with computers)

**Comment by dlech** [comment]
The information here is quite outdated, so closing.
