### ISSUE TITLE
Refering people to the ev3dev website

### ISSUE THREAD

**Issue by MolarAmbiguity** [ev3dev/ev3dev#341]
I was trying to help out @AlienSM in #340. I linked to http://www.ev3dev.org/support/#irc. When I click on that link the (extremely helpful) navigation bar blocks the heading of the content in addition to the first paragraph. Whilst a minor nitpick this feels like an easy fix that could greatly improve user experience.

I'm using firefox 38.0 on Linux Mint. I'm curious to see if others can reproduce this. I don't know what would need to be edited to resolve this issue.

**Comment by ddemidov** [comment]
Confirmed on chromium 43.0.2357.81 (Arch linux)

**Comment by MolarAmbiguity** [comment]
Also confirmed in Midori 0.4.3 on Mint. I think its safe to assume this is universal.

**Comment by dlech** [comment]
I thought it was just me...

**Comment by dlech** [comment]
How does it look now?

**Comment by ddemidov** [comment]
Looks great in chromium!

**Comment by MolarAmbiguity** [comment]
Looking good @dlech
