### ISSUE TITLE
Lego nxt light sensor

### ISSUE THREAD

**Issue by Oxel40** [ev3dev/ev3dev#343]
Hi!
I wonder if there are any code examples for using the light sensor in batch or Python?
I can't understand how you would be able to take readings from the light sensor in bach or Python.
Thanks for all answers!!!

**Comment by ddemidov** [comment]
ev3dev/ev3dev-lang#59 seems to indicate the nxt light sensor does work at least with python. Does the following work for you?
```py
>>> from ev3dev import *
>>> s = light_sensor()
>>> s.connected
True
```

**Comment by Oxel40** [comment]
No @ddemidov, it does not work. Is there a module named ev3dev that i can download that would be able to take readings from the light sensor?
```
>>> from ev3dev import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ev3dev
```

**Comment by MolarAmbiguity** [comment]
When you are doing ```from ev3dev import *``` are you sshed into the brick?

**Comment by Oxel40** [comment]
Yes @MolerAmbiguity, I am sshed using putty

**Comment by MolarAmbiguity** [comment]
Also which version of ev3dev are you using? And where did you install python from?

**Comment by Oxel40** [comment]
I installed python by folowing this instruction https://github.com/topikachu/python-ev3.
I don't remember which verison the ev3dev is.

**Comment by ddemidov** [comment]
> I installed python by folowing this instruction https://github.com/topikachu/python-ev3.

I thought you were talking about [python-ev3dev](https://github.com/ddemidov/ev3dev-lang-python). My example won't work for @topikachu's bindings. You should probably get more help if you [open an issue ](https://github.com/topikachu/python-ev3/issues/new) in python-ev3 repository.

**Comment by Oxel40** [comment]
Ok, Thanks alot @ddemidov!

**Comment by ddemidov** [comment]
And, by the way, you *will* be able to use NXT light sensor with [python-ev3dev](https://github.com/ddemidov/ev3dev-lang-python).
