### ISSUE TITLE
Can't load uart sensors

### ISSUE THREAD

**Issue by topikachu** [ev3dev/ev3dev#344]
After burn the new ev3-ev3dev-jessie-2015-05-20 image, the system can't load uart sensors

dmesg.
```
[  340.701077] g_ether gadget: high-speed config #2: RNDIS
[  403.092174] lego-port port1: Removed device 'in2:ev3-uart-host'
[  404.474948] lego-port port2: Added new device 'in3:ev3-uart-host'
```
But there's no sensor under /sys/class/lego-sensor/
It's empty and no sensor in the brickman Devices Browser

:(

BTW, a nxt-i2c device is OK. 
```
[  870.078867] lego-sensor sensor1: Registered 'ms-absolute-imu' on 'in4:i2c17'.
[  870.108584] i2c-legoev3 i2c-legoev3.6: registered on input port 4
[  870.113989] lego-port port3: Added new device 'in4:nxt-i2c-host'
root@ev3dev:~# ls /sys/class/lego-sensor/
sensor1
```

**Comment by theZiz** [comment]
I would guess, this is the same problem as stated here: https://github.com/ev3dev/ev3dev/issues/336

upgrade and reboot should help. :)
