### ISSUE TITLE
Using ev3 input port 1 as serial port?

### ISSUE THREAD

**Issue by Sashkakuhta** [ev3dev/ev3dev#346]
So, i need to use input port 1 as uart, but cant find any actual instructions about it. This https://github.com/ev3dev/ev3dev/wiki/Frequently-Asked-Questions instructions is way too outdated. I tried setting in1 mode as other-uart and shorted yellow and blue wire on wire plugged in port 1. Then i tried cat to ttyS0 and ttyS1, none of them replied with something when i was sending something. How do i do it then?

**Comment by dlech** [comment]
If you want to use input port 1 to debug kernel messages, you need to edit `/etc/modprobe.d/ev3.conf` and `/etc/sysctl.d/ev3.conf`. This make the port unusable for anything else.

If you would like to keep the port configurable, but still use the UART function, you can change the port mode to `UART`. See <http://www.ev3dev.org/docs/ports/legoev3-input-port/> and <http://www.ev3dev.org/docs/drivers/lego-port-class/>.

**Comment by dlech** [comment]
Oops, I meant `other-uart` instead of `UART` for the mode. Corrected above.

**Comment by dlech** [comment]
Also, there are symlinks for the input port ttys so you don't have to sort out which one is which. There should be a `/dev/tty_in1`.

**Comment by Sashkakuhta** [comment]
Its actually called tty_ev3:in1. What i want is connecting to another device via uart from ev3. I tried to set mode to other-uart and ev3-uart but ttys are silent even when connecting rx and tx

**Comment by dlech** [comment]
Sounds like you need to do `sudo apt-get update; sudo apt-get upgrade`. It is not supposed to have the `ev3:` in the link (this causes UART sensors to not work). It won't affect what you are trying to to though.

Maybe you have your rx and tx crossed. It is working for me.

**Comment by Sashkakuhta** [comment]
I updated it, messed with minicom a bit and it started working, thanks!
Minicom needs to be launched withs -s flag and setted to tty_in1 port, then it should just start working.
