### ISSUE TITLE
Permissions issue with latest release

### ISSUE THREAD

**Issue by Svetomech** [ev3dev/ev3dev#358]
I'm getting this error when trying to add permissions (following 'getting started' guide): 
**usermod: group 'i2c' does not exist**

**Comment by dlech** [comment]
Try installing the `i2c-tools` package.

**Comment by Svetomech** [comment]
Why is it not included?

**Comment by dlech** [comment]
No one ever asked :wink:

**Comment by Svetomech** [comment]
Btw, may be closed now. Though I am still a bit curious as to why I wasn't getting this error in previous versions.

**Comment by ddemidov** [comment]
>  Though I am still a bit curious as to why I wasn't getting this error in previous versions.

The recommendation to add users to `i2c` group has only been added three days ago in ev3dev/ev3dev.github.io@a193678d6bf7c5297392dc058e7bdd91266bc41d.

**Comment by dlech** [comment]
I've reverted that commit for now. I will add `i2c-tools` and the corresponding python i2c packages to the next image release and then add the `i2c` group back to getting started.
