### ISSUE TITLE
[brickpi] Using set_device attribute to set ev3-uart sensor hangs if sensor is not connected

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#370]
Using brickpi on RPi with nothing plugged into the sensor ports. Steps to repeat....

    cd /sys/class/lego-port/port0 # presuming this is a brickpi input port
    echo ev3-uart > mode
    echo lego-ev3-us > set_device # this command hangs

The command hangs until a sensor is actually plugged in.

**Comment by dlech** [comment]
Cannot duplicate anymore. There is a long timeout (10 seconds) but does not hang. May have been fixed by commit from #531.

**Comment by dlech** [comment]
Now I'm getting a timeout of nearly a minute. This is due to the BrickPi just not responding at all. It's like the microprocessor on the BrickPi is in a bad state. This will probably have to be fixed in the BrickPi firmware rather than in ev3dev.

**Comment by jabrena** [comment]
Good morning,

What is the process to update the firmware on brickpi?

**Comment by dlech** [comment]
http://www.dexterindustries.com/BrickPi/about/design/brickpi-firmware-update/

Although if you want better firmware, you have to change the firmware source code yourself. :wink:
