### ISSUE TITLE
Support for mindsensors.com PiStorms

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#372]
http://www.openelectrons.com/index.php?module=pagemaster&PAGE_user_op=view_page&PAGE_id=27&MMN_position=7:7

This should be fairly easy to implement since we already have an RPi image.

For bonus points, we can add touchscreen support to brickman.

**Comment by dlech** [comment]
I will purchase one of these if we get $100 in bounties at <https://www.bountysource.com/issues/25142687-support-for-openelectrons-com-pistorms>.

**Comment by dlech** [comment]
mindsensors.com is sending us one - yea!

**Comment by rhempel** [comment]
You should have a FatCat unit on the way as well - put that bounty money to use and pick up a BeagleBone :-)

**Comment by dlech** [comment]
Fix released in kernel cycle 8 (`*-8-ev3dev-*`).
