### ISSUE TITLE
EV3 has been booting for 22 minutes

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [ev3dev/ev3dev#381]
I inserted the microSD and booted for the first time. This was at 8:41 EST. The getting started page says it's supposed to take longer on first boot, but should it take this long? Is it safe to pull out the card or pull out a battery or will this corrupt files?

**Comment by dlech** [comment]
Longer means about 1 minute at most. Yes, it is safe to pull out the card or the battery - although holding the back and enter buttons for about 3 seconds to reset is generally easier than removing the battery.

My guess is that the SD card is already corrupt or defective or too big (> 32GB). Try flashing again or using a different SD card.

**Comment by The-Penultimate-Defenestrator** [comment]
SD card is 8 GB, I'll try re-flashing. New ones arrive tomorrow.

**Comment by The-Penultimate-Defenestrator** [comment]
FIxed. I had copied the EV3-BOOT from the disk image, but not the other file. Now it works.

**Comment by G33kDude** [comment]
I don't recall ever having to copy files around to flash my SD cards, it's always just flash them then stick it into the bot and boot.

**Comment by The-Penultimate-Defenestrator** [comment]
I flashed it using disk utility on my Mac, but the image had two partitions, only one of which I flashed

**Comment by rhempel** [comment]
No, you take the entire image that was downloaded and then:
```
dd if=source.img of=/dev/sdx bs=4M
```
No need to monkey around with the images or partitions in the image or on the SD card.
Not being picky, but what part of the instructions was not clear on that so we can improve it if necessary.

**Comment by The-Penultimate-Defenestrator** [comment]
Yes, I didn't do this because it didn't work the first time. This is how I
fixed my issue. Before, I had used Disk Utility
