### ISSUE TITLE
apt-add-repository

### ISSUE THREAD

**Issue by tiblop** [ev3dev/ev3dev#382]
Hello I can't make apt-add-repository to work ! 
I tried to install from : 

sudo apt-get install software-properties-common
sudo apt-get install python3-software-properties
sudo apt-get install python-software-properties

but then it doesn't work... please help

**Comment by dlech** [comment]
Did you run `sudo apt-get update` first? Do you have an Internet connection to your EV3?

**Comment by tiblop** [comment]
yes and yes

**Comment by dlech** [comment]
Hmm... `sudo apt-get install software-properties-common` works for me. Are there any error messages?

**Comment by tiblop** [comment]
yes, apt-get install works it is then when i try to use apt-add-repository it says : 
apt-add-repository could not find a distribution template for ev3dev/jessie
I thought it was because i should install apt-add-repository differently

**Comment by dlech** [comment]
I see, what is the actual command line you are typing in?

**Comment by tiblop** [comment]
sudo apt-add-repository http://ev3dev.org/debian

**Comment by dlech** [comment]
That repository is already included in the apt sources on the EV3. Are you trying to install this repository on a regular computer?

**Comment by tiblop** [comment]
no but i've done some fail manipulation. at some point it told me that it was a problem with my source so i did a backup of my source and delete everything on it then i deleted the backup by mistake... :/ I try to start all over from scratch but it didn't help ...

**Comment by tiblop** [comment]
i'm trying to install ROS by following thie tutorial: 
https://github.com/moriarty/ros-ev3/blob/master/brickstrap-build-status.md
but it messed up my whole system and now i'm stuck.

**Comment by dlech** [comment]
It looks like those instructions are supposed to be run on a host computer, not on the EV3 itself.

**Comment by dlech** [comment]
Also, that project has not been updated in many months and will likely not work correctly on a recent release of ev3dev.

**Comment by tiblop** [comment]
:/ ok so now that explain things... So now how can I fix my EV3?

**Comment by dlech** [comment]
You could re-flash the SD card.

**Comment by dlech** [comment]
Assuming this issue is resolved. You can reopen if there is still a problem.
