### ISSUE TITLE
Announcement missing from release "rpi-ev3dev-jessie-2015-09-15" and "rpi2-ev3dev-jessie-2015-09-15"

### ISSUE THREAD

**Issue by BertLindeman** [ev3dev/ev3dev#389]
'http://www.ev3dev.org/news/2015/09/15/rpi2-ev3dev-jessie-2015-09-15-release' has a pointer to the announcement: 'http://www.ev3dev.org/news/2015/09/15/rpi-ev3dev-jessie-2015-09-15-release' but that page does not exsist. Similar for the rpi2 announcement.

**Comment by dlech** [comment]
Yes, I was too tired last night to finish. :wink:

**Comment by dlech** [comment]
I have traveled back and time and made the announcements.

**Comment by BertLindeman** [comment]
Thank you @dlech for the great work!
