### ISSUE TITLE
print3rbot 40T gear problem

### ISSUE THREAD

**Issue by ihsan-akin** [ev3dev/ev3dev#406]
In the print3rbot, the 40T gears, printed or original, stuck and then tick on the center of the piece with  Beam R. Frame (PID 4540797). You can see from the picture. 
To solve this issue, I'll need the print and cut the R Frame.

![img_20150929_235550](https://cloud.githubusercontent.com/assets/13473590/10178279/7847a1da-6707-11e5-97c2-1c16da4e2fbb.jpg)

Any other suggestions?

**Comment by dlech** [comment]
Is this the printerbot by @cavenel?

**Comment by ihsan-akin** [comment]
Yes, 
http://www.ev3dev.org/projects/2015/05/06/EV3-Print3rbot/

But not he extension.

**Comment by cavenel** [comment]
It would maybe be easier to open an issue directly on the Print3rbot project page: https://github.com/cavenel/ev3-print3rbot/issues
Unfortunately I don't have the original 40T gears to test, didn't have the problem on my printed version, and have a 1 day old baby to take care of ;) 3 reasons that make it difficult for me to solve the issue right now.
I know that others have built the robot with original gear without problem, see https://github.com/cavenel/ev3-print3rbot/issues/2

**Comment by rhempel** [comment]
Congratulations on the new arrival - see you in 16 years :-)

**Comment by cavenel** [comment]
Isn't 16 a bit too old to play Lego? :-p

Any news on this problem? I see a lot of other people building the robot without complaining about this, so it would be interesting to know if there is indeed a problem here.
