### ISSUE TITLE
ev3dev Print3rbot Medium motor running forever

### ISSUE THREAD

**Issue by maceron4444** [ev3dev/ev3dev#411]
I've managed to get the Print3rbot up and running with all the required software, but when I run the writer.py code whatever's connected to motor port B will just run indefinitely regardless of what image I try to draw.

Has anyone else had this issue? Does this happen when the svg image doesn't have any paths? I'm most likely missing something simple here.

Thanks.

**Comment by cavenel** [comment]
Hi!

Please open an issue on the print3rBot page, it will be simpler to track for other users.
https://github.com/cavenel/ev3-print3rbot/issues

Then we can continue discussion there!

**Comment by maceron4444** [comment]
Will do sorry :)
