### ISSUE TITLE
Mono installation on ev3

### ISSUE THREAD

**Issue by pgrudzien12** [ev3dev/ev3dev#423]
I'm trying to install mono-complete package on EV3. I tried same thing on RaspberryPi 2 rpi2-ev3dev-jessie-2015-09-15.img and it was ok. Then tried on EV3 with rpi-ev3dev-jessie-2015-09-15.img. 

I'm stuck with resolving dependencies. Mono-complete needs mono-devel and it in turn needs libgdiplus whitch needs libjpeg8 >= 8c.

EDIT: I initially thought that it is available on rpi2 but it seems that it is not. Nevertheless I will investigate why I was able to install mono-complete on on rpi2 but on ev3 it is not possible at the moment. I always end up with: 

```
root@ev3dev:~# apt-get install mono-complete
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mono-complete : Depends: mono-devel (= 4.0.4.1-0xamarin1) but it is not going to be installed
                 Depends: mono-4.0-service (= 4.0.4.1-0xamarin1) but it is not going to be installed
                 Depends: libmono-cil-dev (= 4.0.4.1-0xamarin1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by pgrudzien12** [comment]
Never mind. I was able to work around this particular problem by installing mono 3.2 and then upgrade.

**Comment by dlech** [comment]
I don't think Xamarin builds all of the packages for the armel architecture, which is what the EV3 is. Raspberry Pi 2 is armhf, which Xamarin does support.

So, on the EV3 you probably have a mix of 3.2 packages from debian and and 4.x from Xamarin.

**Comment by pgrudzien12** [comment]
Thanks @dlech for your support. Although I did not succeed I decided to publish description of my attempt on blog (if you are interested) http://bleedingnedge.com/2015/11/08/asp-net-5-on-lego-mindstorms-ev3-using-ev3dev/ And moreover I opened discussion at DNX repo here: https://github.com/aspnet/dnx/issues/3145

**Comment by pgrudzien12** [comment]
Awesome ! I have true solution. Seems that xamarin have full support for armel: http://origin-download.mono-project.com/repo/debian/dists/wheezy/main/binary-armel/

The problem was I was missing repository for `libgdiplus`:

    echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list

Seemingly RPI2 has libgdiplus alredy installed? Nevertheless I am going to have mono v4 on my ev3 tomorrow and if everything goes well DNX as well.
