### ISSUE TITLE
usbip modules in kernel   usbip-core usbip-host vhci-hcd

### ISSUE THREAD

**Issue by astin1317** [ev3dev/ev3dev#429]
i want to forward usb devices connected to my notebook to the ev3 over network.
for example  usb  gamepad..

**Comment by dlech** [comment]
Sounds like a useful thing to do. I've enabled this in the EV3 kernel and will be available in the next kernel release. It is already enabled in the Raspberry Pi kernels.

**Comment by dlech** [comment]
Fix has been released in kernel 3.16.7-ckt21-9-ev3dev-ev3. More casual users will want to wait for the next image release before updating. See the [announcement](http://www.ev3dev.org/news/2015/12/15/Kernel-Release-Cycle-9/) for more info.
