### ISSUE TITLE
Ultrasonic sensor docs explain LED colors???

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#434]
I was looking at the ultrasonic sensor docs [here](http://www.ev3dev.org/docs/sensors/lego-ev3-ultrasonic-sensor/) and noticed that they say things like:

```
Single measurement
LEDs: On momentarily when mode is set, then off
```

Is this supposed to be there, or was this copied from the LED page and not fully updated?

**Comment by dlech** [comment]
It is supposed to be there. The LEGO EV3 Ultrasonic sensor has LEDs that behave differently depending on the selected mode.

**Comment by WasabiFan** [comment]
Ahhhh I see. I've been testing with my NXT ultrasonic recently and completely forgot that the newer one had those LEDs. Thanks for clarifying!
