### ISSUE TITLE
Alternative to NFS (SSH/SFTP Guide for Wiki)

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev#44]
I forked this repo and added a new page for ssh and sftp. I changed the Home page too.
But i cant pull this to the main repo, so i post this here.

**Comment by dlech** [comment]
If someone would like to start a "File Transfer" section in the tutorials at <http://www.ev3dev.org/docs/tutorials/>, I think that would be a great addition. This is a pretty basic function that everyone needs.
