### ISSUE TITLE
Add anchors for attributes in website documentation pages.

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#450]
Idea from @ddemidov in https://github.com/ev3dev/ev3dev/issues/449#issuecomment-163338196

I think this is a good idea. We can use the javascript function for adding the css class to do this too. However, first we should modify the source code files so that only the attribute name is in the `dt` element.

**Comment by WasabiFan** [comment]
By anchors, you mean anchor elements with an `href` right? So, links? If so, what would be the link target?

**Comment by dlech** [comment]
The link target would be the individual attribute. So, for example, if someone asked "how do motor commands work?", you could answer "http://www.ev3dev.org/docs/drivers/tacho-motor-class/#commands"

**Comment by dlech** [comment]
Actually, anchor might be the wrong terminology. really, all you would need is to add an `id=attribute`

**Comment by WasabiFan** [comment]
OK, that makes sense. In that case it would just be an ID on each -- no links required.

**Comment by dlech** [comment]
right. I was thinking anchor as in `<a name="attribute_name" />`, but I think `id="attribute_name"` does the same thing essentially.

**Comment by dlech** [comment]
Since the driver documentation is moved to readthedocs.org, the anchors are created for that site.
