### ISSUE TITLE
ev3dev on non-EV3 platforms (Rasberry Pi/Brick Pi/PiStorms,  BeagleBone/EVB) propaganda ;-)

### ISSUE THREAD

**Issue by bmegli** [ev3dev/ev3dev#452]
I was going to dissasemble one of my robots and took a "propaganda" movie for ev3dev on RaspberryPi/BrickPi platform (before dissasembling, but ugh, I couldn't make myself to dissasemble it)

The information that ev3dev supports other platforms doesn't seem to be widespread.

http://www.youtube.com/watch?v=dZfVPe_U0yA

Yeah, let's brainwash people a bit ;-)

@dlech - how are you going with BBB/EVB?

We should also document all the quirks of other platforms in one place. If somebody wants to use RPi/BrickPi/PiStorms he should know in advance what will/won't work.

I know those quirks:
- BrickPi - hardware doesn't support breaking in tacho-motor or does it?
- BrickPi - no other-uart mode for sensor
- BrickPi - can we load some custom driver for I2C devices or is it only nxt-i2c-device?

Is that correct, are there some other?

---------------------------------------------------------------------------------------

I am not sure if we want "Cam-Robot" in projects, I like it, I would say it's a classic. The good thing about it is we would have information about making proper power supply (for BrickPi/Raspberry Pi) + gstreamer pipelines + info on camera integration with Lego Technic. 

 Mapping Robot this or other way will be there when I find time.

**Comment by dlech** [comment]
> how are you going with BBB/EVB?

I haven't really touched it yet. (Well I couldn't resist when first got it, so it is booting an image created from brickstrap, but zero drivers implemented yet).

Right now, my priority is getting an image release out that supports PiStorms. Then we can start spreading propaganda about it.

> We should also document all the quirks of other platforms in one place.

Yes, definitely. [Here](https://github.com/ev3dev/ev3dev/issues/412#issuecomment-154242776) is a table that I started on the differences between platforms. 

> I am not sure if we want "Cam-Robot" in projects

We want anything made with ev3dev in projects. :wink:

**Comment by bmegli** [comment]
I probably had some brain malfunction when I was writing this post

I am sorry.

Both robots are ev3dev.

**Comment by dlech** [comment]
I think it is a good post. Just a little premature. :wink:
