### ISSUE TITLE
What is maximum value for the attribute: duty_cycle_sp in a DC Motor?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#473]
Hi,

I was testing DC Motors but I discovered that some values return the following error.

``` bash
root@ev3dev:/sys/class/dc-motor/motor8# echo 50 > /sys/class/dc-motor/motor8/duty_cycle_sp
root@ev3dev:/sys/class/dc-motor/motor8# echo 300 > /sys/class/dc-motor/motor8/duty_cycle_sp
-bash: echo: write error: Invalid argument
```

What is the limit for the property: "duty_cycle_sp"?

I was reading the info about Motors but I didn't find anything:
http://www.ev3dev.org/docs/motors/

I am using latest update:

``` bash
root@ev3dev:/home# uname -a
Linux ev3dev 3.16.7-ckt21-9-ev3dev-ev3 #1 PREEMPT Tue Dec 15 15:16:17 CST 2015 armv5tejl GNU/Linux
```

**Comment by BertLindeman** [comment]
Look at http://www.ev3dev.org/docs/drivers/dc-motor-class/

```
Valid values are -100 to 100 (-100% to 100%).
```

**Comment by jabrena** [comment]
Hi Bert!!

Many thanks, I will update my notes. :D 

Cheers
