### ISSUE TITLE
Our website code is too valid -- titles are broken on mobile now

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#480]
After removing that stray byte from our head template to make our HTML valid, titles are now cut off on mobile. They need more margin above them to not be hidden under the header. Damn HTML validation...

**Comment by dlech** [comment]
Also, `img-responsive` for screenshots doesn't seem to be working on mobile anymore either.

**Comment by dlech** [comment]
Never mind about the images. I think firefox is just being weird. Works in chromium.

**Comment by ddemidov** [comment]
Another small thing about mobile: the main image gets out of borders (android chrome):
![screenshot_20151231-200926](https://cloud.githubusercontent.com/assets/270503/12066557/bf6f8046-affa-11e5-84b8-81367fa68d5a.png)

**Comment by dlech** [comment]
@ddemidov, that image should be fixed now.

**Comment by ddemidov** [comment]
@dlech, confirmed!

**Comment by ddemidov** [comment]
Titles are cut off not only on mobile, but on desktop as well if browser window is thin enough. See #507.

**Comment by ddemidov** [comment]
And another thing: the drop down menus do not do drop down when desktop browser is that thin. That happens when narrow the window, as soon as search box disappears.

**Comment by ddemidov** [comment]
The change proposed by @moriarty in #507 helps with headers cutoff, but not with dropdown menus.

**Comment by moriarty** [comment]
For the dropdown menus, there are currently two drop down links with, docs :

    <a class="dropdown-toggle" data-toggle="dropdown" href="#main-nav" ...

It should be

    <a class="dropdown-toggle" data-toggle="dropdown" href="#" ...

This changes the behaviour, now if you click on a link, dropdown will stay open until you click it closed again. When you hover on the dropdown it will display, and go away when you're not over it. But clicking on it will keep it open until you click on something else. 

The new behaviour is similar to the behaviour in the [default bootswatch darky](https://bootswatch.com/darkly/) preview site which I was comparing it to, except that they do not expand the menus on mouse over.

**Comment by WasabiFan** [comment]
Migrated to ev3dev/ev3dev.github.io#112
