### ISSUE TITLE
Brickman WiFi password prompt needs resized

### ISSUE THREAD

**Issue by G33kDude** [ev3dev/ev3dev#482]
The WiFi password screen you get when connecting to a new network (not the one with the keyboard, but the one just before it) has some clipping issues and needs to be resized.

**Comment by dlech** [comment]
can you get a screenshot with fbgrab?

**Comment by WasabiFan** [comment]
If I remember correctly, this is the one where the buttons are hanging off the bottom of the dialog.

**Comment by dlech** [comment]
@WasabiFan, I fixed #463

**Comment by G33kDude** [comment]
![wifi](https://cloud.githubusercontent.com/assets/437198/12067930/deb4ead8-afd0-11e5-9451-f33b5226520d.png)

**Comment by WasabiFan** [comment]
Oh, I meant that they were hanging off like in the screenshot that @G33kDude posted.

**Comment by dlech** [comment]
I sort of fixed this with <https://github.com/ev3dev/ev3devKit/commit/7be2b3e5b7fd8653cd293a6a5b0871e39a9ca664>. It will still look like the picture above if the SSID is very long, but calling it fixed for now.

**Comment by dlech** [comment]
Fix has been released in `brickman 0.8.0`
