### ISSUE TITLE
A Motor instance to a non-connected motor causes exception when instance is garbage collected

### ISSUE THREAD

**Issue by pootle** [ev3dev/ev3dev#497]
Unless I am doing something silly (I understand I am trying to connect a non existant motor) then this results in an unavoidable rude message:
> from ev3dev.auto import *
> m=Motor(OUTPUT_B)
> m.connected
False
> m=None

Exception AttributeError: "'Motor' object has no attribute '_path'" in <bound method Motor.__del__ of <ev3dev.core.Motor object at 0xb69bd8d0>> ignored

**Comment by WasabiFan** [comment]
This repo is for the ev3dev kernel and core systems. If you are having an issue with one of the Python libraries, please open an issue on the library-specific repo instead.

**Comment by pootle** [comment]
Oops quite right, ddemidov has already got a fix over there, so I'll just close this
