### ISSUE TITLE
CI not picking up empty links on ev3dev.github.io

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#501]
In ev3dev/ev3dev.github.io#97, @WasabiFan and I pointed out a few empty links. When we were getting CI going for the website, I distinctly remember having to fix and empty link like `[something]()`, but now CI does not seem to be catching it.

**Comment by WasabiFan** [comment]
Can we get a definitive build log and markdown example? If it's still there in ev3dev/ev3dev.github.io#97, can you trigger a manual build so we can confirm?

**Comment by dlech** [comment]
I justed added `[bad link]().` to the last paragraph of `support.md` and it fails for me locally with..

```
- ./support/index.html
  *  anchor has no href attribute (line 202)
htmlproof 2.6.1 | Error:  HTML-Proofer found 1 failure!
```

I'll create a PR to see if it fails on travis.

**Comment by dlech** [comment]
Fails as expected. https://travis-ci.org/ev3dev/ev3dev.github.io/builds/102003468

**Comment by dlech** [comment]
> If it's still there in ev3dev/ev3dev.github.io#97, can you trigger a manual build so we can confirm?

This is failing on an image link, but not the others. Maybe htmlproofer stops because of the other error before it gets to this sort of error.

**Comment by WasabiFan** [comment]
Yeah... that's definitely possible. As long as it doesn't let errors through, I don't think it's something we need to worry about.

**Comment by dlech** [comment]
Yup. Tested locally and that was it.
