### ISSUE TITLE
using keyboard to type in ev3dev

### ISSUE THREAD

**Issue by smcri** [ev3dev/ev3dev#505]
can you use keyboard to type in ev3dev?

**Comment by rhempel** [comment]
The bigger problem is can you use the screen to see anything :-) Yes, you can use a USB keyboard to type characters, you just need to tell your program where to get the input from.

**Comment by smcri** [comment]
i used a wireless keyboard.
it worked.
i think i pressed alt + left arrow and i managed to access the command line from the ev3 brick.

**Comment by dlech** [comment]
Yes, you can use a USB or Bluetooth keyboard. You can use it to navigate around brickman using the up, down, left, right, enter and backspace buttons. You can also get a terminal using ALT+CTRL+F6. Other F keys could get you a terminal too, but F6 is *always guaranteed* to get a terminal. Use ALT+CTRL+F1 to return to the main user interface (brickman).

**Comment by smcri** [comment]
can you code in python directly on the brick?

**Comment by dlech** [comment]
Yes. We already discussed this in #466.

**Comment by jabrena** [comment]
Hi, 

One alternative could be show the shell in a smartphone or a tablet to code.

**Comment by dlech** [comment]
I believe the original question has been sufficiently answered.
