### ISSUE TITLE
[website] Navigation bar partly covers page heading.

### ISSUE THREAD

**Issue by ddemidov** [ev3dev/ev3dev#507]
I first saw this on android chrome:

<img src="https://cloud.githubusercontent.com/assets/270503/12371235/ef999afa-bc3d-11e5-8955-c168fd64c935.png" width=300/>

But, if you make the page thin enough, it also happens on desktop chrome:

<img src="https://cloud.githubusercontent.com/assets/270503/12371280/b43e3668-bc3e-11e5-8ec4-773b5db4dff0.png" width=500/>

Also, the search box is not visible when the page is so thin, although there is enough place for it.

**Comment by moriarty** [comment]
Changing margin in .page-heading and adding padding top (to stop the Edit on Github from touching the header) fixed this with Chromium "inspect element". But I don't know where to make that change in the ev3dev/ev3dev.github.io repository, either directly in the bootstrap.css or is it being generated from less?

From following the issues, I think @WasabiFan is the one to have the final say

These settings work:

    .page-header {
        padding-top: 1px;
        padding-bottom: 9.5px;
        margin: 60px 0 21px
        border-bottom: 1px solid transparent;
    }

These settings are the orginal:

    .page-header {
        padding-bottom: 9.5px;
        margin: 42px 0 21px
        border-bottom: 1px solid transparent;
    }

**Comment by moriarty** [comment]
Also, I think this is a duplicate issue with #480

**Comment by ddemidov** [comment]
It does seem a duplicate, closing.
