### ISSUE TITLE
Can the EV3 save sensory input in memory and then access any of the hundreds of them?

### ISSUE THREAD

**Issue by ADVANCESSSS** [ev3dev/ev3dev#513]
Can the EV3 continually save sensory input into memory, and then get access to them all? And also pick out one by a way like first letter or number or if is close to a number (like send the whole array saved up to this point to a check function~) Btw does the Array save them like a index of memory storage?

**Comment by rhempel** [comment]
The EV3 language APIs allow you to read the sensor value by reading the `value*` attribute(s). It is up to your application to store the values in an array or whatever data structure you need.

**Comment by dlech** [comment]
If we ever implement iio on top of our sensor drivers as mentioned in #498 then there could be a way to do this in the kernel driver.

**Comment by ADVANCESSSS** [comment]
dlech er, what are you saying, that what I said won't work? Just wondering why you made a feeling or "it won't work unless" comment...

But it saves em all right? It doesn't just throw out each sense after it shows a binary does it?

**Comment by dlech** [comment]
I'm saying that no one has written a driver that does this, so for now, you have to do what @rhempel says and read individual values and store them yourself.

**Comment by ADVANCESSSS** [comment]
But I'm talking about using the programming-blocks >>> it gets sensory input and then saves them by " " by using a certain block, only blocks are used here no external mod hack ? ? ?

**Comment by dlech** [comment]
What do you mean by programming blocks? The graphical programming language from LEGO?

**Comment by ADVANCESSSS** [comment]
Yes, man...

**Comment by ADVANCESSSS** [comment]
Maybe I didn't specify that above......

**Comment by dlech** [comment]
ev3dev doesn't work with that. Better ask your question somewhere else like http://bricks.stackexchange.com/ or https://www.facebook.com/groups/legomindstorms/

**Comment by ADVANCESSSS** [comment]
Your comment doesn't make sense....

**Comment by ADVANCESSSS** [comment]
dev....I'm not using dev though, just the blocks...

**Comment by dlech** [comment]
This is an issue tracker for [ev3dev.org](http://www.ev3dev.org). We make an alternative operating system for the EV3. If you need help with the official software from LEGO, this is the wrong place to ask.

**Comment by ADVANCESSSS** [comment]
Ok.
