### ISSUE TITLE
Boot manager?

### ISSUE THREAD

**Issue by marecl** [ev3dev/ev3dev#514]
Something like GRUB just to choose between original ev3 os or ev3dev.
Or other os's maybe ;)

**Comment by rhempel** [comment]
Our idea of boot manager is this:

- Original EV3 firmware is no bootable SD card in slot
- ev3dev is an ev3dev SD card in slot

So you get to choose the OS by putting an appropriate SD card in the slot :-)

**Comment by dlech** [comment]
Not likely to happen, but interesting idea. In the meantime, what @rhempel said.
