### ISSUE TITLE
Brickman doesn't finish to load with PiStorms & USB Battery

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#532]
Good Morning,

Today, I started testing PiStorm with a old RaspberryPi 1.
In the screen I see BrickPi loading:
https://pbs.twimg.com/media/CaMxAn4WYAAq85u.jpg:large

but after 15m. the screen continues in the same status.
What is the problem?

I updated config.txt in the right way enabling the line about PiStorm.

PiStorm is running with a Raspberry pi 1 and I am using a USB Battery connected to Raspberry Pi.

Juan Antonio

**Comment by dlech** [comment]
You need to power the PiStorms via the power connection on the PiStorms itself. And you probably need more than the 5V supplied by USB.

**Comment by jabrena** [comment]
Using external battery provided by @mindsensors, the doubt was fixed.
Demo: https://twitter.com/juanantoniobm/status/694973523157188608
