### ISSUE TITLE
Is touchable Brickman on BrickPi?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#533]
Good evening,

I was starting to use EV3Dev with Brickpi but I can't use the screen.
Brickman has touch features to navigate on the menu?
Besides If I observe, Brickpi doesn't have a back button, so how to go back from a internal menu to main menu?

Juan Antonio

**Comment by WasabiFan** [comment]
I believe you need to use an external keyboard for now. Arrows navigate, enter key selects, and backspace goes back (escape might also work).

**Comment by jabrena** [comment]
For me, is  Ok. I will test tomorrow.
I will try to get a internet connection.

Cheers

**Comment by dlech** [comment]
I think you mean PiStorms and not BrickBi. See #426. For now you need to plug in an external keyboard/keypad.
