### ISSUE TITLE
PiStorms // How to use a NXT Ultrasonic Sensor

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#540]
Good afternoon,

I am testing some NXT Sensors on PiStorms and I would like to use a NXT US Sensor:
http://shop.lego.com/en-US/Ultrasonic-Sensor-9846

Currently if try to see lego sensors connected to piStorms, I can't see anything:

``` bash
robot@ev3dev:/sys/class$ cd lego-sensor/
robot@ev3dev:/sys/class/lego-sensor$ ls
```

If I use lego-ports way, I see the following modes:

``` bash
robot@ev3dev:/sys/class/lego-port$ cd port1
robot@ev3dev:/sys/class/lego-port/port1$ ls
address  device  driver_name  mode  modes  set_device  status  subsystem  uevent
robot@ev3dev:/sys/class/lego-port/port1$ cat address 
pistorms:BBS2
robot@ev3dev:/sys/class/lego-port/port1$ cat modes 
none nxt-analog nxt-color i2c-thru ev3-analog ev3-uart
```

What is the best mode to use the NXT US Sensor?

Cheers

Juan Antonio

**Comment by dlech** [comment]
The LEGO NXT Ultrasonic sensor is not supported on PiStorms for technical reasons. 

http://www.mindsensors.com/forum/topic/151_nxt-ultrasonic-sensor-in-pistorms
