### ISSUE TITLE
Can't set or read the speed of tachomotors

### ISSUE THREAD

**Issue by jfcloutier** [ev3dev/ev3dev#543]
I installed the linux-image-4.1.15-10-rc2-ev3dev-rpi2_1_armhf.deb package.

I can not specify the speed and I can not read the current speed of a tachomotor

    robot@ev3dev:/sys/class/tacho-motor/motor0$ cat speed
    cat: speed: Operation not supported
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo 4 > speed_sp
    -bash: echo: write error: Operation not supported
    robot@ev3dev:/sys/class/tacho-motor/motor0$ cat speed_sp
    0

**Comment by dlech** [comment]
This is currently not implemented for BirckPi.

**Comment by dlech** [comment]
Again, this would be best solved by modifying the BrickPi firmware.

**Comment by dlech** [comment]
Somewhat related: http://www.dexterindustries.com/topic/accuracy-of-rotating-a-motor/

**Comment by jfcloutier** [comment]
That's surprising. Setting/reading motor speed is kind of important. Let's hope Dexter fixes their firmware soonish.

**Comment by dlech** [comment]
Found a great paper on calculating motor speed.

http://www.diegm.uniud.it/petrella/Azionamenti%20Elettrici%20II/Tesine/Petrella%20et%20al.%20-%20Speed%20Measurement%20Algorithms%20for%20Low-Resolution%20Incremental%20Encoder%20Equipped%20Drives_a%20Comparative%20Analysis.pdf

**Comment by WasabiFan** [comment]
@dlech Are you saying that that paper helps you bypass the firmware limitations so that you can measure motor speed?

**Comment by dlech** [comment]
I would say it explains all of the options so that we can make the best choice given the constraints we have to work with.

**Comment by dlech** [comment]
This fix has been released in the `4.1.21-10-ev3dev-rpi` kernel. Be aware the tacho-motor class has breaking changes in this release, so don't expect motors to work with your existing programs/libraries if you upgrade to this version.
