### ISSUE TITLE
Changing the polarity of a tachomotor has no effect

### ISSUE THREAD

**Issue by jfcloutier** [ev3dev/ev3dev#545]
I installed the linux-image-4.1.15-10-rc2-ev3dev-rpi2_1_armhf.deb package.

Inverting polarity has no effect

    robot@ev3dev:/sys/class/tacho-motor/motor0$ cat polarity
    normal
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo run-forever > command
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo stop > command
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo inversed > polarity
    robot@ev3dev:/sys/class/tacho-motor/motor0$ cat polarity
    inversed
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo run-forever > command
    robot@ev3dev:/sys/class/tacho-motor/motor0$ echo stop > command

The motor's effective polarity was no changed.

**Comment by dlech** [comment]
We have decided to not implement polarity this way. See #601.

With the example given in the opening comment, it is expected that the polarity will not change. However, this will change the polarity....

robot@ev3dev:/sys/class/tacho-motor/motor0$ cat polarity
normal
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo 400 > speed_sp
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo run-forever > command
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo stop > command
robot@ev3dev:/sys/class/tacho-motor/motor0$ cat speed_sp
400
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo inversed > polarity
robot@ev3dev:/sys/class/tacho-motor/motor0$ cat polarity
inversed
robot@ev3dev:/sys/class/tacho-motor/motor0$ cat speed_sp
-400
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo 400 > speed_sp
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo run-forever > command
robot@ev3dev:/sys/class/tacho-motor/motor0$ echo stop > command
