### ISSUE TITLE
my ev3 wont boot into ev3dev

### ISSUE THREAD

**Issue by spike11302000** [ev3dev/ev3dev#560]
every time i try to boot into the sd it will not boot

**Comment by jabrena** [comment]
Good morning @spike11302000,
 
maybe the sd card had some problem. Did you test to change your sd card? Are you checked that the sd card was burned with the image?

Juan Antonio

**Comment by harmooni** [comment]
Hello @spike11302000,

(Just like @jabrena suggested) I also recommend plugging the SD Card in your PC, and check if you can see the ev3dev system.
Which operating system did you use to flash your SD Card?

**Comment by dlech** [comment]
Did you unzip the image file before writing to the SD card?

**Comment by spike11302000** [comment]
yes i have unzip and try different sd cards

but i can boot into jelos. [http://www.lejos.org/]

**Comment by spike11302000** [comment]
im running ubuntu and i follow this [http://www.ev3dev.org/docs/tutorials/writing-sd-card-image-ubuntu-disk-image-writer/]

**Comment by dlech** [comment]
If you plug the SD card into your computer do you see the `EV3DEV_BOOT` and `EV3DEV_ROOT` partitions? 

Do the lights change from red to orange/amber or flash when booting? 

Do you have a serial cable you can use for debugging?

**Comment by spike11302000** [comment]
i see rootfs and boot

**Comment by spike11302000** [comment]
do i need to rename them?

**Comment by dlech** [comment]
no need to rename. and the other questions?

also, make sure nothing is plugged into the EV3 (input ports, output ports and USB).

**Comment by spike11302000** [comment]
there is nothing else plugged in

**Comment by spike11302000** [comment]
could it be my ev3?

**Comment by dlech** [comment]
Doubtful that it is your EV3 if leJOS and the official firmware work.

You still have not answered the other questions.

Do the lights change from red to orange/amber or flash when booting? Do you see the ev3dev logo on the screen?

Do you have a serial cable you can use for debugging on input port 1?

**Comment by spike11302000** [comment]
no the light dont change

and what do you mean serial cable, like usb to serial?

**Comment by spike11302000** [comment]
it just boot normally

**Comment by spike11302000** [comment]
no ev3dev logo

**Comment by dlech** [comment]
what (official) firmware do you have in your EV3?

**Comment by spike11302000** [comment]
i dont know

i think i need to update

**Comment by dlech** [comment]
> and what do you mean serial cable, like usb to serial?

yes

**Comment by spike11302000** [comment]
ok then i have a serial cable

**Comment by dlech** [comment]
update your firmware first. if you have a 3.3V usb/serial adapter, you can attach it like [this](http://botbench.com/blog/2013/08/15/ev3-creating-console-cable/) and it will hopefully give more info.

**Comment by dlech** [comment]
actually a 5V adapter is OK too. just not more than 5V.

**Comment by spike11302000** [comment]
ok
i will try that

**Comment by spike11302000** [comment]
and i did not know you can get serial data from the ports

**Comment by spike11302000** [comment]
can you run a webserver on ev3dev?

**Comment by spike11302000** [comment]
just woundering

**Comment by dlech** [comment]
yes, you can run a webserver.

**Comment by spike11302000** [comment]
can it run php?

**Comment by dlech** [comment]
sure. it can run just about anything (that doesn't take up too much memory).

**Comment by spike11302000** [comment]
ok
cough cough minecraft server

**Comment by markosko** [comment]
not enough processing power ev3 has only 300MHz processor

**Comment by spike11302000** [comment]
i know

**Comment by spike11302000** [comment]
ok im updating my ev3 now

**Comment by spike11302000** [comment]
ok i updated to v1.09h and it still wont boot

**Comment by spike11302000** [comment]
and can you boot from the usb port?

**Comment by dlech** [comment]
not without compiling your own bootloader

**Comment by dlech** [comment]
If leJOS boots from the SD card and ev3dev won't, I'm not sure what could be wrong, sorry.

**Comment by spike11302000** [comment]
ok
 im making the serial cable right now so i can see what worng


and can you send me pictures so i can see what on the partions of the sd card

**Comment by laurensvalk** [comment]
Not sure it's related, but I occasionally experience that it will not boot into ev3dev. Instead it boots the standard FW from flash. The following works for me:

- Turn the EV3 on.
- In the main menu of the standard firmware, go to the Files tab.
- After some time, you will see the SD card there
- Open that folder. If you can, you know that it's mounted.

Then, shut down the brick through the menu, wait for it to shut down, and launch again. For me this consistently solves my problem, which usually happens the first time after flashing the card. (But not always.)

**Comment by spike11302000** [comment]
ok i will try doing that

**Comment by spike11302000** [comment]
this mite help

it says cant find boot.src on the sd card

**Comment by dlech** [comment]
does `boot.scr` exist in the `EV3DEV_BOOT` partition?

It sounds like the u-boot bootloader is not mounting the sd card properly, which is why @laurensvalk's workaround might help.

does is say anything else besides "cant find uboot.scr"?

**Comment by spike11302000** [comment]
[http://i.imgur.com/pmdzRFC.png](url)

**Comment by spike11302000** [comment]
http://i.imgur.com/pmdzRFC.png

**Comment by spike11302000** [comment]
sorry did the link wrong one the first one

**Comment by spike11302000** [comment]
![screenshot from 2016-03-07 14 57 46](https://cloud.githubusercontent.com/assets/12355526/13585867/bb783f1a-e483-11e5-9ac7-dd9cce288eaf.png)

**Comment by dlech** [comment]
You are using the EVB image for BeagleBone Black, so of course it doesn't work on the EV3.

 Try the EV3 image: https://github.com/ev3dev/ev3dev/releases/tag/ev3dev-jessie-2015-12-30

**Comment by spike11302000** [comment]
ok..

**Comment by markosko** [comment]
i misdownloaded same image at first :D

**Comment by spike11302000** [comment]
ok make sence no

**Comment by spike11302000** [comment]
thank for the help

**Comment by WasabiFan** [comment]
@dlech what can be done to name the image files so that they are more obviously different? I imagine that expanding the name in the image file would be a good start ("evb" -> "beaglebone-evb"). Past that, what else could be done? In my mind, the best case would be to have that downloads page on the site that we've wanted so that we can have large title headings.

**Comment by dlech** [comment]
normally, all of the images are listed in a single release. however, there was a special release that contains EVB only. this is probably what is throwing people off. I added some capital letters that will hopefully help.
