### ISSUE TITLE
Brickman runs programs from home rather than current directory.

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/ev3dev#575]
Can be reproduced as follows:

Say you have a script /home/robot/testdir/showdir.sh:

```
pwd
sleep 2
```

When on a terminal, going into the folder and running the script we get, as expected:

```
robot@ev3dev:~$ cd testdir/
robot@ev3dev:~/testdir$ ./showdir.sh 
/home/robot/testdir
```

But in brickman the display reads:
```
/home/robot
```

**Comment by dlech** [comment]
Fix has been released in `brickman 0.8.0`
