### ISSUE TITLE
Device Browser > Sensors: Mode string does not change when changing mode

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/ev3dev#576]
To reproduce: In Brickman, go to Device Browser > Sensors > Select any sensor with more than one mode (e.g. Gyro or IR) > Set mode > Pick a different mode.

Problem: the new mode appears not to have been selected. Old mode still shown in menu.

However, when you go to Watch values, it is actually changed, as I now see deg/s instead of deg for the Gyro.

So perhaps it's just the mode string on the display that is not updated.

**Comment by dlech** [comment]
I think this was actually a kernel issue fixed by https://github.com/ev3dev/lego-linux-drivers/commit/0fd08f7c52dbdabf5ee6fd8bc2a6814d1ba1ab8f

Can you confirm that this is fixed with kernel release 10 or higher?
