### ISSUE TITLE
Python API install problem

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev#599]
I'm having trouble setting up my Python API. Could you help me?
![capture8](https://cloud.githubusercontent.com/assets/18370992/14407360/0e80146a-fe94-11e5-8eec-e06dc22d492a.PNG)

**Comment by dlech** [comment]
Not exactly sure what you are trying to do. This is why we ask you to answer all of the questions each time you open a new issue.

ev3dev-lang-python comes preinstalled so there is nothing to setup. If you have further questions about ev3dev-lang-python, have a look at https://github.com/rhempel/ev3dev-lang-python and open an issue there if you get stuck.

**Comment by Johnny-West** [comment]
I'm trying to get a python script into the EV3.

**Comment by WasabiFan** [comment]
@Johnny-West Although it would be great if you could provide some more information, I think I might be able to help you. Try running `sudo apt-get install git` and then try what you were doing again.

**Comment by Johnny-West** [comment]
It isn't working. Any other solutions?

**Comment by sudharsh** [comment]
I also noticed that you are doing an `import` from the shell, hence the command not found error. Try running `python` from the shell which will drop you in the interpreter. Your import statements will work then.
