### ISSUE TITLE
IRC anyone?

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#60]
Even though we don't exactly have a massive following at this point, I thought it might be useful/fun to have an IRC channel, so I have set one up - \#ev3dev on irc://irc.freenode.net. It is logged so you can ask a question and come back in a couple of days and see if anyone responded.

**Comment by MolarAmbiguity** [comment]
I feel like this IRC should be documented on ev3dev.org. I've been following this project for a few months now and only found about it today. Any thoughts?

**Comment by theZiz** [comment]
Same here, I planed to join there in future, too, after I figured out, that there is a channel at freenode.

**Comment by G33kDude** [comment]
#ev3dev on freenode

**Comment by MolarAmbiguity** [comment]
@G33kDude, that seems sane. I'll send a pull request through.

**Comment by dlech** [comment]
I like the idea of adding a link to the "Community" menu. Not sure about what to call it though. I would like it to be more than just IRC. Maybe "Social" or "Discuss". The page it links to would of course include info about the IRC channel. It could also include links to https://www.facebook.com/groups/legomindstorms or https://mindboards.trella.biz/ if anyone is interested in those sites.

**Comment by rhempel** [comment]
We probably want a place that's just a bit more accessible than IRC for some aspects of ev3dev - do we want to consider a Facebook group where we announce neat projects, and leave the developer stuff on IRC or github as issues?

**Comment by dlech** [comment]
IRC should be available for anyone that want to "just chat" about ev3dev, not just "developer" stuff. But I do agree that we should have a more "moder" outlet too. Although I am not a fan of Facebook, that seems to be where most people are at these days, so I'm for either piggy-backing on the existing legomindstorms group or starting a new ev3dev group on Facebook.

Our existing www.ev3dev.org website already has a news feed (atom) for announcing stuff too.

**Comment by MolarAmbiguity** [comment]
I would say steer away from facebook. Perhaps reddit would be better? There already is a mindstorms subreddit, which is moderatively active. Is the mindboards forums still a good spot?

**Comment by rhempel** [comment]
I'm not a big fan of Facebook here, but that's where most people hang out. I had my head in the sand on Facebook for a long time before I joined, but I have to say it's a powerful way to get people to share. We have to think beyone reaching our little echo-chamber of hard-core users and let more people know about ev3dev.
For instance, did you know there's a Ruby developer in Japan that's using ev3dev to demonstrate robotics concepts? I shared it on my Facebook site :-)
Asking people to document their creations in the format we want is a hurdle - I would like to see a lower barrier for people to share their creations.

**Comment by G33kDude** [comment]
As for LEGO related IRC channels, I know of ##Mindstorms (I made this one recently for /r/Mindstorms), #ev3dev, #brickset, and #brickipedia. For subreddits I'm familiar with /r/AFOL, /r/LEGO, /r/Mindstorms, and /r/FLL. For mindstorms related forums I know of mindboards and LeJOS. Not sure how much if any of my list is relevant.

**Comment by rhempel** [comment]
That's exactly my point - there are almost too many choices. ev3dev.org is where the official docs live, we have real-time chats on our #ev3dev IRC channel (thanks Dave L for setting up both of those) - I think we need to start with a single, popular, low barrier social media platform. Reddit requires yet another registration - on the minus side, a lot of privacy minded developers avoid Facebook - so we have to consider that too.

**Comment by MolarAmbiguity** [comment]
reddit is preferable to Facebook though, as you can actually see the content without being registered.

**Comment by G33kDude** [comment]
Reddit's registration system is super simple and anonymous, and a lot of tech minded people already have accounts. It's pretty bad from an archival standpoint, though.

**Comment by rhempel** [comment]
I have an account - I'm not too concerned about archiving discussions - if it's important enough to archive, then it goes on the github issues list - I would discourage tech support type discussion on Facebook, the geek talk would scare away users :-)

**Comment by dlech** [comment]
> I think we need to start with a single, popular, low barrier social media platform.

Facebook seems like the only one that fits the bill here.

**Comment by MolarAmbiguity** [comment]
Perhaps we should poll the current community, to see what is prefered?

**Comment by G33kDude** [comment]
> Single

Bwaha, there are so many splintered groups on facebook. Kinda hard to find a unified community there.

> Popular

Facebook is definitely on the decline, but still fairly popular.

> Low barrier

Facebook is pretty far from low barrier and it's very bad for anonymity, which is a main point for many developers.

---

Another thing to consider is the available moderation tools on a given platform. I'm not familiar with Facebook's, but reddit seems to have pretty good moderation tools all things considered.

**Comment by rhempel** [comment]
Splintering is the enemy of groups - I hate to be the old man here, but everyone should read this if they are unfamiliar with it: <http://www.shirky.com/writings/herecomeseverybody/group_enemy.html> written in 2003 and just as valid today.
I was around for the awesome rise of Todd Lehman's Lugnet - one of the first truly great social network sites for LEGO - great discussions, filterable news, read/write via email if you wanted. And quickly died when Facebook came on the scene.

**Comment by MolarAmbiguity** [comment]
@rhempel I agree. No solution is perfect and you need to avoid having 10 different places to talk about something. Especially for something as small as ev3dev.

**Comment by WasabiFan** [comment]
@dlech Separate topic, but on that page on `ev3dev.org` that you were describing you could think about adding a web client for quick IRC access: http://webchat.freenode.net/. They have a button in the nav for creating `iframe` links.

**Comment by rhempel** [comment]
You mean like a page that IS the IRC client? That would be really cool! Does that impose a high traffic load through ev3dev.org, or does the web client connect the users's web session directly to IRC.
Sorry for my ignorance on this.

**Comment by G33kDude** [comment]
Having a web client in an iframe is a pretty bad idea I think. Best to let it be its own tab, with a proper tab title. Wouldn't want people to accidentally open it in multiple ev3dev pages, or not see channel activity. It'd also be extra weight on freenode's servers.

@rhempel It's qwebirc if you want to learn more

**Comment by MolarAmbiguity** [comment]
If people want to do chat on the web they can join at: http://webchat.freenode.net/?channels=ev3dev

**Comment by WasabiFan** [comment]
> You mean like a page that IS the IRC client? That would be really cool! Does that impose a high traffic load through ev3dev.org, or does the web client connect the users's web session directly to IRC.

It's just some AJAX requests or a single socket open to Freenode's servers (depending on the browser).

> Having a web client in an iframe is a pretty bad idea I think. Best to let it be its own tab, with a proper tab title.

I'm not saying that we should invite someone to use this window as their primary client, I'm just saying it would be helpful for some if there was a title like "Need quick help with ev3dev? Chat with us over IRC below!" on that page. You could then include more info on opening it in a new tab or downloading a client. This would just lower the barrier to entry.

**Comment by G33kDude** [comment]
If I see a popup advertising quick in-site live help I usually nope right out of there. Also note that there are more clients than just freenode's qwebirc instance. KiwiIRC is a popular choice, and we at the AutoHotkey community have been recommending it due to its prominent display of the channel topic.

**Comment by WasabiFan** [comment]
> If I see a popup advertising quick in-site live help I usually nope right out of there.

I understand, I do the same -- and that would be a problem that would have to be looked into/mitigated. Personally, I can tell what's a scam and what's not: especially if it provides context, such as "#ev3dev on Freenode.net". But other users that aren't as capable with these things might not be aware of this, and as you say it could cause problems.

> Also note that there are more clients than just freenode's qwebirc instance. KiwiIRC is a popular choice...

That looks like an available option as well, and looking at their website it definitely looks better at a quick glance. I'm not trying to suggest a specific client widget, just the idea to consider.

**Comment by G33kDude** [comment]
I'm up for a poll, but does GitHub even support polls? First we need a platform that supports polls to do a poll on which platform to use

**Comment by MolarAmbiguity** [comment]
strawpoll is a common solution, I don't know if its any good.

**Comment by dsharlet** [comment]
I suggest using a mailing list. They're pretty much universally accessible,
and ones like google groups archive discussions and make them searchable.

**Comment by moriarty** [comment]
My 2-cents:

The problem with mailing lists, is there is a lot of people use them differently. Someone asks a question and then on user replies in line, another at the end.

**Comment by moriarty** [comment]
My 2-cents: (edited because I hit comment accidentally, you can't delete a comment on github and it doesn't let you use markdown preview when updating a comment.)
 
The platform depends on what you want out of it. 
Is this for sharing? for support? for expanding the community?
Support -> GH Issues, IRC.
Sharing -> Facebook vs Reddit
Community -> FB vs Reddit vs IRC. 

Long story short, I vote for FB for sharing but keeping GHI & IRC. 

I wrote a big list of pros and cons with block quotes addressing the above mentioned issues but that amount of text is something for a reddit post not a GH Issue comment. 

I know for documentation you're moving away from the github wiki but perhaps we could use it to do the pros and cons list and a vote, seeing as everyone is already on Github.

**Comment by ddemidov** [comment]
Just a random link: https://gitter.im/

**Comment by dlech** [comment]
This has turned into quite a discussion! (I like it)

Getting back to the original issue here: since we have an IRC channel, there should be something on www.ev3dev.org about it.

Based on the discussion so far, this is what I am envisioning...

Right now, we have a *Community* menu as follows:

    +-------------+
    | Community v |
    +------------------+
    | Projects Gallery |
    +------------------+
    | Contributing     |
    +------------------+
    | Issues           |
    +------------------+

I'm thinking we change it to:

    +-------------+
    | Community v |
    +-------------+
    | Share      |
    +------------+
    | Contribute |
    +------------+
    | Get Help   |
    +------------+

The *Share* page has links to our existing *Projects Gallery* and presuming we start a Facebook group, it would go here too.

The *Contribute* page is the existing *Contributing* page about how to contribute to the ev3dev platform itself.

The *Get Help* page will have the existing info about using GitHub Issues. I think this is where IRC fits in.

**Comment by G33kDude** [comment]
I never did like gitter, though not for any specific reason. The new menu layout you've suggested seems reasonable, but I still think reddit would be a far better choice over Facebook.

**Comment by WasabiFan** [comment]
> Based on the discussion so far, this is what I am envisioning...

That's what I was thinking too. I think that menu change and new page would make finding info about ev3dev easier.

Along with that, I think it would be great if we separated all the info on the homepage into separate pages. Opening the homepage of a website to find a wall of text is not something that seems inviting to most. The current page is mostly a copy of the contents of our README from a few months ago.

**Comment by rhempel** [comment]
Agree with WasabiFan - wall of text is intimidating. Your proposed new front page structure looks good @dlech

**Comment by theZiz** [comment]
I think, who is able to install and use (!) ev3dev, should also be able to install and use an IRC client (or an web client).

Furthermore imho Facebook is a bad idea. There are always people not wanting to join it. I didn't work much with reddit yet, but in fact I don't like the site - but that's probably just me, I could life with it. Just using Facebook because much people using it, is not a good argument imo. If someone wants to participate or to ask questions, I think a quick registration isn't such a big problem.

Until now (if I doesn't overlook something) nobody suggested just a simple good old Bulletin Board like https://mindboards.trella.biz/ I know, it was discuessed to add this, but not to make a new one especially für ev3dev. The big question is: Shall the community be about programming mindstorms in general or "just" about ev3dev? For https://mindboards.trella.biz : Until now I didn't even know, that is exists - and I searched for such a board (so thanks). However the certificate of the https seems to be broken. I got a warning...

**Comment by rhempel** [comment]
OK, but I think we want to find new users that may not know how to use IRC or install ev3dev yet - we want to find parents that want to help their kids learn robotics or Linux, or teachers that would like to give their advanced students busy :-)
The community is for ev3dev only - it needs focus - we can't be yet another general Mindstorms site.
Keep the discussion going though...

**Comment by dsharlet** [comment]
I still think a mailing list would be good. I can't think of a single open source project I've either been involved with or been a user of that does *not* use a mailing list as its primary means of developers communicating with users. This is for everything from tiny projects all the way up to massive projects Clang/LLVM. Particular mailing list solutions also offer forum-like interfaces (to the same discussions) where you can browse/search past threads and post. Google groups does this, I'm sure others do too.

**Comment by MolarAmbiguity** [comment]
I think what we've established is that there are many different things people want to talk about. Not all these things need to be in the same place. For instance:

I think I found a bug/something is not working (should go on github/LegoAnswers?)
Hey look what I made! (currently submitted through github, probably going to change)
I want live support/talk/development (IRC channel.)
General asynchronous communitcation (github kinda at the moment? Probably would be good on a mailing list or subreddit) 

Theres probably more things people want to talk about, I will add them to this list as I/you think of them.

**Comment by dlech** [comment]
I've made the changes that I proposed. I embedded the Kiwi IRC client as suggested. It looks pretty cool.

http://www.ev3dev.org/support/#irc

**Comment by dlech** [comment]
I can't think of anything that a mailing list does that GitHub issues does not already do, so I don't see a need for a mailing list. Well, I partly take that back. GitHub issues are not good for announcements. Our news page has a RSS feed (atom really), but I suppose some people might like to subscribe to that via email.

**Comment by dlech** [comment]
I'm closing this issue since we now have a bit about IRC on the www.ev3dev.org site. Since the discussion evolved to be bigger than just IRC, if there are any suggestions or other concerns that you feel like were not addressed, please start a new issue and we will continue the conversation.
