### ISSUE TITLE
Remove encoder_polarity attribute in tacho-motor class

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#600]
As it currently stands, the encoder polarity is selected by selecting a motor driver (e.g. `fi-l12-ev3-50`). There is really no longer a need for the `encoder_polarity` attribute to be exposed to userspace.

**Comment by rhempel** [comment]
I agree - the encoder polarity was helpful when we did not have specific motor drivers. It's no longer needed so I'm OK with getting rid of it.

**Comment by dlech** [comment]
This fix has been released in the `3.16.7-ckt26-10-ev3dev-ev3` kernel (an other `10-ev3dev` kernels on other platforms). Be aware the tacho-motor class has breaking changes in this release, so don't expect motors to work with your existing programs/libraries if you upgrade to this version.
