### ISSUE TITLE
Linux kernel/Git download issues

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev#602]
I'm having problems with my EV3 build because it contains some errors inside the Linux kernel. Can you fix this?
![capture9](https://cloud.githubusercontent.com/assets/18370992/14408094/7caaac6e-feb4-11e5-8fa9-08081d84feea.PNG)

**Comment by dlech** [comment]
Make sure your EV3 is connected to the Internet, then run

    sudo apt-get update

then run `sudo apt-get install` again.

**Comment by Johnny-West** [comment]
I tried, and they said:

```
Err http://ev3dev.org jessie InRelease

Err http://ftp.debian.org jessie Release.gpg
  Temporary failure resolving 'ftp.debian.org'
Err http://ev3dev.org jessie Release.gpg
  Temporary failure resolving 'ev3dev.org'
Reading package lists... Done
W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/InRelease

W: Failed to fetch http://ev3dev.org/debian/dists/jessie/InRelease

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'ftp.debian.org'

W: Failed to fetch http://ev3dev.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'ev3dev.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

```

So this is a big problem. Would you mind fixing it?

**Comment by rhempel** [comment]
First, you need to make sure that your EV3 is actually able to access the Internet - can you `ping` anywhere outside your local network?
Have you followed the instructions in http://www.ev3dev.org/docs/tutorials/ related to connecting to the Internet under Networking?

**Comment by psychemedia** [comment]
I'm having terrible problems with updating packages - networking is fine (I can install some things) but the packages I really need are just coming back as `E: Unable to locate package WHATEVER`

The `apt-get` update also fails to complete cleanly... It hangs at the end:

```
Ign http://ftp.debian.org jessie InRelease         
Hit http://ftp.debian.org jessie Release.gpg       
Hit http://ftp.debian.org jessie Release
Hit http://ev3dev.org jessie InRelease                 
Get:1 http://ftp.debian.org jessie/main armel Packages [6,622 kB]
Hit http://ev3dev.org jessie/main armel Packages        
Ign http://ev3dev.org jessie/main Translation-en_US                            
Ign http://ev3dev.org jessie/main Translation-en                               
Get:2 http://ftp.debian.org jessie/contrib armel Packages [37.1 kB]            
Get:3 http://ftp.debian.org jessie/non-free armel Packages [59.6 kB]           
Hit http://ftp.debian.org jessie/contrib Translation-en                        
Get:4 http://ftp.debian.org jessie/main Translation-en [4,581 kB]              
Get:5 http://ftp.debian.org jessie/non-free Translation-en [72.5 kB]           
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]                          
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]
100% [4 Translation-en bzip2 0 B] [1 Packages xz 0 B]^Crobot@ev3dev:~$
```

It would be really handy if the distribution included `git`, `pip` and `python-dev` (maybe `build-essential ` as well?)

**Comment by dlech** [comment]
`sudo apt-get update` should fix you up.

We will be including `git` by default in the next image release. I believe `easy_install` is already included. Building on the EV3 is so slow, we don't bother including `build-essential` or `python-dev`. Feel free to open a new issue if you think they should be included.

**Comment by psychemedia** [comment]
I've run `sudo apt-get update` repeatedly and it doesn't help.... `git` is one of the packages not recognised, as is `python-dev`. I had things working with an old version of ev3dev this morning, but since upgrading to a reflashed `ev3dev` at lunch time I've just gone backwards through not being able to load packages. (It took 90 mins of dancing between `easy_install` and `pip` (the latter loaded from source) to get `ipython` installed, and the kernels still don't run properly because I can't build `pyzmq`.)

**Comment by dlech** [comment]
Have you waited for `apt-get update` to finish without aborting it? It does take a very long time - especially the first time you run it, you just have to wait and it will eventually finish.

Debian has an [older version of IPython](https://packages.debian.org/hu/source/jessie/ipython) already packaged. Would this work?

**Comment by psychemedia** [comment]
I ended up leaving it to update overnight and it seems to have run to completion at some point during that period  - thanks... I guess I was too hasty assuming it was stuck when it had apparently stalled for >5000s at a time. Doh!

**Comment by moriarty** [comment]
At the beginning I let installations and compiles run overnight on the brick... But watch out, sometimes they'll run out of ram & swap.

It is usually quicker to set up a brickstrap environment, sync your /home/robot/ directories (or anywhere else you were working), install or compile what you need and create a new SD card, or copy what you need form the brickstrap environment back to the brick.

**Comment by psychemedia** [comment]
@moriarty Thanks for the brickstrap tip - I'll explore that. Is there a base dockerfile anywhere that can kickstart that process?

**Comment by moriarty** [comment]
Not to my knowledge. Actually I was thinking of making a docker image earlier today- but then got distracted with another docker project I stumbled on

**Comment by online4ever** [comment]
robot@ev3dev:~$ sudo apt-get update
[sudo] password for robot:
Get:1 http://ftp.debian.org jessie InRelease
100% [1 InRelease gpgv 5,620 B]Splitting up /var/lib/apt/lists/partial/ftp.debiaIgn http://ftp.debian.org jessie InReleaseata and signature failed
E: GPG error: http://ftp.debian.org jessie InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
robot@ev3dev:~$ ping google.de
PING google.de (172.217.18.163) 56(84) bytes of data.
From p4FE3A785.dip0.t-ipconnect.de (79.227.167.133) icmp_seq=1 Packet filtered

... does anybody know what is going wrong?

User is robot and password is maker?

**Comment by dlech** [comment]
Maybe try a different debian mirror<sup>[1]</sup> or use the HTTP redirector<sup>[2]</sup>. Edit `/etc/apt/sources.list` as root (e.g. `sudo nano /etc/apt/sources.list` and change `ftp.debian.org` to `httpredir.debian.org`.

[1]: https://www.debian.org/mirror/list
[2]: http://http.debian.net/

**Comment by online4ever** [comment]
Even I changed ... same result.

**Comment by dlech** [comment]
Maybe your ISP is blocking the file. Can you browse to <http://archive.ev3dev.org/debian/dists/jessie/InRelease>? (or `wget http://archive.ev3dev.org/debian/dists/jessie/InRelease` on the EV3)

**Comment by rhempel** [comment]
If the ISP is blocking the file, then it those commands might fail on his main computer as well, or there could be a firewall on his shared internet connection preventing the download.

**Comment by moriarty** [comment]
You're in Germany?

I know that some university networks block port ranges on the Eduroam networks (including ssh + ftp, which is really annoying) and that some student dormitory networks block shared internet connections (studentenwerk Bonn)

**Comment by online4ever** [comment]
Hi all,

yes I come from Germany a village near Karlsruhe called Leopoldshafen. I have an ordinay T-Online DSL 16 MBit access over a Fritz!Box 7490. So nothing special at all. Hear are my wget results ...

robot@ev3dev:~$ wget http://archive.ev3dev.org/debian/dists/jessie/InRelease
--2016-04-27 14:58:56--  http://archive.ev3dev.org/debian/dists/jessie/InRelease
Resolving archive.ev3dev.org (archive.ev3dev.org)... 206.190.152.46
Connecting to archive.ev3dev.org (archive.ev3dev.org)|206.190.152.46|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://fritz.box/tools/kids_not_allowed.lua?account=ip-192.168.178.39 [following]
--2016-04-27 14:58:56--  http://fritz.box/tools/kids_not_allowed.lua?account=ip-192.168.178.39
Resolving fritz.box (fritz.box)... 192.168.178.1
Connecting to fritz.box (fritz.box)|192.168.178.1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘InRelease’

InRelease               [ <=>                  ]   5.49K  --.-KB/s   in 0.003s

2016-04-27 14:58:57 (2.07 MB/s) - ‘InRelease’ saved [5620]

robot@ev3dev:~$ sudo apt-get update
[sudo] password for robot:
Get:1 http://httpredir.debian.org jessie InRelease
100% [1 InRelease gpgv 5,620 B]Splitting up /var/lib/apt/lists/partial/httpredirIgn http://httpredir.debian.org jessie InReleaseata and signature failed
E: GPG error: http://httpredir.debian.org jessie InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
robot@ev3dev:~$

**Comment by moriarty** [comment]
The:
> fritz.box/tools/kids_not_allowed.lua

makes me think you're fritz box has been configured with parental settings blocking access.

**Comment by markyi370** [comment]
@online4ever Maybe you can explain your situation and have the admin open it up for you.

**Comment by online4ever** [comment]
Yes. Good idea. At the moment everything works fine. Thanks a lot ;-)

**Comment by psychemedia** [comment]
@moriarty If there isn't a Dockerfile, do you know if there is a Vagrantfile that sets up a machine for building images under brickstrap?
