### ISSUE TITLE
flash-kernel: unsupported platform in Raspberry Pi3

### ISSUE THREAD

**Issue by JorgePe** [ev3dev/ev3dev#606]
### System information:

* I am using: Rapsberry Pi Model 3B, Dexter Industries BrickPi

* I installed ev3dev using this image file: rpi2-ev3dev-jessie-2015-12-30.img.xz

* My kernel version is: 4.1.21-10-ev3dev-rpi2

* My host computer is running: Ubuntu Linux

* I am connecting using: Wi-Fi

#### What led up to the situation?
I'm testing Raspberry Pi 3 with BrickPi, and issue #605 sent me here
I deleted 'bcm2710-rpi-3-b.dtb' from /boot/flash/ and wanted to try command 'flash-kernel'

#### What exactly did you do (or not do) that was effective (or ineffective)?
I ran
`sudo flash-kernel`

#### What was the outcome of this action?
`Unsupported platform.`

#### What outcome did you expect instead?
flash-kernel should re-create 'bcm2710-rpi-3-b.dtb'

**Comment by dlech** [comment]
What is output of `dpkg -s flash-kernel`?

**Comment by dlech** [comment]
Just the version actually. `dpkg -s flash-kernel | grep Version`

**Comment by JorgePe** [comment]
`Version: 3.35ev3dev8`

**Comment by dlech** [comment]
hmm... did output of `cat /proc/device-tree/model; echo` change? It should match `Machine:` in https://github.com/ev3dev/flash-kernel/commit/e11ba4de6f82b459b3996dc19729bb84577ea664

**Comment by dlech** [comment]
Oops, wrong link: Correct link is https://github.com/ev3dev/flash-kernel/commit/ddfcc0c3dc5544ddce058f6dc8c9f31e37c01184

**Comment by JorgePe** [comment]
```
cat /proc/device-tree/model; echo
Raspberry Pi 3 Model B Rev 1.2
```
seems ok

**Comment by dlech** [comment]
I wonder if I accidentally copied some non-printing character or something. You could try editing `/usr/share/flash-kernel/db/all.db` and delete that line and re-create it.

**Comment by JorgePe** [comment]
```
robot@ev3dev:~$ sudo flash-kernel 
Installing bcm2710-rpi-3-b.dtb into /boot/dtb-4.1.21-10-ev3dev-rpi2
Taking backup of dtb-4.1.21-10-ev3dev-rpi2.
Installing new dtb-4.1.21-10-ev3dev-rpi2.
flash-kernel: installing version 4.1.21-10-ev3dev-rpi2
Version: Linux version 4.1.21-10-ev3dev-rpi2 (david@freyr) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1 SMP Sun Apr 10 21:33:51 CDT 2016
DT: y
283x: n
Will use /dev/mmcblk0p1 as boot device.
Taking backup of kernel7.img.
Installing new kernel7.img.
Taking backup of bcm2710-rpi-3-b.dtb.
Installing new bcm2710-rpi-3-b.dtb.
```

Nice! Thanks a lot, case closed.

**Comment by dlech** [comment]
Did you change something to fix it?

**Comment by JorgePe** [comment]
No.
Just made what you said: deleted everything from 'Machine:' to end of line, then past the output I posted above, then deleted the end of the line and inserted a new line just in case.

**Comment by dlech** [comment]
OK, so you did change something :wink:

So we shouldn't close this issue until the `flash-kernel` package is fixed.

**Comment by dlech** [comment]
I don't understand what you changed. If I try to delete that line and re-create it, git does not pick up the diff.

**Comment by JorgePe** [comment]
I cannot see any difference either.
Could it be just the "touch" in the file? Perhaps I had something wrong with the file, not with the content.

**Comment by dlech** [comment]
not sure. you could try reinstalling and see if it breaks again `sudo apt-get install --reinstall flash-kernel`

**Comment by JorgePe** [comment]
I reinstalled. Still works.

**Comment by dlech** [comment]
OK. I guess we will close unless someone can reproduce the problem again.
