### ISSUE TITLE
apt-get upgrade bricked my brick

### ISSUE THREAD

**Issue by piersh** [ev3dev/ev3dev#616]
i was running ev3dev-jessie-2015-12-30 and everything was working fine.
i did an apt-get update && apt-get upgrade && reboot.
now it's stuck on 'mindstorms starting...'

can someone else please attempt to repro this?

**Comment by dlech** [comment]
Put the SD card in a computer and open `EV3_BOOT`. There should be a couple of `.bak` files (`uImage.bak` and `uboot.scr.bak`). Replace the matching files with the backup then put the SD card back in the EV3 and hopefully it will boot.

**Comment by piersh** [comment]
oh, i already  wiped the card, and tried it again with a newer image.  this time it worked...
