### ISSUE TITLE
Getting started instructions for the BeagleBone/EVB?

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#617]
I just noticed that there are currently no mentions of the BeagleBone in the getting started guide. Is this intentional? I would expect that there are no significant variations from other platforms, so I imagine it would be quick to add if all that needs to be done is mention the image name and board name.

**Comment by dlech** [comment]
There has not been a regular release that support EVB yet. I'll be updating the docs more when we do the next image release.

**Comment by dlech** [comment]
Done: http://docs.ev3dev.org/en/ev3dev-stretch/platforms/evb.html
