### ISSUE TITLE
Does rpi2-ev3dev-jessie-2015-12-30.img can be used to boot rpi2+BiickPi (not BrickPi+) ?

### ISSUE THREAD

**Issue by yang2218** [ev3dev/ev3dev#631]
Hello everybody !

Does rpi2-ev3dev-jessie-2015-12-30.img can be used to boot rpi2+BiickPi (not BrickPi+) ?

**Comment by dlech** [comment]
Yes. Be sure to edit `config.txt` before booting. It explains what to turn on if you are using BrickPi.

**Comment by yang2218** [comment]
But I get the following Error:

Power_supply brickpi-battery driver failed to report voltage_now property -5

**Comment by yang2218** [comment]
But I get the following Error:

Power_supply brickpi-battery driver failed to report voltage_now property -5

**Comment by yang2218** [comment]
Sorry, I make a mistake to comment and close. It sure be just comment.

**Comment by dlech** [comment]
It sounds like you did not follow the directions:

> # uncomment only if you are using BrickPi+
> #dtparam=brickpi_battery=okay

The BrickPi does not have the capability to monitor battery voltage. So *do not* uncomment this line.
