### ISSUE TITLE
【Q】Can't Upgrade

### ISSUE THREAD

**Issue by LEXUGE** [ev3dev/ev3dev#635]
Help!
It said:
robot@ev3dev:~$ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

**Comment by LEXUGE** [comment]
@dlech

**Comment by ddemidov** [comment]
try `sudo apt-get update`

**Comment by LEXUGE** [comment]
robot@ev3dev:~$ sudo apt-get update

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
@ddemidov

**Comment by ddemidov** [comment]
That is normal. `sudo` means 'do something with a superuser rights'. So it gives you this lecture (first time) and asks for your password.

**Comment by LEXUGE** [comment]
But,what is the password of [sudo]@ddemidov

**Comment by ddemidov** [comment]
This is *your* password, meaning the password of the current user. Its `maker` by default for the `robot` user.

**Comment by LEXUGE** [comment]
Thank you very much

**Comment by LEXUGE** [comment]
But:
[sudo] password for robot:
Err http://ftp.debian.org jessie InRelease

Err http://ev3dev.org jessie InRelease

Err http://ftp.debian.org jessie Release.gpg
  Temporary failure resolving 'ftp.debian.org'
Err http://ev3dev.org jessie Release.gpg
  Temporary failure resolving 'ev3dev.org'
Reading package lists... Done
W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/InRelease

W: Failed to fetch http://ev3dev.org/debian/dists/jessie/InRelease

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'ftp.debian.org'

W: Failed to fetch http://ev3dev.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'ev3dev.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
@ddemidov

**Comment by LEXUGE** [comment]
Help!

**Comment by ddemidov** [comment]
That means your ev3 is not connected to the internet.

**Comment by LEXUGE** [comment]
What?
Oh!In the All network->IPv4
I load the default windows,but it do not back to All Network

**Comment by LEXUGE** [comment]
I only click the connect

**Comment by LEXUGE** [comment]
How can connect the internet!I followed the dochttp://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/

**Comment by LEXUGE** [comment]
@ddemidov

**Comment by ddemidov** [comment]
I am not sure how to do that on widows, but I guess the important steps in the tutorial you linked to are 7-9. Simple test: `ping google.com` should work on the ev3.

**Comment by LEXUGE** [comment]
Oh,But I followed the doc
http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/
@dlech

**Comment by dlech** [comment]
At this point in time, I highly recommend *not* upgrading any packages unless you want a broken system that you are planning on fixing yourself.

If you are not connected to the Internet, then you probably did not follow the tutorial exactly. Also, Windows Internet Connection Sharing breaks easily. It is usually fixed by disabling it and then setting it up again.

**Comment by dlech** [comment]
Also, many of these questions have been asked and answered before. Please search issues (open and closed) before asking a question.

**Comment by LEXUGE** [comment]
Oh,But I didn't faild.I always do by docs
Yes,I changed it,but it didn't back.But ,I update faild,haha!
![image](https://cloud.githubusercontent.com/assets/13804737/15219670/3b5c38ca-1897-11e6-94b9-29c19bce39f4.png)

They are all good,I didn't setting faild

**Comment by LEXUGE** [comment]
What a magical question

**Comment by LEXUGE** [comment]
But the other questions can't help me.:-(
Can it work on buletooth?(windows)
@dlech

**Comment by dlech** [comment]
Bluetooth works for me on Window.

**Comment by LEXUGE** [comment]
@dlech I can ping the website,Am I connect the Internet?

**Comment by LEXUGE** [comment]
Yes,it is succesful!

**Comment by LEXUGE** [comment]
So,you said,do not upgrade the sys.If there is a new version,how can I upgrade the new version?Resetup?
@dlech

**Comment by dlech** [comment]
When we release a new image file, you can install the new image file to the SD card.

You could also use `sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade` at that time, but it will take a very long time. It will be much faster to backup any files you want and write the new image file.

**Comment by LEXUGE** [comment]
OK,thank you very much,and what time in your country?
"sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade"is this one command?

**Comment by dlech** [comment]
11 AM.

> is this one command?

It can be. `&&` means if the previous part was successful, then do the next part. You could also run them as separate commands.

    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get dist-upgrade

**Comment by LEXUGE** [comment]
You are so great,I am only a pupil in China

**Comment by LEXUGE** [comment]
Ask a very easy question:Can the computer give the electric to EV3?

**Comment by dlech** [comment]
No. It requires at least a 1A power supply. 3A is better if you are running more than 1 motor.

**Comment by LEXUGE** [comment]
Oh,it only have 7.86 betty now
the EV3DEV can't install many software(for example:w3m)

**Comment by dlech** [comment]
I don't understand, what is "7.86 betty"

Also, you need to run `sudo apt-get update` before you can install any software with `sudo apt-get install`.

**Comment by LEXUGE** [comment]
But,I input sudo apt.......gcc,it said:
robot@ev3dev:~$ sudo apt-get install gcc
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package gcc

**Comment by dlech** [comment]
Yes. You must run `sudo apt-get update` first, otherwise the package list is empty.

**Comment by LEXUGE** [comment]
原来如此,Thanks!

**Comment by LEXUGE** [comment]
Are you working now?have I bother you yet?

**Comment by dlech** [comment]
If you bothered me too much, I would not answer your questions so much. :wink:

ev3dev is my work most of the time.

**Comment by LEXUGE** [comment]
haha,it can visit my website:

**Comment by dlech** [comment]
The link is missing.

**Comment by LEXUGE** [comment]
lexuge.github.io

**Comment by LEXUGE** [comment]
But it isn't English

**Comment by LEXUGE** [comment]
@dlech How to uninstal softwarel?Help!

**Comment by dlech** [comment]
`sudo apt-get remove <package>`

**Comment by dlech** [comment]
Yes, that also deletes any configuration files (the ones in `/etc/`)

**Comment by LEXUGE** [comment]
Thanks.How can I visit my FTP

**Comment by dlech** [comment]
Install an ftp client.

**Comment by LEXUGE** [comment]
oh,I thought it have one client.But I'm error.

**Comment by LEXUGE** [comment]
This is a very good sys.I like it!
