### ISSUE TITLE
How to run the ev3dev on Raspberry Pi 3 + Brick Pi?

### ISSUE THREAD

**Issue by sportscar** [ev3dev/ev3dev#658]
### System information:

* I am using: *RaspberryPi3 + Dexter Industries BrickPi (HW v2.8)*

* I installed ev3dev using this image file: *rpi2-ev3dev-jessie-2015-12-30.img.xz*

* My kernel version is: *I don't know it.*

* My host computer is running: *OS X 10.11.5*

* I am connecting using: *directly, with monitor, mouse and keyboard*

### About my issue:

Dear all, I'm a new guy on ev3dev. I want to run Lejos api on ev3dev.

I download the img file. and using Etcher app to write img to the SD card.

and then I edit config.txt like this:

 

`# For more options and information see`
`# http://www.raspberrypi.org/documentation/configuration/config-txt.md`
`# Some settings may impact device functionality. See link above for details`

`###################################`
`# mindsensors.com PiStorms config #`
`###################################`

`# uncomment if you are using PiStorms`
`#dtoverlay=pistorms`

`# uncomment to invert the display`
`#dtparam=rotate=270`

`####################################`
`# Dexter Industries BrickPi config #`
`####################################`

`# uncomment both if you are using BrickPi`
`dtoverlay=brickpi`
`init_uart_clock=32000000`

`# uncomment only if you are using BrickPi+`
`#dtparam=brickpi_battery=okay`

`# uncomment to disable BrickPi LEDs on boot.`
`#dtparam=brickpi_led1_trigger=none,brickpi_led2_trigger=none`

`# uncomment if you have a Model B Rev 1 board that uses gpio 21 instead of`
`# gpio 27`
`dtparam=brickpi_led1_gpio=21`

`# uncomment if you have a mindsensors.com RTC sensor connected to input port 5`
`#dtoverlay=i2c-rtc,ds1307`

`################################`
`# Standard Raspberri Pi config #`
`################################`

`# uncomment if you want to use the camera module`
`#start_x=1`
`#gpu_mem=128`
`#disable_camera_led=1`

`# uncomment if you get no picture on HDMI for a default "safe" mode`
`#hdmi_safe=1`

`# uncomment this if your display has a black border of unused pixels visible`
`# and your display can output without overscan`
`#disable_overscan=1`

`# uncomment the following to adjust overscan. Use positive numbers if console`
`# goes off screen, and negative if there is too much border`
`#overscan_left=16`
`#overscan_right=16`
`#overscan_top=16`
`#overscan_bottom=16`

`# uncomment to force a console size. By default it will be display's size minus`
`# overscan.`
`framebuffer_width=1280`
`framebuffer_height=720`

`# uncomment if hdmi display is not detected and composite is being output`
`#hdmi_force_hotplug=1`

`# uncomment to force a specific HDMI mode (this will force VGA)`
`#hdmi_group=1`
`#hdmi_mode=1`

`# uncomment to force a HDMI mode rather than DVI. This can make audio work in`
`# DMT (computer monitor) modes`
`#hdmi_drive=2`

`# uncomment to increase signal to HDMI, if you have interference, blanking, or`
`# no display`
`config_hdmi_boost=4`

`# uncomment for composite PAL`
`#sdtv_mode=2`
`#uncomment to overclock the arm. 700 MHz is the default.`
`#arm_freq=800`
 
 
after this, I put SD card into raspberryPi and boot it. 

but, after I turn it on, the monitor display the rainbow square. and the raspberry pi green light flashing as 4 times long 4 times short.

please tell me what's wrong in there. Thanks!

**Comment by JorgePe** [comment]
The latest image available for download doesn't work with the RPi3 out of the box.
Do you have a Raspberry Pi 2? You can put you the SD card on it, boot, upgrade it to latest version (apt-get update , apt-get upgrade, apt-get dist-upgrade, reboot) and then put the SD card again in the Raspberry Pi 3.

**Comment by JorgePe** [comment]
Also see #563

**Comment by sportscar** [comment]
thanks JorgePe, I don't have Raspberry Pi 2. So, My question is : Do they have a plan to publish a ev3dev image for Raspberry Pi 3 ready? and when ? 

thanks!

**Comment by JorgePe** [comment]
I'm pretty sure the next rpi2 image will also work with the rpi3. You'll have to ask the maintainers about their timings but since there is a milestone for ev3dev 1.0 (https://github.com/ev3dev/ev3dev/milestones) maybe it's just a matter of a couple of months.

**Comment by sportscar** [comment]
OK, I see. Thanks JorgePe, I will waiting the next image package. This question can be closed. 
Thanks again.

**Comment by JorgePe** [comment]
@sportscar please test the nightly builds - an image two days old worked OK with my Raspberry Pi 3 and BrickPi. If you want to use onboard bluetooth and onboard wi-fi please see #607

**Comment by WasabiFan** [comment]
@sportscar the nightly build can be found here:

  [ ![Download](https://api.bintray.com/packages/ev3dev/nightly/ev3dev-jessie/images/download.svg) ](https://bintray.com/ev3dev/nightly/ev3dev-jessie/_latestVersion)

The one from the 26th is currently the most recent image, and it should be the one that works with the rpi3.
