### ISSUE TITLE
I'm confused on the state of the project [Trying to get Motors working next]

### ISSUE THREAD

**Issue by jmshelby** [ev3dev/ev3dev#66]
I feel like I've gotten pretty far going through the wiki (which seems very incomplete still). I've stumbled through many missing sections and broken links, and it's hard to tell what's been completed yet or not. So just tell me if i'm just too far in, and you're still working on things...

I have the most recent SD card image working, loaded up the recent kernel update, and got wifi working.

The "Loading A Driver Module" wiki page says to find the ev3 kernel modules under the ev3dev repo in a directory named modules. That directory doesn't exist, so I assumed it meant the ev3dev-modules repo .... yet still there were no *.ko files anywhere in that repo, nor any releases... so where are these kernel extensions?

Looking around on the booted ev3 file system, I found 3 .ko files (ev3dev, ev3dev_ui, and ev3dev_pwm) under /lib/modules/3.3.0/kernel/ev3dev. So I kept going forward assuming they were up-to-date (though i'm not quite so sure now). I followed the directions to add the three to /etc/modules, rebooted, and saw that the modules were now loaded.

I was able to see and mess with the LED and button device files at /sys/devices/platform/ev3dev/ui and they all work fine...

I'm stuck at the motor section now, the files don't seem to be there from the documentation (https://github.com/mindboards/ev3dev/wiki/Using-Motors). In fact I don't see this directory at all: /sys/bus/legoev3. Is this not working yet? Seems like other people have them working. I can see motor files for A B C and D under /sys/devices/platform/ev3dev/pwm but I can't quite get them working.

Can you point me in the right direction to start messing with the motor drivers?

**Comment by erichuang2013** [comment]
I am trying to control a normal RC ESC for servo-motor class. but don't have a clue how to generate the servo-motor-class under /sys/class. any hardware wiring needed to allow ev3dev to detect external device? or I can manually add this servo-motor class in a specific port?

My kernel version is Linux "ev3dev 3.16.7-ckt6-ev3dev1 #2 PREEMPT Sun Feb 22 16:07:24 CST 2015"

**Comment by rhempel** [comment]
Please open a separate defect for this issue @erichuang2013 - the EV3 does not generate hobby servo compatible pulse widths - the servo motor class is for devices that generate those pulses, but communicate with the EV3 through the standard port communication modes.

**Comment by dlech** [comment]
@erichuang2013, currently, the only supported servo controller is the [mindsensors.com 8 channel servo controller](http://www.ev3dev.org/docs/sensors/mindsensors.com-8-channel-servo-controller/). You need one of these to use your servo.
