### ISSUE TITLE
resizing SD card 

### ISSUE THREAD

**Issue by jsvalderrama** [ev3dev/ev3dev#67]
Hello, 
I have succeeded to resize the SD image  in my previous deployment of the EV3dev release, but today I couldn't find the command to resize the SD card once already written on it which I think I read on the EV3dev wiki documentation. Could anybody please point me on the good pages or give me the command? 

Thanks in advance.

**Comment by cho934** [comment]
Hi,

Using last ev3dev release ev3-ev3dev-jessie-2015-12-30, what is the new process ? because the following line doesn't work anymore:
robot@ev3dev:~$ sudo lvextend --extents +100%FREE --resizefs /dev/ev3devVG/root /dev/mmcblk0p3 

Best Regards,

**Comment by dlech** [comment]
The SD card is automatically resized on the first boot. You can verify by running `df -h`. If the root partition (`/`) is larger than 2GB, then it has been resized.

**Comment by cho934** [comment]
Yes, I confirmed that it is ok.
 ;)

**Comment by dwalton76** [comment]
@dlech what is the script that runs on firstboot that does this?  I created a .img of my SD card and wrote it to a much larger SD card, now I need to expand the filesystem.  It doesn't happen on a reboot, I'm guessing whatever does that magic only runs when you first install ev3dev.

**Comment by dwalton76** [comment]
I found this:
https://github.com/rhempel/ev3dev-jessie/blob/be2cbeaf43823e497352abfbea3c80154fef8a04/root/etc/init.d/firstboot

but no luck
```
robot@beaglebone[~]# sudo parted --script /dev/mmcblk0 unit % resizepart 2 100%
Warning: Partition /dev/mmcblk0p2 is being used. Are you sure you want to continue?
robot@beaglebone[~]# sudo partprobe
robot@beaglebone[~]# sudo resize2fs /dev/mmcblk0p2
resize2fs 1.42.12 (29-Aug-2014)
The filesystem is already 1878784 (4k) blocks long.  Nothing to do!

robot@beaglebone[~]#
```

after a reboot, still at 8G.  The SD card is 128G
```
robot@beaglebone[~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            98M  388K   98M   1% /run
/dev/mmcblk0p2  7.1G  2.4G  4.4G  36% /
tmpfs           244M     0  244M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           244M     0  244M   0% /sys/fs/cgroup
/dev/mmcblk0p1   48M  2.0K   48M   1% /boot/flash
tmpfs            49M     0   49M   0% /run/user/1000
robot@beaglebone[~]# 
```

**Comment by dlech** [comment]
FWIW, the latest version is [here](https://github.com/ev3dev/docker-library/blob/master/ev3dev-jessie/layers/base/etc/init.d/firstboot), but it looks the same to me other that a workaround was added. Try it without the `--script` option or just run `sudo parted` to run in interactive mode.

**Comment by dwalton76** [comment]
I ended up following http://elinux.org/RPi_Resize_Flash_Partitions#Resizing and got it working
```
robot@beaglebone[~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            98M  388K   98M   1% /run
/dev/mmcblk0p2  118G  2.5G  110G   3% /
tmpfs           244M     0  244M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           244M     0  244M   0% /sys/fs/cgroup
/dev/mmcblk0p1   48M  2.0K   48M   1% /boot/flash
tmpfs            49M     0   49M   0% /run/user/1000
robot@beaglebone[~]# 
```
