### ISSUE TITLE
Ev3 not booting

### ISSUE THREAD

**Issue by Fotblx25** [ev3dev/ev3dev#670]
### System information:

* I am using: LEGO MINDSTORMS EV3

* I installed ev3dev using this image file: ev3-ev3dev-jessie-2015-12-30.img

* My host computer is running: Windows

* I am connecting using: USB

### About my issue:

When I boot my EV3 with ev3dev, It either shows a blank screen with green led or just gets stuck on the boot splash. I've tried reflashing my sd card (32GB SDHC) and I'm using the latest img file yet i havn't had any success.

**Comment by dlech** [comment]
Try a different SD card. Also make sure you don't have anything plugged into the EV3 (sensors, motors, USB).

**Comment by Brian0526** [comment]
I'm pretty sure it said ev3 does not support any sd card more than 32GB.

**Comment by dlech** [comment]
Please reopen if this is still an issue using the latest image from [here](https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/)
