### ISSUE TITLE
Coding Applications?? PLZ HELP!!!

### ISSUE THREAD

**Issue by Brian0526** [ev3dev/ev3dev#672]
# About my issue:
Okay, so I just installed ev3dev, and I want to know what application(s) I can use to code using this OS. I would like to program in PYTHON, NODE.JS, and C++

Thanks,

**Comment by theZiz** [comment]
Python: http://www.ev3dev.org/docs/tutorials/setting-up-python-pycharm/ or https://github.com/rhempel/ev3dev-lang-python
Node-JS: https://github.com/wasabifan/ev3dev-lang-js
C++: https://github.com/ddemidov/ev3dev-lang-cpp

**Comment by Brian0526** [comment]
THANK YOU!!!!!!!
