### ISSUE TITLE
ig

### ISSUE THREAD

**Issue by lonny** [ev3dev/ev3dev#676]
### System information:

* I am using: *PASTE DEVICES HERE*

* I installed ev3dev using this image file: *IMAGE NAME GOES HERE*

* My kernel version is: *KERNEL VERSION GOES HERE*

* My host computer is running: *OS GOES HERE*

* I am connecting using: *PASTE METHOD HERE*

**Comment by dlech** [comment]
Is there actually an issue or can we close this?

**Comment by lonny** [comment]
That occurred due to a slip of the fingers on the keyboard when I was viewing. It should not exist.

Please close it, and delete it if possible.
