### ISSUE TITLE
Battery status?

### ISSUE THREAD

**Issue by daniels** [ev3dev/ev3dev#68]
Is there any way to get the current status of the battery? If not, is it something you will look into?

I'm not sure how the system will react to sudden power loss, maybe it's not a problem?

(I've been following the status of this project for almost half a year, and finally found some time and courage to try it out for real. It was a boost to get a motor to run from the shell the first time, and now I'm trying to get to know the system. I will open a couple of issues, but they are more questions than issues, so please let me know if you'd rather have me ask my questions elsewhere.)

**Comment by ensonic** [comment]
Where do these values come from?
POWER_SUPPLY_VOLTAGE_MAX_DESIGN=7500000
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7100000
As everyone gets values larger than MAX for a fully charged battery (POWER_SUPPLY_VOLTAGE_NOW=8013800 in my case), can we override this in some way?

**Comment by dlech** [comment]
They come from the [LEGO source code](https://github.com/mindboards/ev3sources/blob/master/lms2012/lms2012/source/lms2012.h#L433) and they seemed to meet the definition from [power_supply_class.txt](https://www.kernel.org/doc/Documentation/power/power_supply_class.txt).

> VOLTAGE_MAX_DESIGN, VOLTAGE_MIN_DESIGN - design values for maximal and
minimal power supply voltages. Maximal/minimal means values of voltages
when battery considered "full"/"empty" at normal conditions. Yes, there is
no direct relation between voltage and battery capacity, but some dumb
batteries use voltage for very approximated calculation of capacity.
Battery driver also can use this attribute just to inform userspace
about maximal and minimal voltage thresholds of a given battery. 

If you think these values should be changed, please state your reasoning (and open a new issue). The only requirement I have is that it needs to fit the criteria in [power_supply_class.txt](https://www.kernel.org/doc/Documentation/power/power_supply_class.txt).

While we are on the subject, I have it in the back of my mind that I would like to use the `POWER_SUPPLY_CAPACITY_LEVEL` property to supply property to provide a [simple 5-step indication](https://github.com/ev3dev/ev3-kernel/blob/ev3dev-jessie/include/linux/power_supply.h#L73) just like the [LEGO firmware](https://github.com/mindboards/ev3sources/blob/master/lms2012/c_ui/source/c_ui.c#L1660).
