### ISSUE TITLE
Raspberry Pi 3 Wi-Fi

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#688]
I didn't see any open issues for this, so starting a new one.

I have just created a new package called `firmware-rpi` that contains the firmware needed to get Wi-Fi working on Rapsberry Pi 3.

    sudo apt-get update
    sudo apt-get install firmware-rpi
    sudo reboot

**Comment by dlech** [comment]
Fix released.

@jorgepe

**Comment by JorgePe** [comment]
Very late but I confirm - with nightly build of 26 July 2016 the onboard wi-fi adapter works out of the box.
