### ISSUE TITLE
Spark motor controller with EV3?

### ISSUE THREAD

**Issue by Master-Matt** [ev3dev/ev3dev#691]
Has anyone tried using the spark controller from Rev robotics with the ev3? It uses a PWM connection. Can this be used to connect directly to an rj12 for use on the EV3 brick? 

Also, I'm looking for a motor cutoff device that can handle high current motors. like 20-40A @12VDC.
Is there something I can directly interface with the brick that can act as a big switch? 
Thanks!

**Comment by dlech** [comment]
Looking at the data sheet for the Spark, it uses hobby servo type PWM to control the motor, which means you need a servo controller such as the [mindsenors.com servo controller](http://www.ev3dev.org/docs/sensors/mindsensors.com-8-channel-servo-controller/).

If you want to connect directly to the brick, technically it is possible to use one of the output ports, but you will have to do some work (both hardware and software) to make it work. See #308.

As for the motor shutoff, you could use a [mindsensors.com relay driver](http://www.mindsensors.com/ev3-and-nxt/82-relay-driver-for-nxt-or-ev3) connected to an automotive relay that can handle the higher current of the motor.

**Comment by Master-Matt** [comment]
I'm also looking into using [these](https://www.parallax.com/product/28962) with [this](https://wiki.robocore.io/hardware:motordriver) as a controller. Since it's using quadrature encoding, would the EV3 be able to decipher the output of the motor? I would use [this](https://wiki.robocore.io/hardware:hmotor_and_hsensor_connectors) to connect to the brick.

**Comment by dlech** [comment]
Yes, from the looks of it, I think it should work.

**Comment by Master-Matt** [comment]
I found [this](http://www.cytron.com.my/p-mdds10) as well. Because it has the UART connection, could this be plugged directly into the brick?

**Comment by dlech** [comment]
Yes, you could plug it into on of the input ports and set that port to `other-uart` mode. One thing to watch out for is that the EV3 has 3.3V I/O and the other board looks like it operates on 5V. The EV3 has protection so that it is safe to connect 5V signals, but the question is if 3.3V is enough to be detected as logic high on the motor controller. It probably is, but there is a small chance you would need a buffer to convert voltage levels between the two devices.
