### ISSUE TITLE
Bluetooth not working (new EV3)

### ISSUE THREAD

**Issue by johngpayne** [ev3dev/ev3dev#698]
### System information:

* I am using: LEGO MINDSTORM EV3
* My kernel version is: 3.16.7-ckt21-9-ev3dev-ev3
* My host computer is running: Windows (git bash shell)
* I am connecting using: Wifi or wired

### About my issue:

I'm quite new to this, trying to follow instructions to get a PS3 pad bluetooth connected, and failing at the first hurdle of getting bluetooth working.

I'm pretty sure i'm all up to date

I've tried using the standard bluetooth menu and I get ??? underneath the powered/discoverable menu buttons (like in the report #572)

systemctl has a red line saying:

 ev3-bluetooth.service                   loaded failed failed

"sudo systemctl -l status ev3.bluetooth.service" gives

● ev3.bluetooth.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

In bluetoothctl I get "No default controller available" for all instructions like "power on" or similar (though agent on and default-agent seem to work)

sudo journalctl has a section that looks like this:

Jan 01 00:01:00 ev3dev brickman[321]: ** (process:321): CRITICAL **: bluez5_manager_get_devices: assertion 'self != NULL' failed
Jan 01 00:01:00 ev3dev dbus[272]: [system] Failed to activate service 'org.bluez': timed out
Jan 01 00:01:22 ev3dev systemd[1]: ev3-bluetooth.service: control process exited, code=exited status=1
Jan 01 00:01:22 ev3dev systemd[1]: Failed to start LEGO MINDSTORMS EV3 built-in Bluetooth.
Jan 01 00:01:22 ev3dev systemd[1]: Unit ev3-bluetooth.service entered failed state.
Jan 01 00:01:22 ev3dev systemd[1]: Starting Connection service...
Jan 01 00:01:22 ev3dev systemd[1]: Starting Bluetooth service...
Jan 01 00:01:23 ev3dev bluetoothd[451]: Bluetooth daemon 5.23
Jan 01 00:01:23 ev3dev systemd[1]: Started Bluetooth service.
Jan 01 00:01:24 ev3dev kernel: Bluetooth: Core ver 2.19

Which I think looks related? Though there's loads of other bluetooth entries so maybe I'm looking at a symptom not a cause...

My issue looks a bit like #572 but that's quite old.

I hope there's some useful info here. I'm new to ev3dev so let me know if I've done things wrong.

**Comment by dlech** [comment]
#572 may be old, but it is still valid. Please direct any further comments there.

Couple things to try:
* Make sure you don't have any sensors plugged in when you boot. 
* Upgrade the `flash-kernel` package

        sudo apt-get update
        sudo apt-get install flash-kernel
        sudo flash-kernel
        sudo reboot
