### ISSUE TITLE
version 00.02.00 and C++ ?

### ISSUE THREAD

**Issue by cho934** [ev3dev/ev3dev#70]
Hello,

I participate every year to the French Cup of Robotic, and We have an NXT and an EV3. I'm interested to test ev3dev in C/C++.

Have you got some tests in C++? what will be new in the next release 00.02.00?
I can maybe help in your project ?

Best regards,
Christophe.

**Comment by cho934** [comment]
I think you can close this issue now.

**Comment by dlech** [comment]
Tip: If you opened an issue, you can close it too.
