### ISSUE TITLE
Nightly images are 4GB in size, breaking compatibility with 2GB cards

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#701]
After downloading the most recent nightly EV3 image, I discovered (after a few days of considerable confusion) that the image is 4GB by default and cannot be imaged to the 2GB card I use for new upgrades. Was this intended?

**Comment by dlech** [comment]
Nope, not intentional. Probably broke because of https://github.com/ev3dev/brickstrap/commit/25e89140df552f0e8567f1dc9425d3315ac5817c

**Comment by dlech** [comment]
Fix released in brickstrap 0.5.1
