### ISSUE TITLE
Create a docs page on upgrading the installed kernel

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#709]
We often end up telling people that they need to upgrade the kernel + drivers to get their software to run as expected. It would be great if we had a page that we could link to that had the commands needed along with the option of re-flashing with a nightly/other recent release.

**Comment by dlech** [comment]
This is also done, yes?

**Comment by WasabiFan** [comment]
Yes. This issue was relocated but never closed.
