### ISSUE TITLE
Is there a language agnostic test suit for a language interface?

### ISSUE THREAD

**Issue by tbrowder** [ev3dev/ev3dev#714]

**Comment by rhempel** [comment]
Not really - and I'm not sure what that would look like if it existed. I have a (tentative) start on a test interface for Python [here](https://github.com/rhempel/ev3dev-lang-python/tree/develop/tests/motor)[here]  but I'm not really happy with it.

As I mentioned in #713 - if you use `autogen` then almost all of the code is generated for you once you have the liquid templates working. From that point on, if you can read/write the motor `position` attribute it's a pretty good bet you can read a sensor attribute.

**Comment by rhempel** [comment]
The Python test suite I have is intended to test the drivers, not the Python binding - although it does test the binding as a side effect.

**Comment by tbrowder** [comment]
On Monday, August 1, 2016, Ralph Hempel <notifications@github.com> wrote:

> The Python test suite I have is intended to test the drivers, not the
> Python binding - although it does test the binding as a side effect.
>
Thanks, Ralph!

>

**Comment by dlech** [comment]
> and I'm not sure what that would look like if it existed.

It would like like our user defined sensor driver. You can programatically define any sensor and its behavior this way. Of course this is not ready to use at this time, but that is what it would look like.

**Comment by dlech** [comment]
There is https://github.com/ev3dev/ev3dev-lang-fake-sys

It doesn't really do much though.
