### ISSUE TITLE
Clarify the intent of the "projects" page on website

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#732]
As was brought up in conversation with @ndward, the "projects" page should be updated to reflect the fact that they aren't all suited to replication by beginners or even experts. I think we should rename the page to "Project showcase", "Community showcase" or "Community project showcase" to make it clearer.

**Comment by dlech** [comment]
I like "Project showcase"

**Comment by dlech** [comment]
Website says "Project showcase", so assuming this is complete.
