### ISSUE TITLE
Clarify "libraries" page and promote a single option for each language

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#733]
The "Libraries" page is currently confusing and needlessly complicated. We should have the largest section focus on the most common and primary options, and then have links to extra resources at the end. Preferably a heading (maybe `h2` or `h3`) per language.

cc @ndward

**Comment by dlech** [comment]
Sadly, 90% of the libraries should be flagged as "not actively maintained"

The only ones that have seen activity in the last 6 months (that I know of) are
* https://github.com/ev3go/ev3dev
* https://github.com/in4lio/ev3dev-c
* ev3dev-lang-*

**Comment by WasabiFan** [comment]
Do we think this is done? After the overhaul of this page that I did, I believe it is in good shape.

**Comment by jabrena** [comment]
Hi, In the case of Java, I return to the library.

Why dont exist a release for raspberry pi 3?

Cheers

**Comment by WasabiFan** [comment]
> Why dont exist a release for raspberry pi 3?

I'm not quite sure what you mean... are you referring to ev3dev releases in general? If so, it isn't related to this issue (questions like that should be asked in their own issue, although in this case it has been asked before, so you should do a search beforehand). The image for the Raspberry Pi 2 supports the Raspberry Pi 3 as well, so you use the `rpi2-` image.

**Comment by jabrena** [comment]
Oki, I will test with it.

Cheers
