### ISSUE TITLE
Reword docs to make them platform-agnostic instead of calling it an "EV3"

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#735]
Now that ev3dev supports multiple platforms, it would be best to replace mentions of "EV3" with something more generic or make a note that we will be using that term even though it applies to all platforms.

**Comment by dlech** [comment]
I would lean towards the latter. I would guess from downloads that <10% of people are using something other than an EV3.

**Comment by dlech** [comment]
I've been trying to do this in the ev3dev-stretch docs. Probably not worth it to go back and change things in old docs at this point.
