### ISSUE TITLE
Wrong doc in web page part: Motors

### ISSUE THREAD

**Issue by mob41** [ev3dev/ev3dev#738]
Hi,

I am recently updating my library while I found out that the [document here](http://www.ev3dev.org/docs/motors/) in the website. I think it is pointing a wrong sysfs class, for example [here](http://www.ev3dev.org/docs/motors/actuonix-l12-ev3-100mm/). 

It is pointing to ```lego-motor``` instead of ```tacho-motor```, where ```lego-motor``` is no longer exist in kernel version 15.

It is a typo? Or it is correct? Thanks.

Regards,
Anthony Law

**Comment by dlech** [comment]
You are right. It should be `tacho-motor`

**Comment by mob41** [comment]
So almost all the pages about the Motor drivers name is probably wrong right now...

**Comment by dlech** [comment]
Should be better now

**Comment by mob41** [comment]
Thanks!
