### ISSUE TITLE
Can the rpi2-ev3dev-jessie-2015-12-30.img image be used to boot RPi3 with BrickPi+?

### ISSUE THREAD

**Issue by mike-shock** [ev3dev/ev3dev#746]
* I am using: 
   Rapsberry Pi Model 3 B
   Dexter Industries BrickPi+ (HW v2.8)

* I installed ev3dev using this image file: rpi2-ev3dev-jessie-2015-12-30.img

* My host computer is running: Linux (openSUSE Tumbleweed 20160920).

* I am connecting using: USB keyboard & mouse, TVset via HDMI.

* About my issue:
I wrote the image on a microSD card and edited the config.txt accordingly.
Then I tried to boot RPi3 from the card but the booting stopped with a "rainbow square" on the screen and the green LED on RPi board flashing 7 times.
I tried to write the image onto different microSD HC cards (different sizes, different classes) with the same result.
RPi3 is powered by microUSB, BrickPi+ by 9V battery.

**Comment by dlech** [comment]
This image does not work with RPi 3. Please use the latest nightly image from https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/

Also be sure to read `config.txt` carefully and edit it to match the hardware that you have.

**Comment by dlech** [comment]
To be more specific, pick the image file with `-rpi2-` in the name.

**Comment by dlech** [comment]
Please open a new issue if the nightly images don't work for you.
