### ISSUE TITLE
python code in c libraries; use of swig etc.

### ISSUE THREAD

**Issue by towtruck1** [ev3dev/ev3dev#750]
Hello

I am hoping someone can explain the relationship between the python code & C code in the EV3 C libraries. I understand from reading up on SWIG, that C/C++ code can be wrapped for use in scripting languages, however it seems at some point that the opposite is occurring. 

For example:
In trying to understand the example (ev3dev-c\eg\tacho\tacho.c) I tried to discover where DESC_LIMIT was declared/defined/set. It is referenced in ev3_tacho.h, but only set in line 133 of ev3.yu-i.

```
#define DESC_LIMIT    64
```

All of which gives me the impression that the C is wrapping something else (whatever *.yu-i is).
I suppose I could spend hours trying to get up to speed on SWIG &/or reverse engineering all this, or maybe someone can be merciful and give me a shove in the right direction. I'm finding the examples don't help me that much if I have to go outside of the *.h or *.c files.

Thanks!

**Comment by dlech** [comment]
You might have better luck asking at the source of the library: https://github.com/in4lio/ev3dev-c/issues

**Comment by towtruck1** [comment]
Thanks. Sorry I missed that. I have moved it to: <https://github.com/in4lio/ev3dev-c/issues/3>
