### ISSUE TITLE
Unstable USB Network connection on Ubuntu 14.04

### ISSUE THREAD

**Issue by GrLow** [ev3dev/ev3dev#77]
Hi. I've been trying without much success to set up USB networking on my system running Ubuntu 14.04 LTS. I can ping the robot successfully and then SSH into it, but the connection is unstable and will only last anywhere from a few seconds to a few minutes. After this, the terminal locks out and I cannot enter text or even leave the SSH session. If I then close the terminal window and then restart I can no longer get a ping on the robot and have to go through the process of setting the ifconfig for usb0 before I can try again.

I have tried logging in as su - but have the same problems still. Hope you can help, I have only been using Linux for a few weeks now and are still pretty green.

**Comment by dlech** [comment]
Closing due to no response - and pretty sure this is fixed.
