### ISSUE TITLE
After shutdown, no longer boots

### ISSUE THREAD

**Issue by burf2000** [ev3dev/ev3dev#786]
I am sure this is something unique to me however I flash a card with the latest downloaded EV3Dev

Run it, update it (APT-GET) etc and when I am finished, I shut it down (power off option)

If I then try to fire it up again, it just hands on the MINDSTORMS screen before it even shows EV3 DEV?  What am I missing

**Comment by burf2000** [comment]
Ok so, if I hold down the back and enter button which seems to reboot it, it then works?

**Comment by dlech** [comment]
Maybe you have a bad SD card? Do you have another card you can try?
