### ISSUE TITLE
Fix website demotion in mobile search results due to ev3devKit documentation

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#799]
Currently, the main website is being demoted in Google search results because the ev3devKit docs hosted at <http://www.ev3dev.org/ev3devKit/ev3devkit/index.htm>. It would be great to either relocate that or make the pages more user-friendly.

It's also worth noting that those pages are almost entirely nonexistent from search results.

**Comment by dlech** [comment]
Note to self. See if updating valadoc version fixes this.
