### ISSUE TITLE
How to detect a Raspberry Pi board by command line?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#811]
I would like to know how to detect that ev3dev is running on a raspberry pi board.

Does exist some way to detect it?

One alternative could be the usage of uname-r and parsing later.

``` bash
robot@ev3dev:/sys/class$ uname -r | grep rpi
robot@ev3dev:/sys/class$ uname -r | grep rpi2
robot@ev3dev:/sys/class$ uname -r | grep rpi3
````

Another idea could be use /proc/cpuinfo

``` bash
robot@ev3dev:/sys/class$ cat /proc/cpuinfo | grep BCM2708
Hardware	: BCM2708
``` 

Any idea?

Related issue:
https://github.com/ev3dev/ev3dev/issues/523

**Comment by dlech** [comment]
#523 explains the available options. `/proc/device-tree/model` is probably currently the best option.

**Comment by jabrena** [comment]
For RaspberryPi 1, how to detect BrickPi? Previously, I used the battery path to detect BrickPi

**Comment by dlech** [comment]
Did you read #412? It has some suggestions.

**Comment by jabrena** [comment]
Tomorrow, I will read in detail again.

Cheers

**Comment by dlech** [comment]
In ev3dev-stretch, there is now #523

**Comment by jabrena** [comment]
I have to move to `ev3dev-stretch` in next months. :)

Many thanks @dlech 

Cheers
