### ISSUE TITLE
D-Link DWL-G132 WiFi help

### ISSUE THREAD

**Issue by kleinash** [ev3dev/ev3dev#82]
Hi. 

I am trying to connect a wifi dongle to my ev3.. I have the ev3dev running as it should but I cannot get it to work with the wifi - ie I can only connect with a cable.. 

This is a D-Link DWL-G132 dongle with AR5005UG chip-set. 

I found this as being the most straight forward way of setting it up: http://www.howtogeek.com/howto/43752/how-to-install-a-wireless-card-in-linux-using-windows-drivers/ 

but I cannot install ndiswrapper because I dont have the linux kernel header files on the image.. is there anything I am missing? Is there anyone that can help perhaps? 

-Ashley

**Comment by dlech** [comment]
Is this still and issue?

**Comment by kleinash** [comment]
Nope - we bought the suggested dongle
