### ISSUE TITLE
SD card images have backup files in the boot partition

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#823]
### What did you do?

Flashed a RPi image from ev3dev-jessie-rpi2-generic-2016-12-21.zip

### What did you expect to happen?

Not to have quite so many files in the EV3DEV_BOOT partition

### What actually happened?

The partition contained several `.bak` files

**Comment by WasabiFan** [comment]
Roughly how big are these files? Are they taking up significant space?

**Comment by dlech** [comment]
One of them is the kernel, so probably about 4MB. Also, the files are duplicates and not really backups of a newer file.

**Comment by dlech** [comment]
Fixed in 2017-01-25 snapshot image.
