### ISSUE TITLE
Website doesn´t show some images on Chrome OSX:

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#838]
Hi, 

this morning for some reason, I didn´t show some traditional images on the website.
http://www.ev3dev.org/

```
<div class="col-lg-4">
    <img class="img-responsive" id="splash-thumbnail" src="images/logo_ev3dev_mono.png" alt="ev3dev boot logo">
</div>
```

I tested with FF & Safari on OSX and I see the image but for Chrome the logo disappeared. It is like some responsive media query was enabled.

Juan Antonio

**Comment by dlech** [comment]
I can see the image in Chrome (Chromium 55 on Ubuntu). It disappears if the window is < 1200px wide.

**Comment by WasabiFan** [comment]
Yes, it will be hidden when the window becomes small enough that things start to collapse into mobile view.

**Comment by jabrena** [comment]
Maybe, it is necessary to check that media query. If the window enter in a Tablet dimension, in that case, it should be hidden. Isn´t it?

Cheers

**Comment by dlech** [comment]
Can you post a screenshot?

**Comment by jabrena** [comment]
I link a image:

![](https://raw.githubusercontent.com/ev3dev-lang-java/docs/support/ev3dev/ev3dev_homePage.png)

Take a look dimensions from DOM. If you observe, although my laptop is 1024, if I reduce a bit the screen, the media query disappear. I am not sure if this behaviour is natural from Bootstrap or not.

Cheers

**Comment by WasabiFan** [comment]
Your display is small enough that it's being identified as a tablet, and as a result the unnecessary images are being hidden and content is wrapping.

**Comment by jabrena** [comment]
My comment is if the website for tablet should maintain the image about Linux. The essence of EV3Dev is the development of a complete Linux inside of a EV3Brick, so the image is significative.

**Comment by WasabiFan** [comment]
Although that image is technically valid, it isn't very useful for a new user and I don't believe that it is a good visual element to have on that page. We plan to replace that image with something that is more relevant to the project now that the old boot screen depicted there has been replaced, and in the process I can make it flow properly in tablet/mobile view. See https://github.com/ev3dev/ev3dev.github.io/issues/238.

**Comment by jabrena** [comment]
Yeahhh!!

I like so much this pic:
https://cloud.githubusercontent.com/assets/3310349/21585636/55456b4a-d092-11e6-9746-557d54c6600c.png

**Comment by jabrena** [comment]
This weekend, I will give my personal comment.

Cheers
