### ISSUE TITLE
dc-motor class has no default duty cycle

### ISSUE THREAD

**Issue by vinicentus** [ev3dev/ev3dev#842]
I was playing aroud with my power functions m-motor and discovered that it didn't work. Then I started looking for the fault, and found that there doesn't seem to be a default duty cycle for the dc-motor class. It worked just fine after I changed it to 100.

Is there a reason to why there isn't a default duty cycle?

Also, how do you read things like duty_cycle and status of a motor?

I am running ev3dev-jessie-2017-02-11...

**Comment by dlech** [comment]
> Is there a reason to why there isn't a default duty cycle?

 No reason.


> Also, how do you read things like duty_cycle and status of a motor?

Like all ev3dev drivers, you read the sysfs attributes. For example, using a command prompt...

    cat duty_cycle
    cat status

I assume you have read [this page](http://www.ev3dev.org/docs/drivers/dc-motor-class/)?
