### ISSUE TITLE
Working programs will not run if I unplug the USB cable.

### ISSUE THREAD

**Issue by clplaneguy** [ev3dev/ev3dev#844]
SOLVED

I am using EV3/EV3dev/PyCharm.  Last week I was using MobaTextEditor.  I have written a PID program for the EV3 in PyCharm.  It performs in a very believable manner.  I am satisfied with the program and am ready to get the bot off my desktop and onto the floor.  But, when I unplug the USB cable, the program will not execute.  I had this problem last weak with MobaTextEditor, and the editor was sending the file in DOS format and I needed UNIX format.  Is this the same problem?  How do I set PyCharm to save a file in UNIX format?

**Comment by WasabiFan** [comment]
I suspect it is the same issue. See the page [here](https://www.jetbrains.com/help/pycharm/2016.3/configuring-line-separators.html), specifically under the heading "To change line separator for a file, currently opened in the editor"; that explains how to change the line endings in PyCharm.

**Comment by clplaneguy** [comment]
SOLVED   

THANK YOU

**Comment by WasabiFan** [comment]
Please close the issue now that your problem has been resolved.
