### ISSUE TITLE
Upgrade programming languaje page with info about Java library.

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#845]
Hi, 

I would like to upgrade the document in the website about Programming Languages:
http://www.ev3dev.org/docs/programming-languages/

To update the part about Java.
The library was tested with latest 2 images.
http://ev3dev-lang-java.github.io/#/

Cheers

Juan Antonio

**Comment by dlech** [comment]
Sure. Just send a pull request.

**Comment by jabrena** [comment]
Many thanks. 

Along the week, I will do it.

Cheers

**Comment by jabrena** [comment]
Upgraded.
