### ISSUE TITLE
User group problems

### ISSUE THREAD

**Issue by heidashuai** [ev3dev/ev3dev#846]
### What are you trying to do?
Sorry,but I met a problem with the user groups. I wanted to use sound function so I add robot to audio group,but I find that robot is out of ev3dev group!
And I do not know how to make it back,since I have no right to do the operations...

### What did you expect to happen?
I want to be ev3dev member again

### What actually happened?
I have no right to change the group

**Comment by heidashuai** [comment]
@dlech

**Comment by dlech** [comment]
This sounds like yet another case of SD card corruption. Please make sure you are using an SD card smaller than 32GB. Also try a different SD card if you have one and flash a new image.

**Comment by heidashuai** [comment]
@dlech Thank you David. It is more complicated than SD card problems,but I think I have already solved the it.
And for the sound function.Could you please tell how can I remotely control the ev3 to make a sound?

**Comment by dlech** [comment]
This page hasn't really been maintained, but I think most of the information there is still good: <https://github.com/ev3dev/ev3dev/wiki/Using-Sound>. You should prefer commands to sysfs attributes since the sysfs attributes might not be around forever.

**Comment by heidashuai** [comment]
@dlech Thank you very much! I will try it

**Comment by heidashuai** [comment]
@dlech It works great!Thank you again and maybe I should close the issue.
