### ISSUE TITLE
Tacho motor continues running after being commanded to stop due to "hold" mode

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#847]
### What are you trying to do?

Stop a motor that was commanded to go to a position, as in this Python demo:

```python
mB.run_to_rel_pos(position_sp=5000, speed_sp=100, stop_action='hold')
sleep(5)
mB.stop()
```

The important part is that the motor is commanded to a position with a `stop_action` of `hold`, and then asked to stop prematurely.

### What did you expect to happen?

The motor to stop where it was and hold its position.

### What actually happened?

The motor continued running until it reached the originally-set target.

### What hardware and software are you using (including version numbers)?

https://github.com/ev3dev/lego-linux-drivers/commit/e3f0c461f9d1b39f74607e6c06819a0785606b4a (current `master`) includes the code in question.

---

I've found the root cause of this behavior; it's [this line](https://github.com/ev3dev/lego-linux-drivers/blob/master/ev3/legoev3_motor.c#L346):

```c
case TM_STOP_ACTION_HOLD:
    if (use_pos_sp_for_hold)
        ev3_tm->hold_pid.setpoint = ev3_tm->position_sp;
    else
        ev3_tm->hold_pid.setpoint = ev3_tm->position;
    ev3_tm->hold_pid_ena = true;
    break;
```

The stop logic is special-cased for position commands: the `hold` action's target is set to the target of the original command instead of the current position. Although I can see some logic to this, I believe it should be changed to either always use the current position or only use the original target if the `stop` op was invoked because it reached said target (not because the user manually set the command). This behavior would make the motor's actions much more natural, as currently you can't stop a running motor of this configuration without running a new rotation command that sends no power. Unquestionably, having a motor that ignores a `stop()` call is an issue 😆 

This was reported originally by @ndward.

**Comment by dlech** [comment]
Fix has been released in `20-ev3dev` and `ev3dev-1.1.0` kernels.

http://www.ev3dev.org/news/2017/04/15/kernel-release-cycle-20/
