### ISSUE TITLE
Cant install ruby gems

### ISSUE THREAD

**Issue by LuckyChicken91** [ev3dev/ev3dev#849]
### What are you trying to do?
I try to install the ev3dev_ruby gem but it dont work he show me that he cant find it but if I install it on my normal PC it works. So I was sure that I must first make "sudo apt-get update" but it too dont works.
Does I need a internet connection in the EV3 to install anything?!
I have connected  my PC and EV3 with  http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/

What should I do now?

![5](https://cloud.githubusercontent.com/assets/25749652/23182754/f49cec86-f879-11e6-82f5-468729e9d761.PNG)

### What hardware and software are you using (including version numbers)?

LEGO Mindstorms EV3, ev3dev

(sorry for bad english)

**Comment by JorgePe** [comment]
You do need an internet connection. If you are using USB, you should get internet connection through your PC  if you followed that tutorial (as long as your PC has internet connection and there is no firewall or other security program on your PC blocking it).

**Comment by dlech** [comment]
Can this be closed?
