### ISSUE TITLE
Using WinNFSd for NFS file sharing

### ISSUE THREAD

**Issue by JNFitzgerald** [ev3dev/ev3dev#85]
This is not so much an issue, but a possible solution.

I have gotten WinNFSd to work as an alternative to haneWin NFS, which is of course beneficial as it is freeware.

The procedure is nearly identical to that of haneWin NFS, with the setup of WinNFSd only requiring the creation of a .bat file to launch it, and one tweak to the fstab file on the EV3.
1. Download and Extract WinNFSd.  You will have a folder with an executable, license, and readme file.
2. Open notepad, and enter this line.
   
   ```
    winnfsd.exe -id 0 0 -log off [directory]
   ```
   
   Where [directory] is the full path to the folder as it shows in the file explorer.  For example, mine is
   
   ```
   winnfsd.exe -id 0 0 -log off E:\Users\James\Dropbox\ev3dev
   ```
   
   Save it as all files, named launch.bat
3. fstab is exactly the same as with haneWin with one exception, you must specify the entire file path for the share.  Again, using my config as an example.  So rather than this:
   
   ```
   192.168.0.199:/ev3dev                        /home/root/nfs/ev3dev nfs users,noauto,rw,vers=3  0 0
   ```
   
   I have this:
   
   ```
   192.168.0.199:\E\Users\James\Dropbox\ev3dev                       /home/root/nfs/ev3dev nfs users,noauto,rw,vers=3  0 0
   ```

Using that in the fstab config works perfectly fine.  With the example given on the current wiki the server was denying the ev3 client access to mount the share.  With the full path mapped out, I was able to mount, view, and copy files to and from the share via the EV3.

Does this method work for anyone else?  I was unable to get any sort of function out of FreeNFS, but this is working perfectly as far as I can tell.

**Comment by dlech** [comment]
A tutorial page on this would be nice (at http://www.ev3dev.org/docs/tutorials/)

**Comment by dlech** [comment]
Looks like this is on our website

http://www.ev3dev.org/docs/tutorials/setting-up-an-nfs-file-share/
