### ISSUE TITLE
Include gir1.2-ev3devkit in the ev3dev image

### ISSUE THREAD

**Issue by cavenel** [ev3dev/ev3dev#857]
### What are you trying to do?
Import and use ev3devKit in Python with:
```
from gi.repository import Ev3devKit
```

### What did you expect to happen?
gir1.2-ev3devkit-0.4 to be installed by default in the ev3dev kernel.

### What actually happened?
gir1.2-ev3devkit-0.4 is not installed by default in the last ev3dev kernel:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "writer_ev3devKit.py", line 22, in <module>
    from gi.repository import Ev3devKit
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Ev3devKit, introspection typelib not found
```

### What hardware and software are you using (including version numbers)?
EV3 / [ev3dev-jessie-ev3-generic-2017-02-11](https://github.com/ev3dev/ev3dev/releases/download/ev3dev-jessie-2017-02-11/ev3dev-jessie-ev3-generic-2017-02-11.zip)

**Comment by dlech** [comment]
This is now included in the latest ev3dev-jessie snapshot.
