### ISSUE TITLE
Opening up the wiki

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#878]
As an experiment, I'm opening up the wiki to lower the bar for people contributing documentation. Feel free to put whatever you want there (as long as it is related to ev3dev, obviously). I see it as a way to say "hey, look at this neat thing I figured out how to do" without having to spend the time writing up polished documentation. Let's see what happens...

**Comment by WasabiFan** [comment]
🍿

**Comment by WasabiFan** [comment]
Can we delete the sidebar now that everything has been removed?

**Comment by dlech** [comment]
I just did

**Comment by dlech** [comment]
It seems that opening this issue does not help get contributors for the wiki. Oh well.
