### ISSUE TITLE
Add ppp kernel module for dialup support

### ISSUE THREAD

**Issue by alexissusset** [ev3dev/ev3dev#879]
### What are you trying to do?
use wvdial and/or NetworkManager to work with 3G Dongles

### What did you expect to happen?
Expected wvdial and NetworkManager to run as they do on base RPI Jessy image

### What actually happened?
wvdial starts correctly but fails when trying to establish ppp link as ppp kernel module isn't available

### What hardware and software are you using (including version numbers)?
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-04-14
Kernel version:     4.9.22-ev3dev-1.1.0-ev3
Board:              LEGO MINDSTORMS EV3
Revision:           0000
Brickman:           0.9.0
ev3devKit:          0.5.1
```

**Comment by dlech** [comment]
These modules have been in the last couple kernel releases. Hopefully it is working.
