### ISSUE TITLE
Should we split issues into questions and bugs?

### ISSUE THREAD

**Issue by markyi370** [ev3dev/ev3dev#887]
Just a thought off the top of my head...

Should we have a separate question/answer place and issues/bugs place for ev3dev?

If we do, perhaps a WordPress blog with [this plugin](https://github.com/designwall/dw-question-answer) would be helpful.

**Comment by dlech** [comment]
I'm not interested in maintaining yet another website, especially a wordpress site.

Also see #769.

**Comment by markyi370** [comment]
Okay, thanks @dlech.
