### ISSUE TITLE
EV3 Motor Specifications

### ISSUE THREAD

**Issue by fishworx** [ev3dev/ev3dev#895]
### What are you trying to do?
I am trying to create Matlab control systems (DC motor PID control) for EV3 Large and Medium motors. I am looking for the following motor parameters. Does anybody know these parameters? (Numbers shown are examples from Matlab)

R= 2.0 % Ohms
L= 0.5 % Henrys
Km = 0.015 % torque constant
Kb = 0.015 % emf constant
Kf = 0.2 % Nms (motor friction)
J= 0.02 % kg.m^2

### What did you expect to happen?
N/A

### What actually happened?
N/A

### What hardware and software are you using (including version numbers)?
N/A

**Comment by dlech** [comment]
http://nxt-unroller.blogspot.com/2015/03/mathematical-model-of-lego-ev3-motor.html
