### ISSUE TITLE
Is it possible to upgrade BrickPi3 if you have EV3Dev installed?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#897]
Hi,

This morning I read this news and the changelog for Raspi 2 with Jessie:
http://www.ev3dev.org/news/2017/04/15/kernel-release-cycle-20/
https://github.com/ev3dev/ev3dev-kpkg/blob/a90ed59ed7ece41c46c564653b4acb4a1dd4640c/ev3dev-ev3/changelog

And I would like to know if the process to upgrade the firmware for BrickPi3 is possible to run on EV3Dev.
https://github.com/DexterInd/BrickPi3/blob/master/Firmware/README.md

``` 
* Update to lego driver level 20:
    * Update for BrickPi3 firmware 1.4.x (thanks @sanjayseshan)
    * Fix stopping before run-to-*-pos is complete when stop_action is hold
```

Once I have upgrade the firmware for BrickPi3 and installed latest version of EV3Dev, is it possible to use the other stop actions (**"hold"**, **"coast"** & **"brake"**) with `BrickPi3` and latest EV3Dev? At the moment, I only can use this stop actions with `EV3 Brick` but not with BrickPi+ or `PiStorms`

Juan Antonio

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/issues/889#issuecomment-302974273

As far as I can remember, you should be able to use all stop actions on all platforms.

**Comment by jabrena** [comment]
Many thanks @dlech,

I will test this week.

Cheers

**Comment by jabrena** [comment]
Good morning @dlech, 

I tested with BrickPi+ and PiStorms V2 with latest stable image:
http://www.ev3dev.org/news/2017/02/11/ev3dev-jessie-2017-02-11-release/

and you have reason, Stop modes run nice in every platform.

Cheers

Juan Antonio

**Comment by jabrena** [comment]
Many thanks @dlech 

I could upgrade the firmware and add the support for BrickPi3.

Tomorrow, I will open a issue about some mode for GyroSensor.
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/329
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/188

Cheers

Juan Antonio
