### ISSUE TITLE
How to use a Grove Sensor port included on BrickPi3?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#911]
Hi,

Recently, the kernel was updated to add support for BrickPi3 and I would like to know, how to use the Grove Sensor Port included with the board. I suppose that it is necessary to send/receive I2C messages, but I don´t know if exist some example or technical documentation.

Many thanks in advance.

Juan Antonio

**Comment by dlech** [comment]
There is nothing special about ev3dev here. Try <https://github.com/DexterInd/GrovePi>.

**Comment by JorgePe** [comment]
Not BrickPi but in case someone searching for it gets here, I used the Mindsensors Grove adapter with ev3dev on EV3
http://ofalcao.pt/blog/2017/using-grove-devices-to-the-ev3

It's really just a matter of using the proper I2C commands.

**Comment by jabrena** [comment]
Hi,

Many thanks for the article. The question was about the i2c commands to read values from the new grove port added on the BrickPi3 board, so when I user connect a grove sensor into the grove input port, it is possible to follow the commands described in the article from @JorgePe ?

Juan Antonio

**Comment by JorgePe** [comment]
The concepts look similar...
BrickPi3 seems to have a GrovePi, an Arduino-based board that uses i2C at address 0x04 - at least as I understand from a quick reading of this library:
https://github.com/DexterInd/GrovePi/blob/master/Software/Python/grovepi.py
You should read that file to understand how to set the board to INPUT or OUTPUT and how to send commands to the Grove devices through it.

They also have code in C, perhaps it's better (you're trying to port to Java?)
Bah, they even have Java,
https://github.com/DexterInd/GrovePi/tree/master/Software/Java

**Comment by jabrena** [comment]
Many many thanks @dlech & @JorgePe for the technical support.

This weekend, I will to connect with a Grove Sensor.

Cheers

Juan Antonio

**Comment by JorgePe** [comment]
@jabrena are you going to try stacking? ( #910 )
I wonder if the I2C address of GrovePi is also changeable. If it isn't, you will have to (somehow) disable one of the Grove adapters.
Have to get time this summer holidays to test the BrickPi3 myself.

**Comment by jabrena** [comment]
Hi @JorgePe, 

Yes, yes I will try this summer but, now the focus is with ROSJava nodes:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/210
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/313
:)

Later, I will try with Stacking for BrickPi3 but I have to review the concept about MotorPort/SensorPort because until BrickPi3, every platform only has 4 ports and with this feature, the library should  handle until 16 Ports so I have to review it in detail.

Cheers

Juan Antonio

**Comment by dlech** [comment]
The Grove port on the BrickPi3 is connected directly to the I2C pins on the RPi. GrovePi is a totally separate board.

**Comment by JorgePe** [comment]
really? Then it is necessary something like an i2C hub to allow using more than one grove device.

**Comment by jabrena** [comment]
Hi @JorgePe,
Maybe this item could be pretty interesting...
http://www.robotshop.com/uk/grove-i2c-hub-extension-module.html
http://www.switchdoc.com/2016/12/new-product-3-3v-to-5v-i2c-converter-hub/
http://www.mindsensors.com/ev3-and-nxt/22-mounting-kit-for-grove-sensor
https://www.thingiverse.com/thing:1427428

new sensors!!! :D

**Comment by JorgePe** [comment]
I have the first. Do I really need a 3V3-5V converter?

**Comment by jabrena** [comment]
I don´t know. It is another hub. 
The first one is coming. :D
http://wiki.seeed.cc/Grove-I2C_Hub/

**Comment by JorgePe** [comment]
I'll start my summer holidays in a few days... hope I have time to test something, but kids deserve some attention. Will keep an eye on you to ;)

**Comment by jabrena** [comment]
ROS first but maybe some i2c commands in the middle :p

**Comment by jabrena** [comment]
Hi @JorgePe, 

A Grove electromagnet sensor is coming to follow your Article and learn the idea.

Cheers

**Comment by JorgePe** [comment]
:) That reminds me that my BrickPi 3 is still waiting for some of my attention.

**Comment by jabrena** [comment]
Yes yes, I will start with the Mindsensors adapter for EV3 and later, I will try to jump to BrickPi3.

Cheers

**Comment by jabrena** [comment]
Hi @dlech,

I try to find the technical documentation for the Grove adapter but I couldn´t find it.
http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensors.html#other-i2c-sensors
The unique reference is this post:
http://www.ev3dev.org/news/2017/02/11/ev3dev-jessie-2017-02-11-release/

Do you know the link?

Juan Antonio

**Comment by dlech** [comment]
To be clear, you are talking about the Grove I2C port on the BrickPi3 and not the Mindsensors Grove sensor adapter?

The link you gave is about BrickPi3. There is no documentation because it is just an I2C port. There are no special ev3dev features about it.

**Comment by jabrena** [comment]
Sorry, I talked about `Mindsensors Grove sensor adapter`.

**Comment by dlech** [comment]
There is no support in ev3dev for this sensor.

**Comment by jabrena** [comment]
Any reason? Complexity?

**Comment by dlech** [comment]
No one has asked about this sensor until now, so I suspect there is not much interest.

**Comment by jabrena** [comment]
I am not sure @dlech. 

Do you like If I could collaborate in the project trying to create that Driver? For me, the process will be a bit hard but I will learn in the process. :)

**Comment by dlech** [comment]
I would recommend starting with something much simpler and just use direct I2C commands for this sensor.

**Comment by jabrena** [comment]
Oki, 

In the next opportunity, I will try. :)

**Comment by JorgePe** [comment]
I believe me and @jabrena are the only ones using Mindsensors Grove Adapter with ev3dev :)
For me, direct I2C commands are fine.
But if someone is willing to write a driver, I can at least help with the tests.

**Comment by jabrena** [comment]
The `Iberia` team!!! :D

**Comment by Nyceane** [comment]
@JorgePe, I am using it, and can't find much resources...  I am having a difficult enough time just reading the data...
