### ISSUE TITLE
Error when transfering python file to /home/robot

### ISSUE THREAD

**Issue by lucky962** [ev3dev/ev3dev#914]
I am wondering how I would be able to transfer a file from my pc to /home/robot on my ev3dev.
I tried using FileZilla as recommended by someone on a forum. Although when I drag it into /home/robot this comes up:
Error:	/home/robot/First.py: open for write: received failure with description 'Failure'
Error:	File transfer failed
I then look into the "failed transfers" section and see the reason saying "Could not start transfer"

I just tried using WinSCP to transfer and it came up with this:
General failure (server should provide error description).
Error code: 4
Error message from server: Failure

Common reasons for the Error code 4 are:
- Renaming a file to a name of already existing file.
- Creating a directory that already exists.
- Moving a remote file to a different filesystem (HDD).
- Uploading a file to a full filesystem (HDD).
- Exceeding a user disk quota.

I have tried wiping my EV3 brick but this error still came up.

I'm not sure if my hardware/software info matters but here it is anyways:
brickman v0.8.1
Kernel: 4.4.68-20-ev3dev-ev3
Model: LEGO MINDSTORMS EV3 Programmable Brick

Thanks in advance for anyones help!

**Comment by lucky962** [comment]
I have just changed my SD card and now everything is working fine!
Thank you @dlech for suggesting this for me!

**Comment by dlech** [comment]
Awsome!
