### ISSUE TITLE
No Sharing Tab in Wi-Fi Properties

### ISSUE THREAD

**Issue by lucky962** [ev3dev/ev3dev#915]
### What are you trying to do?
I am trying to connect my EV3 brick to the internet.

### What did you expect to happen?
I expected to see a sharing tab (as I read in many tutorials) in my Wi-Fi properties to be able to share my internet with my EV3 brick that's connected to my computer using Bluetooth.

### What actually happened?
There was no sharing tab in Wi-Fi properties.

### What hardware and software are you using (including version numbers)?
brickman v0.8.1
Kernel: 4.4.68-20-ev3dev-ev3
Model: LEGO MINDSTORMS EV3 Programmable Brick

### Other things that might be important.
I searched this problem up and some people said that I need more than 1 internet connections. How do I do that?
I also tried to connect my ev3 brick using USB although it always says this:
![image](https://user-images.githubusercontent.com/30067456/28098780-9d339ae4-66fb-11e7-8984-666a97581961.png)
If someone could give me a fix about any of these, it would be greatly appreciated!

**Comment by dwalton76** [comment]
@lucky962 when you say `see a sharing tab (as I read in many tutorials)` do you mean a sharing tab on your windows machine? 

What is the problem you are trying to solve...is it just to get your ev3dev on wifi?  If so there are steps in the "With a Wi-Fi dongle" at http://www.ev3dev.org/docs/networking/

**Comment by dlech** [comment]
Given the fact that you have had two unusual problems I'm starting to wonder if you have a bad SD card. Do you have another SD card you can try?

**Comment by lucky962** [comment]
@dwalton76 Yes sorry, I forgot to say that I was on Windows 10. Yes, I was hoping to get it connected to the Wi-Fi with Bluetooth but I guess I will just have to buy a Wi-Fi dongle. Which Wi-Fi Dongle would you recommend? I have seen the ones on the networking page but is there any real difference between them?
@dlech I feel like the File Transfer didn't work because I didn't have internet but I'll try another SD card.

Thank you guys for the help!

Edit: I have just tried using a Wi-Fi Dongle and now my Robot connects to the internet although I still cannot upload programs from pc to my EV3. I tried using WinSCP and it just comes up with the same error as before.
I am yet to try another SD card to see if anything will improve!

Edit2: I have just tried another SD card and now I can import files onto my EV3!!! Everything works now!!! Thank you so much for helping me guys!

**Comment by WasabiFan** [comment]
Glad to hear that everything worked out! If you have suggestions for how our docs could be improved, don't hesitate to tell us.
