### ISSUE TITLE
ev3dev-buildscripts : help needed

### ISSUE THREAD

**Issue by JorgePe** [ev3dev/ev3dev#919]
Sorry if this is trivial but I'm stuck following ev3dev-buildscripts guidelines at
https://github.com/ev3dev/ev3dev-buildscripts

I'm running Ubuntu 17.04
`4.10.0-26-lowlatency #30-Ubuntu SMP PREEMPT Tue Jun 27 10:37:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

At step 2, after the 2 git commands complete and I change to my work directory I get a fatal error trying to manually pull driver submodule:

```
~/Documents/Personal/LEGO/ev3dev/work/ev3-kernel/drivers/lego$ git pull origin master
fatal: Couldn't find remote ref master
```

I've no experience with git but it seems I'm missing the definition of master:
```
git branch -a
* (HEAD detached at 63dbce8)
  ev3dev-stretch
  remotes/origin/HEAD -> origin/ev3dev-stretch
  remotes/origin/ev3dev-jessie
  remotes/origin/ev3dev-stretch
  remotes/origin/issue-661
  remotes/origin/ms-pps58-nx
  remotes/origin/wedo-names
  remotes/origin/wedo-servo
```

**Comment by dlech** [comment]
Hmm... maybe I forgot to push something... let me check...

**Comment by dlech** [comment]
Wait a minute. the problem is `master` there is no branch name `master`.
 
just do 

    git checkout ev3dev-stretch
    git pull

**Comment by JorgePe** [comment]
Thanks, it worked.
I'm suprised, just 8 minutes to compile a kernel, I was afraid it would take much longer. Now I can afford to make much more mistakes :)
