### ISSUE TITLE
Daisy chaining two EV3s?

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev#92]
I'm currently working on a project where I have two EV3s working in tandem. One is the host with some control logic on it, while the other controls some extra motors (just a slave). I'm trying to find the best way to control the second one with the main one over the USB connection (the host port on 1 to the client on 2). What's the best way to do this?

My preferred method would be to use a built-in protocol to control the second one, but I haven't seen any mention of a built-in USB protocol for direct control.

**Comment by GerardWassink** [comment]
Curious as to how things developed since this last post...
I like the exposé about the OSI layers, it makes things clear and gives the opportunity ti use standard protocols that are already in place.
.

**Comment by dlech** [comment]
I've seen some people using MQTT lately for brick-to-brick communications, but there is still no "official" built-in daisy chaining mechanism.

**Comment by dwalton76** [comment]
> Furthermore, why limit it to only two EV3's? When we use WiFi, apart from computing power in a brick, there's no reason why we couldn't make it limitless right?

Agreed, I can't think of a good reason to limit it to two.  SSDP could be used to find the other EV3s on the LAN.  I haven't tried it yet but here is a [SSDP](https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol) implementation (client and server) written in python:
https://gist.github.com/schlamar/2428250

The next step though, the actual controlling of another ev3, I think that would need to be done via  ev3dev-lang-python, ev3dev-lang-cpp, etc.
