### ISSUE TITLE
Is it possible to turn on a EV3 Brick without the ENTER Button?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#933]
Hi,

I would like to know if exist some way to turn on a EV3 Brick without clicking the ENTER Button.

Many thanks in advance.

Juan Antonio

**Comment by dlech** [comment]
Not without modifying the hardware.

**Comment by jabrena** [comment]
Oki.  :(

With `BrickPi+` & `PiStorms V2`, if you disconnect the battery connection, is possible to restart that Bricks. In `BrickPi3`, it is necessary to build some kind of mechanical tool to `turn off` and later `turn on`. Maybe for EV3, one alternative could create some kind of FLL tool to use an external motor to click on ENTER Button, but this idea is a bit complex.

Thanks @dlech 

Cheers

Juan Antonio
