### ISSUE TITLE
Is it possible to use the built-in speakers with an iPhone?

### ISSUE THREAD

**Issue by maluueu** [ev3dev/ev3dev#941]
### What are you trying to do?

I'm trying to use the built-in speakers with an iPhone.

**Comment by dlech** [comment]
Can you give some more details on what exactly you are trying to do? Do you want to play audio from the iPhone on the speaker in the EV3?

**Comment by maluueu** [comment]
Yes, exactly I want to play music from my iPhone on my EV3 using the built-in speakers of the EV3.

**Comment by dlech** [comment]
There is some information on how to do this [here](https://github.com/ev3dev/ev3dev/issues/198#issuecomment-62339000) and maybe [here](https://github.com/ev3dev/ev3dev.github.io/pull/24/files).

**Comment by maluueu** [comment]
I'll try it. 

	
Marlon Alkan
about.me/marlonalkan

**Comment by maluueu** [comment]
Nope it isn't working. I can connect via Bluetooth but I can't Play  Music on the Ev3
