### ISSUE TITLE
Doubt about Gyro Filter command on AbsoluteIMU support

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#949]
Hi,

I was checking the technical documentation for the Mindsensors IMU:
http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#ms-absolute-imu

But I discovered that using the API, it is not possible to use the feature to set a filter for gyro data:
http://www.mindsensors.com/ev3-and-nxt/15-gyro-multisensitivity-accelerometer-and-compass-for-nxt-or-ev3
http://www.mindsensors.com/pdfs/AbsoluteIMU-User-Guide.pdf

```
protected static final int  GYRO_FILTER         = 0x5a;
```

In my Brick, I have connected the sensor on Port 1 and the brick detects the I2C device connected:

```
robot@brick1:~$ ls /dev/i2c-in*
/dev/i2c-in1  /dev/i2c-in2
robot@brick1:~$ udevadm info -q path -n /dev/i2c-in1
/devices/platform/legoev3-ports/lego-port/port0/i2c-legoev3.3/i2c-3/i2c-dev/i2c-3
``` 

How to write the register 0x5a to set a value from 0-7?

Many thanks in advance

Juan Antonio

**Comment by dlech** [comment]
> How to write the register 0x5a to set a value from 0-7?

See http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/i2c.html#direct-reading-and-writing-of-the-sensor

**Comment by jabrena** [comment]
Many thanks @dlech,

Now, I can write and read:

``` 
robot@brick1:/sys/class/lego-sensor$ ls
sensor1
robot@brick1:/sys/class/lego-sensor$ cd sensor1
robot@brick1:/sys/class/lego-sensor/sensor1$ ls
address   bin_data_format  commands  device  driver_name  mode   num_values  power      text_value  units   value1  value3  value5  value7
bin_data  command          decimals  direct  fw_version   modes  poll_ms     subsystem  uevent      value0  value2  value4  value6
robot@brick1:/sys/class/lego-sensor/sensor1$ echo -e -n "4" | dd bs=1 of=direct seek=$(( 0x5a ))
1+0 records in
1+0 records out
1 byte (1 B) copied, 0.0097268 s, 0.1 kB/s
robot@brick1:/sys/class/lego-sensor/sensor1$ hd -s $(( 0x5a )) -n 8 direct
0000005a  34 00 00 00 00 00 00 00                           |4.......|
00000062
robot@brick1:/sys/class/lego-sensor/sensor1$ echo -e -n "6" | dd bs=1 of=direct seek=$(( 0x5a ))
1+0 records in
1+0 records out
1 byte (1 B) copied, 0.00913921 s, 0.1 kB/s
robot@brick1:/sys/class/lego-sensor/sensor1$ hd -s $(( 0x5a )) -n 8 direct
0000005a  36 00 00 00 00 00 00 00                           |6.......|
00000062
robot@brick1:/sys/class/lego-sensor/sensor1$ 
```  

But, in order to read the register `0x5a` does exist another way in order to parse the output in a easier way?  This output is complex to parse:

``` 
robot@brick1:/sys/class/lego-sensor/sensor1$ hd -s $(( 0x5a )) -n 8 direct
0000005a  36 00 00 00 00 00 00 00                           |6.......|
00000062
robot@brick1:/sys/class/lego-sensor/sensor1$ 
```

**Comment by dlech** [comment]
Which programming language do you want to use?

**Comment by jabrena** [comment]
`Java`, in my case.

**Comment by dlech** [comment]
does it have low level read, write and seek functions for files?

**Comment by jabrena** [comment]
Hi @dlech,

Are you talking about this one?
https://www.tutorialspoint.com/java/io/randomaccessfile_seek.htm

---

For the statement to set the value on the register, I have some problem:

```
echo -e -n "4" | dd bs=1 of=direct seek=$(( 0x5a ))
``` 

In a dynamic way, the Java program has to write the value on direct:

```
echo -e -n "5" | dd bs=1 of=/sys/class/lego-sensor/sensor1/direct seek=$(( 0x5a ))
``` 

But, internally I use the classic:

```
Runtime.getRuntime().exec(command);
```

https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/src/main/java/ev3dev/utils/Shell.java

Does exist other way in the second part of the statement to put the value (5) directly to avoid have to use a pipe?

Juan Antonio

**Comment by dlech** [comment]
OK, so maybe something like this:

```java
RandomAccessFile direct = new RandomAccessFile("/sys/class/lego-sensor/sensor1/direct", "rw");

// writing
// equivalent of echo -e -n "\x04" | dd bs=1 of=direct seek=$(( 0x5a ))
direct.seek(0x5a);
direct.writeByte(4);

// reading
// equivalent of hd -s $(( 0x5a )) -n 1 direct
direct.seek(0x05a);
byte data = direct.readByte();
```

**Comment by jabrena** [comment]
Hi @dlech,

using the idea that you say, it is possible to write in the file but the value doesn`t write the same part that manually:

``` 
RandomAccessFile direct = new RandomAccessFile("/sys/class/lego-sensor/sensor1/direct", "rw");

// writing
// equivalent of echo -e -n "\x04" | dd bs=1 of=direct seek=$(( 0x5a ))
direct.seek(0x5a);
direct.writeByte((byte)2);
```

Output:

```
robot@brick1:/sys/class/lego-sensor/sensor2$ hd -s $(( 0x5a )) -n 8 direct
0000005a  02 00 00 00 00 00 00 00                           |........|
00000062

``` 

If I execute manually:

``` 
robot@brick1:/sys/class/lego-sensor/sensor2$  echo -e -n "5" | dd bs=1 of=/sys/class/lego-sensor/sensor2/direct seek=$(( 0x5a ))
1+0 records in
1+0 records out
1 byte (1 B) copied, 0.00999186 s, 0.1 kB/s
robot@brick1:/sys/class/lego-sensor/sensor2$ hd -s $(( 0x5a )) -n 8 direct
0000005a  35 00 00 00 00 00 00 00                           |5.......|
00000062
```

**Comment by jabrena** [comment]
I found a solution:

If value = 1:

``` java
        final String i2c_command2 = "echo \"" + value + "\" | dd bs=1 of=" + this.PATH_DEVICE + "/direct seek=$(( 0x5a ))";
        String[] cmd = {
                "/bin/sh",
                "-c",
                i2c_command2
        };
        String response = Shell.execute(cmd);
``` 

Execution:

``` 
ev3dev#3|2017-09-03 19:52:43 [main] INFO  ev3dev.utils.Shell - Command chunk: /bin/sh
ev3dev#3|2017-09-03 19:52:43 [main] INFO  ev3dev.utils.Shell - Command chunk: -c
ev3dev#3|2017-09-03 19:52:43 [main] INFO  ev3dev.utils.Shell - Command chunk: echo "1" | dd bs=1 of=/sys/class/lego-sensor/sensor2/direct seek=$(( 0x5a ))
```

Review by command line:

```
robot@brick1:/sys/class/lego-sensor/sensor2$ hd -s $(( 0x5a )) -n 8 direct
0000005a  31 00 00 00 00 00 00 00                           |1.......|
00000062
robot@brick1:/sys/class/lego-sensor/sensor2$ 
```

I think that you have reason, I will research about seek features with Java

**Comment by dlech** [comment]
> using the idea that you say, it is possible to write in the file but the value doesn`t write the same part that manually:

It looks the same to me. In java, you write `(byte)2` and `hd` shows hex `02` as the first byte.

In bash, you write ASCII "5", which is 0x35 and `hd` shows hex `35` as the first byte.

**Comment by jabrena** [comment]
Tomorrow, I will review again the notes that you say.

**Comment by dlech** [comment]
Can this be closed?

**Comment by jabrena** [comment]
I will review today
