### ISSUE TITLE
How to read a Boolean value from Grove Adapter?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#950]
Hi, I am following the article from @JorgePe and the Documentation from the sensor which I am using for the Tests:
http://wiki.seeed.cc/Grove-PIR_Motion_Sensor/

And I have a doubt about how to read a Digital value from the sensor.

In the article about the Grove Adapter, it explains how to set true|false for the sensor: 
http://wiki.seeed.cc/Grove-Electromagnet/
http://ofalcao.pt/blog/2017/using-grove-devices-to-the-ev3

Using the following commands:

```
sudo i2cset -y 3 0x21 0x41 0x54
sudo i2cset -y 3 0x21 0x42 0x03
``` 

```
sudo i2cset -y 3 0x21 0x41 0x54
sudo i2cset -y 3 0x21 0x42 0x02
```  

But in my case, the Sensor returns true or false. 
In the following Arduino Sketch, it is possible to see the idea:

``` arduino
/*macro definitions of PIR motion sensor pin and LED pin*/
#define PIR_MOTION_SENSOR 2//Use pin 2 to receive the signal from the module
#define LED 4//the Grove - LED is connected to D4 of Arduino


void setup()
{
    pinMode(PIR_MOTION_SENSOR, INPUT);
    pinMode(LED,OUTPUT);
}

void loop()
{
    if(isPeopleDetected())//if it detects the moving people?
        digitalWrite(LED, HIGH);
    else
        digitalWrite(LED, LOW);
}


/***************************************************************/
/*Function: Detect whether anyone moves in it's detecting range*/
/*Return:-boolean, true is someone detected.*/
boolean isPeopleDetected()
{
    int sensorValue = digitalRead(PIR_MOTION_SENSOR);
    if(sensorValue == HIGH)//if the sensor value is HIGH?
    {
        return true;//yes,return true
    }
    else
    {
        return false;//no,return false
    }
}
```  

So, in this case, what is the way to read a value with Boolean nature?

Many thanks in advance.

Juan Antonio

**Comment by dlech** [comment]
`i2set` will write to the device. If you want to read data, you would need to use `i2cget`.

**Comment by jabrena** [comment]
Many thanks @dlech,

I will read the documentation:
http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/i2c.html

and some technical docs about i2c:
https://linux.die.net/man/8/i2cget
https://www.cs.sfu.ca/CourseCentral/433/bfraser/other/I2CGuide.pdf

Juan Antonio

**Comment by dlech** [comment]
Can this be closed?
