### ISSUE TITLE
Wi-Fi wiki page

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev#955]
I started a Wi-Fi wiki page. https://github.com/ev3dev/ev3dev/wiki/USB-Wi-Fi-Dongles

If you use Wi-Fi with ev3dev, please take a minute to add your device to the list.

**Comment by JorgePe** [comment]
Added ASUS USB-N10 Nano to the known working dongles. Not quite the same chipset as the Edimax but it works fine, also with LeJOS.

**Comment by BertLindeman** [comment]
Updated:

Typo "and" should be "add" on the first line.

Added 
`and the Raspberry Pi Zero W`
to
`Built-in Wi-Fi on the Raspberry Pi 3  is also supported`

**Comment by trofimovdev** [comment]
Added `D-Link DWL-G132`. Works great.

**Comment by DozenCoder** [comment]
Are there any dongle support 5G-hz WIFI?

**Comment by dlech** [comment]
I suspect that all of the supported dongles are capable of 5GHz since they all are capable of 802.11n.

**Comment by DozenCoder** [comment]
@dlech I use the officially supported dongle: "WNA1100 Wireless-N 150`, it says that it's capable of 802.11n, but it only support 2.4000~2.4835GHz from its packaging introduction, and I can only see 2.4GHz wifi from EV3's screen.

**Comment by dlech** [comment]
Thanks to everyone who edited the page.
