### ISSUE TITLE
How to use GRX?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#961]
Hi @dlech,

I read some weeks ago that GRX is the solution to manage display.

Does exist some documentation to use it?
https://github.com/ev3dev/grx

many thanks in advance.

Juan Antonio

**Comment by WasabiFan** [comment]
http://docs.ev3dev.org/projects/grx/en/latest/ ? (linked to in the README)

**Comment by jabrena** [comment]
Hi @WasabiFan, many thanks for the link.
I notice that it is necessary to integrate with this concept:
https://wiki.gnome.org/Projects/GObjectIntrospection

I will review with this `Java` library in order to run `GRX` using `GObject Introspection`
https://wiki.gnome.org/Projects/JGIR

Juan Antonio

**Comment by dlech** [comment]
Can this be closed?

**Comment by JakubVanek** [comment]
This is not necessary anymore, because we have [pure Java support for display](https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/docs/adr/adr-display-api.md) now.
