### ISSUE TITLE
Doubt about cross compilation for EV3

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#964]
Hi,

I am reviewing the `Dockerfiles` from the repo:
https://github.com/ev3dev/docker-cross

And I have a doubt about the way to compile software inside of this kind of images.

When you run a Docker image about EV3Dev:
https://github.com/ev3dev/docker-cross/blob/master/ev3dev-jessie/debian-jessie-armel.dockerfile

If you compile a C program with normal `gcc` but not using `gcc-linaro-arm-linux-gnueabihf` in that case, the binary compiled doesn`t run in this case on an EV3 Brick?

``` 
# install the cross-compiler toolchain
ADD http://releases.linaro.org/14.04/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux.tar.xz /opt/
RUN cd /opt && \
    tar xf gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux.tar.xz && \
    rm gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux.tar.xz
COPY toolchain.cmake.armel /opt/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/toolchain.cmake

# setup a new user
COPY compiler.sudoers /etc/sudoers.d/compiler
RUN chmod 0440 /etc/sudoers.d/compiler && \
    adduser --disabled-password --gecos \"\" compiler && \
    usermod -a -G sudo compiler
USER compiler
WORKDIR /home/compiler
CMD ["/bin/bash"] ["--login"]
```

Many thanks in advance

Juan Antonio

**Comment by dlech** [comment]
See https://github.com/ev3dev/docker-cross/blob/master/ev3dev-jessie/toolchain.cmake.armel

You need to pass some extra arguments to the compiler to get it to build for EV3.
