### ISSUE TITLE
ev3dev PyCharm Tutorial Problem (Cloning Repository)

### ISSUE THREAD

**Issue by lucky962** [ev3dev/ev3dev#972]
### What are you trying to do?
I am trying to "Set Up a Python Development Environment with PyCharm" using this tutorial. http://www.ev3dev.org/docs/tutorials/setting-up-python-pycharm/

### What did you expect to happen?
At the Checkout from GIT part when we have to clone the repository, I was expecting a window to open up, just like the tutorial described.

### What actually happened?
Sometimes, a loading bar popped up and disappeared straight away, other times, the dialogue box just disappeared when I clicked clone.

### What hardware and software are you using (including version numbers)?
PyCharm Community Edition Version 2017.2.3
Windows 10
Model: LEGO MINDSTORMS EV3 Programmable Brick
Brickman v0.8.1

Thanks in advance for any help!

**Comment by dlech** [comment]
You might consider trying ev3dev-stretch with Visual Studio Code instead of PyCharm. It should be easier to setup. 

Docs are still a work in progress though: http://docs.ev3dev.org/en/ev3dev-stretch/
