### ISSUE TITLE
TAKE SNAPSHOTS WITH USB CAMERA 

### ISSUE THREAD

**Issue by Negociation** [ev3dev/ev3dev#977]
Hi i opened early today a issue to use PiXY Camera to take snapshots , but aparently i can't do that. :( 

- I read  on internet i probably can use a commom usb camera to take snapshots with EV3DEV + Python , thats is correct ? 

- If i can , someone recommends me a model or/with sample code , to take snapshots and save like PNG/TIFF/JPG on SD Card ?

- I will use a Socket Conection to send this picture to my Tablet

**Comment by dwalton76** [comment]
You can use fswebcam to take a picture with a variety of usb webcams (including the lego one).  It isn't very fast on an ev3 though, it takes a few seconds to take a pic.
