### ISSUE TITLE
Where's the "Network Connection" button after pairing?

### ISSUE THREAD

**Issue by reaz2ytech05** [ev3dev/ev3dev#981]
The "Network Connection" button didn't show up after accepting the pairing code, and when I press the "Connect" button, it said "GDBus.Error:org.bluez.Error.Failed: No such file or directory".  Also, the status after pairing in the "Wireless and Networks" read "No Connections".  I don't really know what is going on.

**Comment by dlech** [comment]
If a Network Connection button did not appear after pairing, then whatever you are pairing to does not have a Bluetooth network service to connect to. It's hard to say what is going on without more details of exactly what you are trying to do.
