### ISSUE TITLE
can i get back to the original ev3 os after this

### ISSUE THREAD

**Issue by Ekam3284** [ev3dev/ev3dev#983]
i want to do this but  i am curious that would i be able to get back to the previous os after this

**Comment by JorgePe** [comment]
Sure.
ev3dev is a linux operating system in the SD card - if you power the EV3 ON with the SD card inside, the LEGO firmware detects the SD card and passes to it.
If you remove the SD card and power your EV3 again, it is your good old EV3 again.

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/wiki/Frequently-Asked-Questions#how-do-you-switch-back-to-the-official-lego-firmware-after-using-ev3dev
