### ISSUE TITLE
ftrace does't work

### ISSUE THREAD

**Issue by perkinbr** [ev3dev/ev3dev#991]
### What are you trying to do?
Trying to enable ftrace in the kernel

### What did you expect to happen?
ftrace to be enabled

### What actually happened?
Kernel crashes very very early in boot.  I tried to enable early kgdb and early serial messages but saw no signs of life.  I just see the serial uboot message saying it started the kernel but seems to get no farther

### What hardware and software are you using (including version numbers)?

I tried this with Jessie and Stretch as well.  I tried disabling the dynamic ftrace and the call graph stuff.
Same results.

Image file:         ev3dev-stretch-ev3-generic-2017-09-30
Kernel version:     4.9.49-ev3dev-1.5.1-perkinbr15-ev3+
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=001653462FE6
BOARD_INFO_TYPE=main

(kernel version is a custom compile.  ftrace is off, obviously)

I don't really need this feature currently, but I thought I'd report the issue so people are aware of it.  I pretty much got the info I needed from perf instead (which seems to work) .

**Comment by dlech** [comment]
Thanks for reporting.

I'm going to go ahead and close this as wontfix since you don't really need it.

FWIW, I've successfully used early printk on the serial port before, so that problem is probably just a matter of configuration.
