### ISSUE TITLE
BrickPi3: Are ev3-uart devices supported?

### ISSUE THREAD

**Issue by kortschak** [ev3dev/ev3dev#995]
### What are you trying to do?
Connect an ev3-uart device to a BrickPi3.

### What did you expect to happen?
Not entirely sure given that they don't work with BrickPi+

### What actually happened?
```
~$ echo none >/sys/class/lego-port/port0/mode
~$ echo ev3-uart >/sys/class/lego-port/port0/mode
~$ echo fcl-altitude >/sys/class/lego-port/port0/set_device 
~$ ls /sys/class/lego-sensor/
~$ 
```

The equivalent incantations for nxt-i2c work fine.
```
~$ echo none >/sys/class/lego-port/port0/mode
~$ echo nxt-i2c >/sys/class/lego-port/port0/mode 
~$ echo ms-absolute-imu 0x11 >/sys/class/lego-port/port0/set_device
~$ ls /sys/class/lego-sensor/
sensor0
```

### What hardware and software are you using (including version numbers)?

```
Image file:         ev3dev-stretch-rpi2-generic-2017-09-30
Kernel version:     4.9.50-ev3dev-1.5.1-rpi2
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=A02082
BOARD_INFO_MODEL=Raspberry Pi 3 Model B Rev 1.2
BOARD_INFO_SERIAL_NUM=000000008b3a279a
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_FW_VER=1.4.3
BOARD_INFO_HW_REV=3.2.1
BOARD_INFO_MODEL=Dexter Industries BrickPi3
BOARD_INFO_SERIAL_NUM=1AC2CEB0514D355934202020FF0E2540
BOARD_INFO_TYPE=aux
```

**Comment by dlech** [comment]
Only the 4 LEGO brand UART sensors will work. They are hard-coded in the BrickPi3 firmware. The same applies to BrickPi(+) and PiStorms and EV3 sensor multiplexer. There is no generic UART interface for these devices, so 3rd party sensor (and any future LEGO brand sensor) will require a firmware upgrade to the respective devices.

**Comment by kortschak** [comment]
Thanks.
