### ISSUE TITLE
Connecting EV3 brick with Bluetooth using ev3dev and Eclipse

### ISSUE THREAD

**Issue by edouardo17** [ev3dev/ev3dev#996]
Hi all,

I've been trying for a few days to connect my EV3 brick revision 0006 to my computer running on Ubuntu using a Bluetooth connection. I think I'm not far from success, but I still have a couple of issues I can't solve...
I'm using the ev3dev Brick Manager on my EV3 brick, running on brickman v0.8.1, and on the computer, I'm on the last release of Ubuntu 16.04 LTS.
As for my IDE, I'm using Eclipse Oxygen (latest release as well), and coding trying to execute some Java code on my brick. I also have installed the leJOS plugin in Eclipse.

I have created a Network Access Point with my brick, and am able to pair in Bluetooth in Ubuntu, which is already a good start. When I ping the brick using the IP address displayed at the top of my EV3 LCD screen, the device responds correctly to the packets sent. I don't have any issue either when I connect to my brick in the command line using `$ ssh robot@ev3dev.local`.
In Eclipse, I have configured the leJOS plugin in Window->Preferences->leJOS correctly, and ticked the "Use SSH" box.
I purposely ticked the "Use SSH" box because... well, just because it seemed to work better that way  :? 
Now, the issue I'm having comes when I want to run a program from Eclipse on the brick, I have the following message showing after hitting Run: 

`Jar file has been created successfully
Using scp for upload and ssh to execute program
Uploading to 10.42.0.165 ...
EV3ScpUpload: Failed to upload or run jar file: com.jcraft.jsch.JSchException: Auth cancel
Starting EV3ScpUpload failed with exit status 1
leJOS EV3 plugin launch complete`

When I choose to untick the SSH box, well... same kind of issue, the connection is refused...

`Jar file has been created successfully
Using the EV3 menu for upload and to execute program
IP address is /10.42.0.165
Creating the jar file or uploading the program failed
java.rmi.ConnectException: Connection refused to host: 10.42.0.165; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
Caused by java.net.ConnectException: Connection refused (Connection refused)
See Eclipse error log for detailed stack trace.
`

Does someone has an idea of where the problem is coming from? Isn't the brick refusing the connection even though it is properly connected to the laptop in Bluetooth? 

Many thanks in advance,
Edouard

**Comment by WasabiFan** [comment]
I am a bit doubtful that the LeJOS plugin will work with ev3dev. I've never used it, so I don't know what it does exactly, hut my guess is that it is attempting to use protocols and credentials that are specific to LeJOS.

**Comment by dlech** [comment]
If you want to use the leJOS plugin for Eclipse, then you also need to run leJOS on the EV3, not ev3dev. http://www.lejos.org/

If you want an IDE for ev3dev, then I would suggest trying ev3dev-stretch and Visual Studio Code. http://docs.ev3dev.org/en/ev3dev-stretch/
